import type {
  WorkTypeCoordinationContext,
  WorkTypeDefinition,
} from "./work-type.types";

const WORK_TYPES: WorkTypeDefinition[] = [
  {
    key: "publish",
    title: "Đăng bài",
    coordinationContext: "MEDIA",
    icon: "send",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["MEDIA"],
    workflowKey: "watch-publish",
    routingKeys: ["publish", "post", "listing"],
    enabled: true,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "media-processing",
    title: "Xử lý Media",
    coordinationContext: "MEDIA",
    icon: "images",
    defaultOwnerRole: "MEDIA",
    defaultParticipants: ["MEDIA"],
    workflowKey: "watch-media-processing",
    routingKeys: ["media-processing", "media", "content-image-processing"],
    enabled: true,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "review-content",
    title: "Duyệt nội dung",
    coordinationContext: "MEDIA",
    icon: "file-text",
    defaultOwnerRole: "MEDIA",
    defaultParticipants: ["MEDIA"],
    workflowKey: "watch-content-review",
    routingKeys: ["review-content", "content-review"],
    enabled: false,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "review-image",
    title: "Duyệt hình ảnh",
    coordinationContext: "MEDIA",
    icon: "image",
    defaultOwnerRole: "MEDIA",
    defaultParticipants: ["MEDIA"],
    workflowKey: "watch-image-review",
    routingKeys: ["review-image", "image-review"],
    enabled: false,
    sortOrder: 40,
    metadata: null,
  },
  {
    key: "photography",
    title: "Photoshoot",
    coordinationContext: "MEDIA",
    icon: "camera",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["MEDIA"],
    workflowKey: "watch-photography",
    routingKeys: ["photography", "photo-shoot", "shooting"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "order",
    title: "Đơn hàng",
    coordinationContext: "OPERATION",
    icon: "shopping-cart",
    defaultOwnerRole: "OPERATION",
    defaultParticipants: ["OPERATION"],
    workflowKey: null,
    routingKeys: ["order", "orders"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "shipment",
    title: "Giao hàng",
    coordinationContext: "OPERATION",
    icon: "truck",
    defaultOwnerRole: "OPERATION",
    defaultParticipants: ["OPERATION"],
    workflowKey: null,
    routingKeys: ["shipment", "shipping", "delivery"],
    enabled: true,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "technical",
    title: "Kỹ thuật",
    coordinationContext: "TECHNICAL",
    icon: "wrench",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "watch-operation-technical",
    routingKeys: ["technical", "strap-change", "operation-technical"],
    enabled: false,
    sortOrder: 50,
    metadata: null,
  },
  {
    key: "service-operation",
    title: "Service Operation",
    coordinationContext: "TECHNICAL",
    icon: "wrench",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL", "PAYMENT"],
    workflowKey: "service-operation-technical-bench",
    routingKeys: [
      "service-operation",
      "service",
      "technical-bench",
      "service-bench",
    ],
    enabled: true,
    sortOrder: 55,
    metadata: {
      workspaceType: "service-operation",
      itemLabel: "Technical Issue Operation",
      defaultView: "items",
      serviceCapabilities: [
        "service.sr_case_view",
        "service.technical_bench",
        "service.stage_board",
        "service.approval",
        "service.payment_request",
        "service.receive_previous_week",
        "service.activity",
      ],
      surfaces: [
        "SR Cases",
        "Technical Bench",
        "Stage Board",
        "Approval",
        "Payment",
        "Activity",
        "Info",
      ],
    },
  },
  {
    key: "quotation",
    title: "Báo giá",
    coordinationContext: "SALES",
    icon: "file-text",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-quotation",
    routingKeys: ["quotation", "quote"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "pricing",
    title: "Định giá",
    coordinationContext: "SALES",
    icon: "tag",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-pricing",
    routingKeys: ["pricing", "price-adjustment"],
    enabled: true,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "negotiation",
    title: "Thương lượng",
    coordinationContext: "SALES",
    icon: "messages-square",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-negotiation",
    routingKeys: ["negotiation", "sale"],
    enabled: true,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "marketing",
    title: "Marketing",
    coordinationContext: "SALES",
    icon: "megaphone",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES", "MEDIA"],
    workflowKey: "sales-marketing",
    routingKeys: ["marketing"],
    enabled: true,
    sortOrder: 40,
    metadata: null,
  },
  {
    key: "repair",
    title: "Sửa chữa",
    coordinationContext: "TECHNICAL",
    icon: "wrench",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-repair",
    routingKeys: ["repair"],
    enabled: false,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "inspection",
    title: "Kiểm tra",
    coordinationContext: "TECHNICAL",
    icon: "search",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-inspection",
    routingKeys: ["inspection"],
    enabled: false,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "warranty",
    title: "Bảo hành",
    coordinationContext: "TECHNICAL",
    icon: "shield-check",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-warranty",
    routingKeys: ["warranty"],
    enabled: false,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "payment",
    title: "Thanh toán",
    coordinationContext: "PAYMENT",
    icon: "credit-card",
    defaultOwnerRole: "PAYMENT",
    defaultParticipants: ["PAYMENT"],
    workflowKey: "payment-collection-workflow",
    routingKeys: ["payment", "payments"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "general",
    title: "Tổng quát",
    coordinationContext: "GENERAL",
    icon: "circle",
    defaultOwnerRole: null,
    defaultParticipants: [],
    workflowKey: "general",
    routingKeys: ["general", "other"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
];

export function listRegisteredWorkTypes() {
  return [...WORK_TYPES];
}

export function listRegisteredWorkTypesByContext(
  context: WorkTypeCoordinationContext,
) {
  return WORK_TYPES.filter(
    (workType) => workType.coordinationContext === context,
  );
}
