import type {
  WorkTypeCoordinationContext,
  WorkTypeDefinition,
} from "./work-type.types";

const WORK_TYPES: WorkTypeDefinition[] = [
  {
    key: "publish",
    title: "Đăng bài",
    coordinationContext: "OPERATION",
    icon: "send",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["OPERATION"],
    workflowKey: "watch-publish",
    routingKeys: ["publish", "post", "listing"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "review-content",
    title: "Review Content",
    coordinationContext: "OPERATION",
    icon: "file-text",
    defaultOwnerRole: "OPERATION",
    defaultParticipants: ["OPERATION"],
    workflowKey: "watch-content-review",
    routingKeys: ["review-content", "content-review"],
    enabled: false,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "review-image",
    title: "Review Image",
    coordinationContext: "OPERATION",
    icon: "image",
    defaultOwnerRole: "OPERATION",
    defaultParticipants: ["OPERATION"],
    workflowKey: "watch-image-review",
    routingKeys: ["review-image", "image-review"],
    enabled: false,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "photography",
    title: "Photography",
    coordinationContext: "OPERATION",
    icon: "camera",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["OPERATION"],
    workflowKey: "watch-photography",
    routingKeys: ["photography", "photo-shoot", "shooting"],
    enabled: true,
    sortOrder: 40,
    metadata: null,
  },
  {
    key: "technical",
    title: "Technical",
    coordinationContext: "TECHNICAL",
    icon: "wrench",
    defaultOwnerRole: "SYSTEM",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "watch-operation-technical",
    routingKeys: ["technical", "strap-change", "operation-technical"],
    enabled: true,
    sortOrder: 50,
    metadata: null,
  },
  {
    key: "quotation",
    title: "Quotation",
    coordinationContext: "SALES",
    icon: "file-text",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-quotation",
    routingKeys: ["quotation", "quote"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "pricing",
    title: "Pricing",
    coordinationContext: "SALES",
    icon: "tag",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-pricing",
    routingKeys: ["pricing", "price-adjustment"],
    enabled: true,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "negotiation",
    title: "Negotiation",
    coordinationContext: "SALES",
    icon: "messages-square",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES"],
    workflowKey: "sales-negotiation",
    routingKeys: ["negotiation", "sale"],
    enabled: true,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "marketing",
    title: "Marketing",
    coordinationContext: "SALES",
    icon: "megaphone",
    defaultOwnerRole: "SALES",
    defaultParticipants: ["SALES", "OPERATION"],
    workflowKey: "sales-marketing",
    routingKeys: ["marketing"],
    enabled: true,
    sortOrder: 40,
    metadata: null,
  },
  {
    key: "repair",
    title: "Repair",
    coordinationContext: "TECHNICAL",
    icon: "wrench",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-repair",
    routingKeys: ["repair"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
  {
    key: "inspection",
    title: "Inspection",
    coordinationContext: "TECHNICAL",
    icon: "search",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-inspection",
    routingKeys: ["inspection"],
    enabled: true,
    sortOrder: 20,
    metadata: null,
  },
  {
    key: "warranty",
    title: "Warranty",
    coordinationContext: "TECHNICAL",
    icon: "shield-check",
    defaultOwnerRole: "TECHNICAL",
    defaultParticipants: ["TECHNICAL"],
    workflowKey: "technical-warranty",
    routingKeys: ["warranty"],
    enabled: true,
    sortOrder: 30,
    metadata: null,
  },
  {
    key: "general",
    title: "General",
    coordinationContext: "GENERAL",
    icon: "circle",
    defaultOwnerRole: null,
    defaultParticipants: [],
    workflowKey: "general",
    routingKeys: ["general", "other"],
    enabled: true,
    sortOrder: 10,
    metadata: null,
  },
];

export function listRegisteredWorkTypes() {
  return [...WORK_TYPES];
}

export function listRegisteredWorkTypesByContext(
  context: WorkTypeCoordinationContext,
) {
  return WORK_TYPES.filter(
    (workType) => workType.coordinationContext === context,
  );
}
