import { PERMISSIONS } from "@/constants/permissions";

const IMPLICATIONS: Readonly<Record<string, readonly string[]>> = {
    // Legacy report access remains sales-only. Finance access must be explicit.
    [PERMISSIONS.REPORT_VIEW]: [PERMISSIONS.REPORT_SALES_VIEW],
    [PERMISSIONS.WATCH_ACQUISITION_CREATE]: [PERMISSIONS.WATCH_ACQUISITION_VIEW],
    [PERMISSIONS.WATCH_ACQUISITION_UPDATE]: [PERMISSIONS.WATCH_ACQUISITION_VIEW],
    [PERMISSIONS.WATCH_ACQUISITION_DELETE]: [PERMISSIONS.WATCH_ACQUISITION_VIEW],
    [PERMISSIONS.WATCH_ACQUISITION_APPROVE]: [PERMISSIONS.WATCH_ACQUISITION_VIEW],
    [PERMISSIONS.ACCESSORY_ACQUISITION_CREATE]: [PERMISSIONS.ACCESSORY_ACQUISITION_VIEW],
    [PERMISSIONS.ACCESSORY_ACQUISITION_UPDATE]: [PERMISSIONS.ACCESSORY_ACQUISITION_VIEW],
    [PERMISSIONS.ACCESSORY_ACQUISITION_DELETE]: [PERMISSIONS.ACCESSORY_ACQUISITION_VIEW],
    [PERMISSIONS.ACCESSORY_ACQUISITION_APPROVE]: [PERMISSIONS.ACCESSORY_ACQUISITION_VIEW],
    [PERMISSIONS.ACQUISITION_VIEW_ALL]: [PERMISSIONS.WATCH_ACQUISITION_VIEW, PERMISSIONS.ACCESSORY_ACQUISITION_VIEW],
    [PERMISSIONS.ACQUISITION_CREATE_ALL]: [PERMISSIONS.ACQUISITION_VIEW_ALL, PERMISSIONS.WATCH_ACQUISITION_CREATE, PERMISSIONS.ACCESSORY_ACQUISITION_CREATE],
    [PERMISSIONS.ACQUISITION_UPDATE_ALL]: [PERMISSIONS.ACQUISITION_VIEW_ALL, PERMISSIONS.WATCH_ACQUISITION_UPDATE, PERMISSIONS.ACCESSORY_ACQUISITION_UPDATE],
    [PERMISSIONS.ACQUISITION_DELETE_ALL]: [PERMISSIONS.ACQUISITION_VIEW_ALL, PERMISSIONS.WATCH_ACQUISITION_DELETE, PERMISSIONS.ACCESSORY_ACQUISITION_DELETE],
    [PERMISSIONS.ACQUISITION_APPROVE_ALL]: [PERMISSIONS.ACQUISITION_VIEW_ALL, PERMISSIONS.WATCH_ACQUISITION_APPROVE, PERMISSIONS.ACCESSORY_ACQUISITION_APPROVE],
    [PERMISSIONS.ORDER_CREATE]: [PERMISSIONS.ORDER_VIEW],
    [PERMISSIONS.ORDER_UPDATE]: [PERMISSIONS.ORDER_VIEW],
    [PERMISSIONS.ORDER_DELETE]: [PERMISSIONS.ORDER_VIEW],
    [PERMISSIONS.ORDER_APPROVE]: [PERMISSIONS.ORDER_VIEW],
    [PERMISSIONS.PRODUCT_CREATE]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.PRODUCT_UPDATE]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.PRODUCT_DELETE]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.PRODUCT_APPROVE]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.PRODUCT_COST_VIEW]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.PRODUCT_PRICE_EDIT]: [PERMISSIONS.PRODUCT_VIEW],
    [PERMISSIONS.ACCESSORY_CREATE]: [PERMISSIONS.ACCESSORY_VIEW],
    [PERMISSIONS.ACCESSORY_UPDATE]: [PERMISSIONS.ACCESSORY_VIEW],
    [PERMISSIONS.ACCESSORY_DELETE]: [PERMISSIONS.ACCESSORY_VIEW],
    [PERMISSIONS.SHIPMENT_CREATE]: [PERMISSIONS.SHIPMENT_VIEW],
    [PERMISSIONS.SHIPMENT_UPDATE]: [PERMISSIONS.SHIPMENT_VIEW],
    [PERMISSIONS.SHIPMENT_DELETE]: [PERMISSIONS.SHIPMENT_VIEW],
    [PERMISSIONS.SHIPMENT_APPROVE]: [PERMISSIONS.SHIPMENT_VIEW],
    [PERMISSIONS.SERVICE_CREATE]: [PERMISSIONS.SERVICE_VIEW],
    [PERMISSIONS.SERVICE_UPDATE]: [PERMISSIONS.SERVICE_VIEW],
    [PERMISSIONS.SERVICE_DELETE]: [PERMISSIONS.SERVICE_VIEW],
    [PERMISSIONS.CUSTOMER_CREATE]: [PERMISSIONS.CUSTOMER_VIEW],
    [PERMISSIONS.CUSTOMER_UPDATE]: [PERMISSIONS.CUSTOMER_VIEW],
    [PERMISSIONS.CUSTOMER_DELETE]: [PERMISSIONS.CUSTOMER_VIEW],
    [PERMISSIONS.ORDER_PAYMENT_CREATE]: [PERMISSIONS.ORDER_PAYMENT_VIEW],
    [PERMISSIONS.ORDER_PAYMENT_UPDATE]: [PERMISSIONS.ORDER_PAYMENT_VIEW],
    [PERMISSIONS.ORDER_PAYMENT_DELETE]: [PERMISSIONS.ORDER_PAYMENT_VIEW],
    [PERMISSIONS.ACQUISITION_PAYMENT_CREATE]: [PERMISSIONS.ACQUISITION_PAYMENT_VIEW],
    [PERMISSIONS.ACQUISITION_PAYMENT_UPDATE]: [PERMISSIONS.ACQUISITION_PAYMENT_VIEW],
    [PERMISSIONS.ACQUISITION_PAYMENT_DELETE]: [PERMISSIONS.ACQUISITION_PAYMENT_VIEW],
    [PERMISSIONS.SERVICE_PAYMENT_CREATE]: [PERMISSIONS.SERVICE_PAYMENT_VIEW],
    [PERMISSIONS.SERVICE_PAYMENT_UPDATE]: [PERMISSIONS.SERVICE_PAYMENT_VIEW],
    [PERMISSIONS.SERVICE_PAYMENT_DELETE]: [PERMISSIONS.SERVICE_PAYMENT_VIEW],
    [PERMISSIONS.SHIPMENT_PAYMENT_CREATE]: [PERMISSIONS.SHIPMENT_PAYMENT_VIEW],
    [PERMISSIONS.SHIPMENT_PAYMENT_UPDATE]: [PERMISSIONS.SHIPMENT_PAYMENT_VIEW],
    [PERMISSIONS.SHIPMENT_PAYMENT_DELETE]: [PERMISSIONS.SHIPMENT_PAYMENT_VIEW],
    [PERMISSIONS.PAYMENT_VIEW_ALL]: [PERMISSIONS.ORDER_PAYMENT_VIEW, PERMISSIONS.ACQUISITION_PAYMENT_VIEW, PERMISSIONS.SERVICE_PAYMENT_VIEW, PERMISSIONS.SHIPMENT_PAYMENT_VIEW],
    [PERMISSIONS.PAYMENT_CREATE_ALL]: [PERMISSIONS.PAYMENT_VIEW_ALL, PERMISSIONS.ORDER_PAYMENT_CREATE, PERMISSIONS.ACQUISITION_PAYMENT_CREATE, PERMISSIONS.SERVICE_PAYMENT_CREATE, PERMISSIONS.SHIPMENT_PAYMENT_CREATE],
    [PERMISSIONS.PAYMENT_UPDATE_ALL]: [PERMISSIONS.PAYMENT_VIEW_ALL, PERMISSIONS.ORDER_PAYMENT_UPDATE, PERMISSIONS.ACQUISITION_PAYMENT_UPDATE, PERMISSIONS.SERVICE_PAYMENT_UPDATE, PERMISSIONS.SHIPMENT_PAYMENT_UPDATE],
    [PERMISSIONS.PAYMENT_DELETE_ALL]: [PERMISSIONS.PAYMENT_VIEW_ALL, PERMISSIONS.ORDER_PAYMENT_DELETE, PERMISSIONS.ACQUISITION_PAYMENT_DELETE, PERMISSIONS.SERVICE_PAYMENT_DELETE, PERMISSIONS.SHIPMENT_PAYMENT_DELETE],
    [PERMISSIONS.ACTIVITY_EDIT]: [PERMISSIONS.ACTIVITY_READ],
    [PERMISSIONS.TASK_MANAGE]: [PERMISSIONS.TASK_VIEW],
    [PERMISSIONS.WORK_CASE_MANAGE]: [PERMISSIONS.TASK_VIEW],
    [PERMISSIONS.USER_CREATE]: [PERMISSIONS.USER_VIEW],
    [PERMISSIONS.USER_UPDATE]: [PERMISSIONS.USER_VIEW],
    [PERMISSIONS.USER_DELETE]: [PERMISSIONS.USER_VIEW],
    [PERMISSIONS.USER_MANAGE]: [
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_DELETE,
    ],
};

export function expandPermissions(codes: Iterable<string>) {
    const expanded = new Set(codes);
    const queue = [...expanded];
    while (queue.length) {
        const code = queue.shift()!;
        for (const implied of IMPLICATIONS[code] ?? []) {
            if (expanded.has(implied)) continue;
            expanded.add(implied);
            queue.push(implied);
        }
    }
    return expanded;
}
