import { PERMISSIONS } from "@/constants/permissions";

export const TECHNICIAN_PERMISSIONS = [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.ACTIVITY_READ,
    PERMISSIONS.ACTIVITY_EDIT,

] as const;

export const SALE_PERMISSIONS = [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_PRICE_EDIT,
    PERMISSIONS.ACCESSORY_ACQUISITION_VIEW,
    PERMISSIONS.ACCESSORY_ACQUISITION_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.SHIPMENT_VIEW,
    PERMISSIONS.SHIPMENT_CREATE,
    PERMISSIONS.SHIPMENT_UPDATE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.ACTIVITY_READ,
    PERMISSIONS.ACTIVITY_EDIT,
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
    ADMIN: Object.values(PERMISSIONS),

    STAFF: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.PRODUCT_VIEW,
        PERMISSIONS.ORDER_VIEW,
        PERMISSIONS.ACTIVITY_READ,
        PERMISSIONS.ACTIVITY_EDIT,
    ],

    TECHNICIAN: [...TECHNICIAN_PERMISSIONS],
    SALE: [...SALE_PERMISSIONS],
    SALE_ADMIN: [
        ...SALE_PERMISSIONS,
        PERMISSIONS.PRODUCT_COST_VIEW,
        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_CREATE,
        PERMISSIONS.PAYMENT_UPDATE,
        PERMISSIONS.TASK_VIEW,
    ],
    ACCESSORY_MANAGER: [
        PERMISSIONS.ACCESSORY_VIEW,
        PERMISSIONS.ACCESSORY_CREATE,
        PERMISSIONS.ACCESSORY_UPDATE,
        PERMISSIONS.ACCESSORY_DELETE,
        PERMISSIONS.ACCESSORY_ACQUISITION_VIEW,
        PERMISSIONS.ACCESSORY_ACQUISITION_CREATE,
        PERMISSIONS.ACCESSORY_ACQUISITION_UPDATE,
    ],
};
