import { PERMISSIONS } from "@/constants/permissions";

export const TECHNICIAN_PERMISSIONS = [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,

] as const;

export const SALE_PERMISSIONS = [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_PRICE_EDIT,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.SHIPMENT_VIEW,
    PERMISSIONS.SHIPMENT_CREATE,
    PERMISSIONS.SHIPMENT_UPDATE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
    ADMIN: Object.values(PERMISSIONS),

    STAFF: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.PRODUCT_VIEW,
        PERMISSIONS.ORDER_VIEW,
        PERMISSIONS.INVOICE_VIEW,
    ],

    TECHNICIAN: [...TECHNICIAN_PERMISSIONS],
    SALE: [...SALE_PERMISSIONS],
};
