import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MaintenancePartOrderByWithRelationInputObjectSchema as MaintenancePartOrderByWithRelationInputObjectSchema } from './objects/MaintenancePartOrderByWithRelationInput.schema';
import { MaintenancePartWhereInputObjectSchema as MaintenancePartWhereInputObjectSchema } from './objects/MaintenancePartWhereInput.schema';
import { MaintenancePartWhereUniqueInputObjectSchema as MaintenancePartWhereUniqueInputObjectSchema } from './objects/MaintenancePartWhereUniqueInput.schema';
import { MaintenancePartCountAggregateInputObjectSchema as MaintenancePartCountAggregateInputObjectSchema } from './objects/MaintenancePartCountAggregateInput.schema';
import { MaintenancePartMinAggregateInputObjectSchema as MaintenancePartMinAggregateInputObjectSchema } from './objects/MaintenancePartMinAggregateInput.schema';
import { MaintenancePartMaxAggregateInputObjectSchema as MaintenancePartMaxAggregateInputObjectSchema } from './objects/MaintenancePartMaxAggregateInput.schema';
import { MaintenancePartAvgAggregateInputObjectSchema as MaintenancePartAvgAggregateInputObjectSchema } from './objects/MaintenancePartAvgAggregateInput.schema';
import { MaintenancePartSumAggregateInputObjectSchema as MaintenancePartSumAggregateInputObjectSchema } from './objects/MaintenancePartSumAggregateInput.schema';

export const MaintenancePartAggregateSchema: z.ZodType<Prisma.MaintenancePartAggregateArgs> = z.object({ orderBy: z.union([MaintenancePartOrderByWithRelationInputObjectSchema, MaintenancePartOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenancePartWhereInputObjectSchema.optional(), cursor: MaintenancePartWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenancePartCountAggregateInputObjectSchema ]).optional(), _min: MaintenancePartMinAggregateInputObjectSchema.optional(), _max: MaintenancePartMaxAggregateInputObjectSchema.optional(), _avg: MaintenancePartAvgAggregateInputObjectSchema.optional(), _sum: MaintenancePartSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MaintenancePartAggregateArgs>;

export const MaintenancePartAggregateZodSchema = z.object({ orderBy: z.union([MaintenancePartOrderByWithRelationInputObjectSchema, MaintenancePartOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenancePartWhereInputObjectSchema.optional(), cursor: MaintenancePartWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenancePartCountAggregateInputObjectSchema ]).optional(), _min: MaintenancePartMinAggregateInputObjectSchema.optional(), _max: MaintenancePartMaxAggregateInputObjectSchema.optional(), _avg: MaintenancePartAvgAggregateInputObjectSchema.optional(), _sum: MaintenancePartSumAggregateInputObjectSchema.optional() }).strict();