import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ComplicationOrderByWithRelationInputObjectSchema as ComplicationOrderByWithRelationInputObjectSchema } from './objects/ComplicationOrderByWithRelationInput.schema';
import { ComplicationWhereInputObjectSchema as ComplicationWhereInputObjectSchema } from './objects/ComplicationWhereInput.schema';
import { ComplicationWhereUniqueInputObjectSchema as ComplicationWhereUniqueInputObjectSchema } from './objects/ComplicationWhereUniqueInput.schema';
import { ComplicationCountAggregateInputObjectSchema as ComplicationCountAggregateInputObjectSchema } from './objects/ComplicationCountAggregateInput.schema';
import { ComplicationMinAggregateInputObjectSchema as ComplicationMinAggregateInputObjectSchema } from './objects/ComplicationMinAggregateInput.schema';
import { ComplicationMaxAggregateInputObjectSchema as ComplicationMaxAggregateInputObjectSchema } from './objects/ComplicationMaxAggregateInput.schema';

export const ComplicationAggregateSchema: z.ZodType<Prisma.ComplicationAggregateArgs> = z.object({ orderBy: z.union([ComplicationOrderByWithRelationInputObjectSchema, ComplicationOrderByWithRelationInputObjectSchema.array()]).optional(), where: ComplicationWhereInputObjectSchema.optional(), cursor: ComplicationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ComplicationCountAggregateInputObjectSchema ]).optional(), _min: ComplicationMinAggregateInputObjectSchema.optional(), _max: ComplicationMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ComplicationAggregateArgs>;

export const ComplicationAggregateZodSchema = z.object({ orderBy: z.union([ComplicationOrderByWithRelationInputObjectSchema, ComplicationOrderByWithRelationInputObjectSchema.array()]).optional(), where: ComplicationWhereInputObjectSchema.optional(), cursor: ComplicationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ComplicationCountAggregateInputObjectSchema ]).optional(), _min: ComplicationMinAggregateInputObjectSchema.optional(), _max: ComplicationMaxAggregateInputObjectSchema.optional() }).strict();