// src/constants/catalog.ts
export const DEFAULT_PRICE_BOUNDS = {
    min: 0,
    max: 500_000_000,
};

export const complications = [
    'Chronograph',
    'Date',
    'Day-Date',
    'Month',
    'Annual Calendar',
    'Perpetual Calendar',
    'Moonphase',
    'GMT',
    'World Time',
    'Power Reserve Indicator',
    'Tourbillon',
    'Minute Repeater',
    'Skeleton',
    'Big Date',
    'Retrograde',
    'Alarm',
    'Jump Hour',
    'Regulator',
];


export const brands = [
    {
        name: 'Rolex',
        slug: 'rolex',
        country: 'Switzerland',
        foundedYear: 1905,
        website: 'https://www.rolex.com',
        description: 'Luxury Swiss watch manufacturer.',
    },
    {
        name: 'Omega',
        slug: 'omega',
        country: 'Switzerland',
        foundedYear: 1848,
        website: 'https://www.omegawatches.com',
        description: 'Precision timepieces from Switzerland.',
    },
    {
        name: 'Patek Philippe',
        slug: 'patek-philippe',
        country: 'Switzerland',
        foundedYear: 1839,
        website: 'https://www.patek.com',
        description: 'Haute horlogerie, perpetual calendars, complications.',
    },
    {
        name: 'Audemars Piguet',
        slug: 'audemars-piguet',
        country: 'Switzerland',
        foundedYear: 1875,
        website: 'https://www.audemarspiguet.com',
        description: 'Royal Oak icon and fine watchmaking.',
    },
    {
        name: 'Vacheron Constantin',
        slug: 'vacheron-constantin',
        country: 'Switzerland',
        foundedYear: 1755,
        website: 'https://www.vacheron-constantin.com',
        description: 'One of the oldest Swiss maisons.',
    },
    {
        name: 'Jaeger-LeCoultre',
        slug: 'jaeger-lecoultre',
        country: 'Switzerland',
        foundedYear: 1833,
        website: 'https://www.jaeger-lecoultre.com',
        description: 'Reverso and in-house movements.',
    },
    {
        name: 'IWC',
        slug: 'iwc',
        country: 'Switzerland',
        foundedYear: 1868,
        website: 'https://www.iwc.com',
        description: 'Pilot’s and Portugieser lines.',
    },
    {
        name: 'Cartier',
        slug: 'cartier',
        country: 'France',
        foundedYear: 1847,
        website: 'https://www.cartier.com',
        description: 'Santos, Tank—design icons.',
    },
    {
        name: 'TAG Heuer',
        slug: 'tag-heuer',
        country: 'Switzerland',
        foundedYear: 1860,
        website: 'https://www.tagheuer.com',
        description: 'Motorsport chronographs.',
    },
    {
        name: 'Longines',
        slug: 'longines',
        country: 'Switzerland',
        foundedYear: 1832,
        website: 'https://www.longines.com',
        description: 'Classic Swiss value.',
    },
    {
        name: 'Tissot',
        slug: 'tissot',
        country: 'Switzerland',
        foundedYear: 1853,
        website: 'https://www.tissotwatches.com',
        description: 'Accessible Swiss watches.',
    },
    {
        name: 'Seiko',
        slug: 'seiko',
        country: 'Japan',
        foundedYear: 1881,
        website: 'https://www.seikowatches.com',
        description: 'From 5 Sports to Prospex.',
    },
    {
        name: 'Grand Seiko',
        slug: 'grand-seiko',
        country: 'Japan',
        foundedYear: 1960,
        website: 'https://www.grand-seiko.com',
        description: 'High-end Japanese craftsmanship.',
    },
    {
        name: 'Citizen',
        slug: 'citizen',
        country: 'Japan',
        foundedYear: 1918,
        website: 'https://www.citizenwatch.com',
        description: 'Eco-Drive technology.',
    },
    {
        name: 'Casio',
        slug: 'casio',
        country: 'Japan',
        foundedYear: 1946,
        website: 'https://world.casio.com',
        description: 'G-SHOCK and digital icons.',
    },
    {
        name: 'Tudor',
        slug: 'tudor',
        country: 'Switzerland',
        foundedYear: 1926,
        website: 'https://www.tudorwatch.com',
        description: 'Black Bay divers.',
    },
    {
        name: 'Breitling',
        slug: 'breitling',
        country: 'Switzerland',
        foundedYear: 1884,
        website: 'https://www.breitling.com',
        description: 'Aviation chronographs.',
    },
    {
        name: 'Panerai',
        slug: 'panerai',
        country: 'Italy',
        foundedYear: 1860,
        website: 'https://www.panerai.com',
        description: 'Luminor cushion cases.',
    },
    {
        name: 'Hublot',
        slug: 'hublot',
        country: 'Switzerland',
        foundedYear: 1980,
        website: 'https://www.hublot.com',
        description: 'Fusion materials, bold design.',
    },
    {
        name: 'Breguet',
        slug: 'breguet',
        country: 'Switzerland',
        foundedYear: 1775,
        website: 'https://www.breguet.com',
        description: 'Tourbillon inventor’s maison.',
    },
    {
        name: 'Zenith',
        slug: 'zenith',
        country: 'Switzerland',
        foundedYear: 1865,
        website: 'https://www.zenith-watches.com',
        description: 'El Primero high-beat.',
    },
    {
        name: 'Oris',
        slug: 'oris',
        country: 'Switzerland',
        foundedYear: 1904,
        website: 'https://www.oris.ch',
        description: 'Independent Swiss brand.',
    },
    {
        name: 'Hamilton',
        slug: 'hamilton',
        country: 'Switzerland',
        foundedYear: 1892,
        website: 'https://www.hamiltonwatch.com',
        description: 'American spirit, Swiss precision.',
    },
    {
        name: 'NOMOS Glashütte',
        slug: 'nomos-glashuette',
        country: 'Germany',
        foundedYear: 1990,
        website: 'https://nomos-glashuette.com',
        description: 'Minimal Bauhaus designs.',
    },
    {
        name: 'A. Lange & Söhne',
        slug: 'a-lange-soehne',
        country: 'Germany',
        foundedYear: 1845,
        website: 'https://www.alange-soehne.com',
        description: 'German haute horlogerie.',
    },
    {
        name: 'Richard Mille',
        slug: 'richard-mille',
        country: 'Switzerland',
        foundedYear: 2001,
        website: 'https://www.richardmille.com',
        description: 'Avant-garde, ultralight tech.',
    },
    {
        name: 'Montblanc',
        slug: 'montblanc',
        country: 'Switzerland',
        foundedYear: 1906,
        website: 'https://www.montblanc.com',
        description: 'Minerva chronographs heritage.',
    },
];
