// src/constants/permissions.ts
export const PERMISSIONS = {
    DASHBOARD_VIEW: "DASHBOARD_VIEW",

    /* =====================
     * Acquisition
     * ===================== */
    WATCH_ACQUISITION_VIEW: "WATCH_ACQUISITION_VIEW",
    WATCH_ACQUISITION_CREATE: "WATCH_ACQUISITION_CREATE",
    WATCH_ACQUISITION_UPDATE: "WATCH_ACQUISITION_UPDATE",
    WATCH_ACQUISITION_APPROVE: "WATCH_ACQUISITION_APPROVE",
    WATCH_ACQUISITION_DELETE: "WATCH_ACQUISITION_DELETE",
    ACCESSORY_ACQUISITION_VIEW: "ACCESSORY_ACQUISITION_VIEW",
    ACCESSORY_ACQUISITION_CREATE: "ACCESSORY_ACQUISITION_CREATE",
    ACCESSORY_ACQUISITION_UPDATE: "ACCESSORY_ACQUISITION_UPDATE",
    ACCESSORY_ACQUISITION_APPROVE: "ACCESSORY_ACQUISITION_APPROVE",
    ACCESSORY_ACQUISITION_DELETE: "ACCESSORY_ACQUISITION_DELETE",
    ACQUISITION_VIEW_ALL: "ACQUISITION_VIEW_ALL",
    ACQUISITION_CREATE_ALL: "ACQUISITION_CREATE_ALL",
    ACQUISITION_UPDATE_ALL: "ACQUISITION_UPDATE_ALL",
    ACQUISITION_APPROVE_ALL: "ACQUISITION_APPROVE_ALL",
    ACQUISITION_DELETE_ALL: "ACQUISITION_DELETE_ALL",

    ORDER_VIEW: "ORDER_VIEW",
    ORDER_CREATE: "ORDER_CREATE",
    ORDER_UPDATE: "ORDER_UPDATE",
    ORDER_DELETE: "ORDER_DELETE",
    ORDER_APPROVE: "ORDER_APPROVE",

    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_CREATE: "PRODUCT_CREATE",
    PRODUCT_UPDATE: "PRODUCT_UPDATE",
    PRODUCT_DELETE: "PRODUCT_DELETE",
    PRODUCT_COST_VIEW: "PRODUCT_COST_VIEW",
    PRODUCT_PRICE_EDIT: "PRODUCT_PRICE_EDIT",
    PRODUCT_APPROVE: "PRODUCT_APPROVE",

    ACCESSORY_VIEW: "ACCESSORY_VIEW",
    ACCESSORY_CREATE: "ACCESSORY_CREATE",
    ACCESSORY_UPDATE: "ACCESSORY_UPDATE",
    ACCESSORY_DELETE: "ACCESSORY_DELETE",


    SHIPMENT_VIEW: "SHIPMENT_VIEW",
    SHIPMENT_CREATE: "SHIPMENT_CREATE",
    SHIPMENT_UPDATE: "SHIPMENT_UPDATE",
    SHIPMENT_DELETE: "SHIPMENT_DELETE",
    SHIPMENT_APPROVE: "SHIPMENT_APPROVE",

    MEDIA_VIEW: "MEDIA_VIEW",

    SERVICE_VIEW: "SERVICE_VIEW",
    SERVICE_CREATE: "SERVICE_CREATE",
    SERVICE_UPDATE: "SERVICE_UPDATE",
    SERVICE_DELETE: "SERVICE_DELETE",

    USER_VIEW: "USER_VIEW",
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
    USER_MANAGE: "USER_MANAGE",

    CUSTOMER_VIEW: "CUSTOMER_VIEW",
    CUSTOMER_CREATE: "CUSTOMER_CREATE",
    CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
    CUSTOMER_DELETE: "CUSTOMER_DELETE",

    PAYMENT_VIEW: "PAYMENT_VIEW",
    PAYMENT_CREATE: "PAYMENT_CREATE",
    PAYMENT_UPDATE: "PAYMENT_UPDATE",
    PAYMENT_DELETE: "PAYMENT_DELETE",

    REPORT_VIEW: "REPORT_VIEW",

    SYSTEM_JOB_VIEW: "SYSTEM_JOB_VIEW",

    TASK_VIEW: "TASK_VIEW",
    TASK_MANAGE: "TASK_MANAGE",
    ACTIVITY_READ: "ACTIVITY_READ",
    ACTIVITY_EDIT: "ACTIVITY_EDIT",
    WORK_CASE_MANAGE: "WORK_CASE_MANAGE",

} as const;
