import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MaintenanceRecordOrderByWithRelationInputObjectSchema as MaintenanceRecordOrderByWithRelationInputObjectSchema } from './objects/MaintenanceRecordOrderByWithRelationInput.schema';
import { MaintenanceRecordWhereInputObjectSchema as MaintenanceRecordWhereInputObjectSchema } from './objects/MaintenanceRecordWhereInput.schema';
import { MaintenanceRecordWhereUniqueInputObjectSchema as MaintenanceRecordWhereUniqueInputObjectSchema } from './objects/MaintenanceRecordWhereUniqueInput.schema';
import { MaintenanceRecordCountAggregateInputObjectSchema as MaintenanceRecordCountAggregateInputObjectSchema } from './objects/MaintenanceRecordCountAggregateInput.schema';
import { MaintenanceRecordMinAggregateInputObjectSchema as MaintenanceRecordMinAggregateInputObjectSchema } from './objects/MaintenanceRecordMinAggregateInput.schema';
import { MaintenanceRecordMaxAggregateInputObjectSchema as MaintenanceRecordMaxAggregateInputObjectSchema } from './objects/MaintenanceRecordMaxAggregateInput.schema';
import { MaintenanceRecordAvgAggregateInputObjectSchema as MaintenanceRecordAvgAggregateInputObjectSchema } from './objects/MaintenanceRecordAvgAggregateInput.schema';
import { MaintenanceRecordSumAggregateInputObjectSchema as MaintenanceRecordSumAggregateInputObjectSchema } from './objects/MaintenanceRecordSumAggregateInput.schema';

export const MaintenanceRecordAggregateSchema: z.ZodType<Prisma.MaintenanceRecordAggregateArgs> = z.object({ orderBy: z.union([MaintenanceRecordOrderByWithRelationInputObjectSchema, MaintenanceRecordOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenanceRecordWhereInputObjectSchema.optional(), cursor: MaintenanceRecordWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenanceRecordCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceRecordMinAggregateInputObjectSchema.optional(), _max: MaintenanceRecordMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceRecordAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceRecordSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MaintenanceRecordAggregateArgs>;

export const MaintenanceRecordAggregateZodSchema = z.object({ orderBy: z.union([MaintenanceRecordOrderByWithRelationInputObjectSchema, MaintenanceRecordOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenanceRecordWhereInputObjectSchema.optional(), cursor: MaintenanceRecordWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenanceRecordCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceRecordMinAggregateInputObjectSchema.optional(), _max: MaintenanceRecordMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceRecordAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceRecordSumAggregateInputObjectSchema.optional() }).strict();