import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ServiceCatalogWhereInputObjectSchema as ServiceCatalogWhereInputObjectSchema } from './objects/ServiceCatalogWhereInput.schema';
import { ServiceCatalogOrderByWithAggregationInputObjectSchema as ServiceCatalogOrderByWithAggregationInputObjectSchema } from './objects/ServiceCatalogOrderByWithAggregationInput.schema';
import { ServiceCatalogScalarWhereWithAggregatesInputObjectSchema as ServiceCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/ServiceCatalogScalarWhereWithAggregatesInput.schema';
import { ServiceCatalogScalarFieldEnumSchema } from './enums/ServiceCatalogScalarFieldEnum.schema';
import { ServiceCatalogCountAggregateInputObjectSchema as ServiceCatalogCountAggregateInputObjectSchema } from './objects/ServiceCatalogCountAggregateInput.schema';
import { ServiceCatalogMinAggregateInputObjectSchema as ServiceCatalogMinAggregateInputObjectSchema } from './objects/ServiceCatalogMinAggregateInput.schema';
import { ServiceCatalogMaxAggregateInputObjectSchema as ServiceCatalogMaxAggregateInputObjectSchema } from './objects/ServiceCatalogMaxAggregateInput.schema';
import { ServiceCatalogAvgAggregateInputObjectSchema as ServiceCatalogAvgAggregateInputObjectSchema } from './objects/ServiceCatalogAvgAggregateInput.schema';
import { ServiceCatalogSumAggregateInputObjectSchema as ServiceCatalogSumAggregateInputObjectSchema } from './objects/ServiceCatalogSumAggregateInput.schema';

export const ServiceCatalogGroupBySchema: z.ZodType<Prisma.ServiceCatalogGroupByArgs> = z.object({ where: ServiceCatalogWhereInputObjectSchema.optional(), orderBy: z.union([ServiceCatalogOrderByWithAggregationInputObjectSchema, ServiceCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ServiceCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ServiceCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), ServiceCatalogCountAggregateInputObjectSchema ]).optional(), _min: ServiceCatalogMinAggregateInputObjectSchema.optional(), _max: ServiceCatalogMaxAggregateInputObjectSchema.optional(), _avg: ServiceCatalogAvgAggregateInputObjectSchema.optional(), _sum: ServiceCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ServiceCatalogGroupByArgs>;

export const ServiceCatalogGroupByZodSchema = z.object({ where: ServiceCatalogWhereInputObjectSchema.optional(), orderBy: z.union([ServiceCatalogOrderByWithAggregationInputObjectSchema, ServiceCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ServiceCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ServiceCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), ServiceCatalogCountAggregateInputObjectSchema ]).optional(), _min: ServiceCatalogMinAggregateInputObjectSchema.optional(), _max: ServiceCatalogMaxAggregateInputObjectSchema.optional(), _avg: ServiceCatalogAvgAggregateInputObjectSchema.optional(), _sum: ServiceCatalogSumAggregateInputObjectSchema.optional() }).strict();