import type { WorkflowDefinition } from "./workflow-definition.types";

const PUBLISH_WORKFLOW: WorkflowDefinition = {
  key: "watch-publish",
  title: "Publish Workflow",
  description: "Definition for handling watch publish preparation.",
  initialState: "READY_TO_POST",
  terminalStates: ["DONE"],
  metadata: null,
  states: [
    {
      key: "WAITING_CONTENT",
      title: "Waiting Content",
      description: "Waiting for content to be submitted.",
      color: "gray",
      icon: "clock",
      sortOrder: 10,
    },
    {
      key: "CONTENT_REVIEW",
      title: "Content Review",
      description: "Content is being reviewed.",
      color: "blue",
      icon: "file-text",
      sortOrder: 20,
    },
    {
      key: "CONTENT_FEEDBACK",
      title: "Content Feedback",
      description: "Content needs changes before publishing.",
      color: "red",
      icon: "file-x",
      sortOrder: 25,
    },
    {
      key: "WAITING_IMAGE",
      title: "Waiting Image",
      description: "Waiting for images to be submitted.",
      color: "gray",
      icon: "image",
      sortOrder: 28,
    },
    {
      key: "IMAGE_REVIEW",
      title: "Image Review",
      description: "Images are being reviewed.",
      color: "indigo",
      icon: "image",
      sortOrder: 30,
    },
    {
      key: "IMAGE_FEEDBACK",
      title: "Image Feedback",
      description: "Images need changes before publishing.",
      color: "red",
      icon: "image-off",
      sortOrder: 35,
    },
    {
      key: "READY_TO_POST",
      title: "Ready To Post",
      description: "Publish materials are ready.",
      color: "green",
      icon: "send",
      sortOrder: 40,
    },
    {
      key: "DONE",
      title: "Done",
      description: "Publishing workflow is complete.",
      color: "zinc",
      icon: "check-circle",
      sortOrder: 50,
    },
    {
      key: "RECALLED",
      title: "Recalled",
      description: "Publish was recalled because media needs changes.",
      color: "red",
      icon: "rotate-ccw",
      sortOrder: 60,
    },
  ],
  transitions: [
    {
      fromState: "WAITING_CONTENT",
      toState: "CONTENT_REVIEW",
      triggerType: "EVENT",
      triggerValue: "watch.content.submitted",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "CONTENT_REVIEW",
      toState: "IMAGE_REVIEW",
      triggerType: "EVENT",
      triggerValue: "watch.content.approved",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "IMAGE_REVIEW",
      toState: "READY_TO_POST",
      triggerType: "EVENT",
      triggerValue: "watch.image.approved",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "READY_TO_POST",
      toState: "READY_TO_POST",
      triggerType: "MANUAL",
      triggerValue: "open-target",
      manualActionLabel: "Mở Watch detail",
      condition: null,
      metadata: {
        intent: "OPEN_TARGET",
        presentation: "MODAL",
        targetRoute: "watch.detail",
        targetMode: "publish",
        hrefSource: "queueItem.href",
        expectedEventKey: "watch.publish.assets.downloaded",
      },
    },
    {
      fromState: "READY_TO_POST",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "mark-posted",
      manualActionLabel: "Đã đăng bài",
      condition: null,
      metadata: null,
    },
    {
      fromState: "READY_TO_POST",
      toState: "RECALLED",
      triggerType: "MANUAL",
      triggerValue: "recall-media",
      manualActionLabel: "Thu hồi",
      condition: null,
      metadata: null,
    },
    {
      fromState: "RECALLED",
      toState: "READY_TO_POST",
      triggerType: "EVENT",
      triggerValue: "watch.media.ready_for_publish",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "RECALLED",
      toState: "READY_TO_POST",
      triggerType: "MANUAL",
      triggerValue: "restore-publish",
      manualActionLabel: "Đưa lại đăng bài",
      condition: null,
      metadata: null,
    },
  ],
};

const QUOTATION_WORKFLOW: WorkflowDefinition = {
  key: "sales-quotation",
  title: "Quotation Workflow",
  description: "Definition for handling sales quotation work.",
  initialState: "NEW",
  terminalStates: ["WON", "LOST"],
  metadata: null,
  states: [
    {
      key: "NEW",
      title: "New",
      description: "Quotation request is new.",
      color: "gray",
      icon: "circle",
      sortOrder: 10,
    },
    {
      key: "QUOTED",
      title: "Quoted",
      description: "A quotation has been sent.",
      color: "blue",
      icon: "file-text",
      sortOrder: 20,
    },
    {
      key: "NEGOTIATING",
      title: "Negotiating",
      description: "Commercial terms are being negotiated.",
      color: "amber",
      icon: "messages-square",
      sortOrder: 30,
    },
    {
      key: "WON",
      title: "Won",
      description: "Quotation was accepted.",
      color: "green",
      icon: "check-circle",
      sortOrder: 40,
    },
    {
      key: "LOST",
      title: "Lost",
      description: "Quotation was declined.",
      color: "red",
      icon: "x-circle",
      sortOrder: 50,
    },
  ],
  transitions: [
    {
      fromState: "NEW",
      toState: "QUOTED",
      triggerType: "MANUAL",
      triggerValue: "send-quotation",
      manualActionLabel: "Đã báo giá",
      condition: null,
      metadata: null,
    },
    {
      fromState: "QUOTED",
      toState: "NEGOTIATING",
      triggerType: "MANUAL",
      triggerValue: "start-negotiation",
      manualActionLabel: "Đang thương lượng",
      condition: null,
      metadata: null,
    },
    {
      fromState: "NEGOTIATING",
      toState: "WON",
      triggerType: "MANUAL",
      triggerValue: "mark-won",
      manualActionLabel: "Khách đồng ý",
      condition: null,
      metadata: null,
    },
    {
      fromState: "NEGOTIATING",
      toState: "LOST",
      triggerType: "MANUAL",
      triggerValue: "mark-lost",
      manualActionLabel: "Khách từ chối",
      condition: null,
      metadata: null,
    },
  ],
};

const REPAIR_WORKFLOW: WorkflowDefinition = {
  key: "technical-repair",
  title: "Repair Workflow",
  description: "Definition for handling technical repair work.",
  initialState: "NEW",
  terminalStates: ["DELIVERED"],
  metadata: null,
  states: [
    {
      key: "NEW",
      title: "New",
      description: "Repair request is new.",
      color: "gray",
      icon: "circle",
      sortOrder: 10,
    },
    {
      key: "INSPECTING",
      title: "Inspecting",
      description: "Item is being inspected.",
      color: "blue",
      icon: "search",
      sortOrder: 20,
    },
    {
      key: "REPAIRING",
      title: "Repairing",
      description: "Repair work is in progress.",
      color: "amber",
      icon: "wrench",
      sortOrder: 30,
    },
    {
      key: "READY",
      title: "Ready",
      description: "Item is ready for delivery.",
      color: "green",
      icon: "package-check",
      sortOrder: 40,
    },
    {
      key: "DELIVERED",
      title: "Delivered",
      description: "Item has been delivered.",
      color: "zinc",
      icon: "check-circle",
      sortOrder: 50,
    },
  ],
  transitions: [
    {
      fromState: "NEW",
      toState: "INSPECTING",
      triggerType: "MANUAL",
      triggerValue: "start-inspection",
      manualActionLabel: "Kiểm tra",
      condition: null,
      metadata: null,
    },
    {
      fromState: "INSPECTING",
      toState: "REPAIRING",
      triggerType: "MANUAL",
      triggerValue: "start-repair",
      manualActionLabel: "Đang sửa",
      condition: null,
      metadata: null,
    },
    {
      fromState: "REPAIRING",
      toState: "READY",
      triggerType: "MANUAL",
      triggerValue: "mark-ready",
      manualActionLabel: "Hoàn tất sửa",
      condition: null,
      metadata: null,
    },
    {
      fromState: "READY",
      toState: "DELIVERED",
      triggerType: "MANUAL",
      triggerValue: "mark-delivered",
      manualActionLabel: "Đã bàn giao",
      condition: null,
      metadata: null,
    },
  ],
};

const GENERAL_WORKFLOW: WorkflowDefinition = {
  key: "general",
  title: "General Workflow",
  description: "Lightweight definition for general coordination work.",
  initialState: "NEW",
  terminalStates: ["DONE"],
  metadata: null,
  states: [
    {
      key: "NEW",
      title: "New",
      description: "General work is newly created.",
      color: "gray",
      icon: "circle",
      sortOrder: 10,
    },
    {
      key: "IN_PROGRESS",
      title: "In Progress",
      description: "General work is being handled.",
      color: "blue",
      icon: "loader",
      sortOrder: 20,
    },
    {
      key: "DONE",
      title: "Done",
      description: "General work is complete.",
      color: "zinc",
      icon: "check-circle",
      sortOrder: 30,
    },
  ],
  transitions: [
    {
      fromState: "NEW",
      toState: "IN_PROGRESS",
      triggerType: "MANUAL",
      triggerValue: "start-work",
      manualActionLabel: "Bắt đầu xử lý",
      condition: null,
      metadata: null,
    },
    {
      fromState: "IN_PROGRESS",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "mark-done",
      manualActionLabel: "Hoàn tất",
      condition: null,
      metadata: null,
    },
  ],
};

const WATCH_MEDIA_PROCESSING_WORKFLOW: WorkflowDefinition = {
  key: "watch-media-processing",
  title: "Media Processing Workflow",
  description: "Definition for handling Watch media attachment and review.",
  initialState: "NEW",
  terminalStates: ["DONE"],
  metadata: null,
  states: [
    {
      key: "NEW",
      title: "New",
      description: "Watch has entered media processing.",
      color: "gray",
      icon: "circle",
      sortOrder: 10,
    },
    {
      key: "REVIEW",
      title: "Review",
      description: "Media is attached and waiting for review.",
      color: "blue",
      icon: "images",
      sortOrder: 20,
    },
    {
      key: "RETURNED",
      title: "Returned",
      description: "Media was returned to Photoshoot and needs new images before approval.",
      color: "red",
      icon: "message-square-warning",
      sortOrder: 30,
    },
    {
      key: "DONE",
      title: "Done",
      description: "Media processing is approved.",
      color: "zinc",
      icon: "check-circle",
      sortOrder: 40,
    },
  ],
  transitions: [
    {
      fromState: "NEW",
      toState: "REVIEW",
      triggerType: "EVENT",
      triggerValue: "watch.media.asset.attached",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "NEW",
      toState: "NEW",
      triggerType: "MANUAL",
      triggerValue: "open-watch-media",
      manualActionLabel: "Gắn media",
      condition: null,
      metadata: {
        intent: "OPEN_TARGET",
        presentation: "MODAL",
        targetRoute: "watch.edit",
        targetMode: "media",
        focus: "media",
        from: "media-workspace",
        expectedEventKey: "watch.media.asset.attached",
      },
    },
    {
      fromState: "RETURNED",
      toState: "REVIEW",
      triggerType: "EVENT",
      triggerValue: "watch.media.asset.attached",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "RETURNED",
      toState: "RETURNED",
      triggerType: "MANUAL",
      triggerValue: "open-watch-media",
      manualActionLabel: "Cập nhật media",
      condition: null,
      metadata: {
        intent: "OPEN_TARGET",
        presentation: "MODAL",
        targetRoute: "watch.edit",
        targetMode: "media",
        focus: "media",
        from: "media-workspace",
        expectedEventKey: "watch.media.asset.attached",
      },
    },
    {
      fromState: "REVIEW",
      toState: "RETURNED",
      triggerType: "MANUAL",
      triggerValue: "request-changes",
      manualActionLabel: "Trả về",
      condition: null,
      metadata: null,
    },
    {
      fromState: "NEW",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "approve-media",
      manualActionLabel: "Duyệt xong",
      condition: null,
      metadata: null,
    },
    {
      fromState: "REVIEW",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "approve-media",
      manualActionLabel: "Duyệt xong",
      condition: null,
      metadata: null,
    },
    {
      fromState: "DONE",
      toState: "RETURNED",
      triggerType: "EVENT",
      triggerValue: "watch.media.recalled",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "DONE",
      toState: "RETURNED",
      triggerType: "EVENT",
      triggerValue: "watch.content.unapproved",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "DONE",
      toState: "RETURNED",
      triggerType: "EVENT",
      triggerValue: "watch.image.unapproved",
      manualActionLabel: null,
      condition: null,
      metadata: null,
    },
    {
      fromState: "DONE",
      toState: "RETURNED",
      triggerType: "MANUAL",
      triggerValue: "reopen-media",
      manualActionLabel: "Mở lại xử lý",
      condition: null,
      metadata: null,
    },
  ],
};

const SERVICE_OPERATION_TECHNICAL_BENCH_WORKFLOW: WorkflowDefinition = {
  key: "service-operation-technical-bench",
  title: "Service Operation Technical Bench",
  description:
    "Definition for TechnicalIssue stage movement inside Service Operation workspaces.",
  initialState: "INSPECT",
  terminalStates: ["DONE"],
  metadata: {
    domain: "service",
    itemType: "TechnicalIssue",
    scope: "workspace-item",
  },
  states: [
    {
      key: "INSPECT",
      title: "Inspect",
      description: "Technical issue is waiting for inspection or confirmation.",
      color: "amber",
      icon: "search",
      sortOrder: 10,
    },
    {
      key: "READY",
      title: "Ready",
      description: "Technical issue is confirmed and ready for bench work.",
      color: "blue",
      icon: "clipboard-check",
      sortOrder: 20,
    },
    {
      key: "IN_PROGRESS",
      title: "In Progress",
      description: "Technical work is currently in progress.",
      color: "indigo",
      icon: "wrench",
      sortOrder: 30,
    },
    {
      key: "DONE",
      title: "Done",
      description: "Technical issue work is complete.",
      color: "zinc",
      icon: "check-circle",
      sortOrder: 40,
    },
  ],
  transitions: [
    {
      fromState: "INSPECT",
      toState: "READY",
      triggerType: "MANUAL",
      triggerValue: "confirm-issue",
      manualActionLabel: "Confirm issue",
      condition: null,
      metadata: {
        serviceOperationAction: "CONFIRM_TECHNICAL_ISSUE",
      },
    },
    {
      fromState: "INSPECT",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "close-no-issue",
      manualActionLabel: "Không có vấn đề",
      condition: null,
      metadata: {
        serviceOperationAction: "CLOSE_TECHNICAL_ISSUE_NO_ISSUE",
      },
    },
    {
      fromState: "READY",
      toState: "IN_PROGRESS",
      triggerType: "MANUAL",
      triggerValue: "start-work",
      manualActionLabel: "Start work",
      condition: null,
      metadata: {
        serviceOperationAction: "START_TECHNICAL_WORK",
      },
    },
    {
      fromState: "IN_PROGRESS",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "mark-done",
      manualActionLabel: "Mark done",
      condition: null,
      metadata: {
        serviceOperationAction: "COMPLETE_TECHNICAL_ISSUE",
      },
    },
    {
      fromState: "IN_PROGRESS",
      toState: "DONE",
      triggerType: "MANUAL",
      triggerValue: "cancel-work",
      manualActionLabel: "Hủy xử lý",
      condition: null,
      metadata: {
        serviceOperationAction: "CANCEL_TECHNICAL_ISSUE",
      },
    },
    {
      fromState: "READY",
      toState: "INSPECT",
      triggerType: "MANUAL",
      triggerValue: "send-back-to-inspect",
      manualActionLabel: "Send back to inspect",
      condition: null,
      metadata: null,
    },
    {
      fromState: "IN_PROGRESS",
      toState: "READY",
      triggerType: "MANUAL",
      triggerValue: "pause-or-return",
      manualActionLabel: "Return to ready",
      condition: null,
      metadata: null,
    },
    {
      fromState: "DONE",
      toState: "IN_PROGRESS",
      triggerType: "MANUAL",
      triggerValue: "reopen-work",
      manualActionLabel: "Reopen work",
      condition: null,
      metadata: null,
    },
    {
      fromState: "INSPECT",
      toState: "INSPECT",
      triggerType: "EVENT",
      triggerValue: "technical_issue.created",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
    {
      fromState: "INSPECT",
      toState: "READY",
      triggerType: "EVENT",
      triggerValue: "technical_issue.confirmed",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
    {
      fromState: "INSPECT",
      toState: "DONE",
      triggerType: "EVENT",
      triggerValue: "technical_issue.completed",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
    {
      fromState: "READY",
      toState: "IN_PROGRESS",
      triggerType: "EVENT",
      triggerValue: "technical_issue.started",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
    {
      fromState: "IN_PROGRESS",
      toState: "DONE",
      triggerType: "EVENT",
      triggerValue: "technical_issue.completed",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
    {
      fromState: "DONE",
      toState: "IN_PROGRESS",
      triggerType: "EVENT",
      triggerValue: "technical_issue.reopened",
      manualActionLabel: null,
      condition: null,
      metadata: {
        contractOnly: true,
      },
    },
  ],
};

function createSimpleWorkflowDefinition(input: {
  key: string;
  title: string;
  description: string;
  activeTitle?: string;
  activeIcon?: string;
}): WorkflowDefinition {
  return {
    key: input.key,
    title: input.title,
    description: input.description,
    initialState: "NEW",
    terminalStates: ["DONE"],
    metadata: null,
    states: [
      {
        key: "NEW",
        title: "New",
        description: "Work has been created.",
        color: "gray",
        icon: "circle",
        sortOrder: 10,
      },
      {
        key: "IN_PROGRESS",
        title: input.activeTitle ?? "In Progress",
        description: "Work is being handled.",
        color: "blue",
        icon: input.activeIcon ?? "loader",
        sortOrder: 20,
      },
      {
        key: "DONE",
        title: "Done",
        description: "Work is complete.",
        color: "zinc",
        icon: "check-circle",
        sortOrder: 30,
      },
    ],
    transitions: [
      {
        fromState: "NEW",
        toState: "IN_PROGRESS",
        triggerType: "MANUAL",
        triggerValue: "start-work",
        manualActionLabel: "Bắt đầu xử lý",
        condition: null,
        metadata: null,
      },
      {
        fromState: "IN_PROGRESS",
        toState: "DONE",
        triggerType: "MANUAL",
        triggerValue: "mark-done",
        manualActionLabel: "Hoàn tất",
        condition: null,
        metadata: null,
      },
    ],
  };
}

const WORKFLOW_DEFINITIONS: WorkflowDefinition[] = [
  PUBLISH_WORKFLOW,
  createSimpleWorkflowDefinition({
    key: "watch-content-review",
    title: "Content Review Workflow",
    description: "Lightweight definition for content review work.",
    activeTitle: "Reviewing",
    activeIcon: "file-text",
  }),
  WATCH_MEDIA_PROCESSING_WORKFLOW,
  SERVICE_OPERATION_TECHNICAL_BENCH_WORKFLOW,
  createSimpleWorkflowDefinition({
    key: "watch-image-review",
    title: "Image Review Workflow",
    description: "Lightweight definition for image review work.",
    activeTitle: "Reviewing",
    activeIcon: "image",
  }),
  createSimpleWorkflowDefinition({
    key: "watch-photography",
    title: "Photography Workflow",
    description: "Lightweight definition for photography work.",
    activeTitle: "Shooting",
    activeIcon: "camera",
  }),
  createSimpleWorkflowDefinition({
    key: "watch-operation-technical",
    title: "Operation Technical Workflow",
    description: "Lightweight definition for operation technical work.",
    activeTitle: "Handling",
    activeIcon: "wrench",
  }),
  QUOTATION_WORKFLOW,
  createSimpleWorkflowDefinition({
    key: "sales-pricing",
    title: "Pricing Workflow",
    description: "Lightweight definition for pricing work.",
    activeTitle: "Pricing",
    activeIcon: "tag",
  }),
  createSimpleWorkflowDefinition({
    key: "sales-negotiation",
    title: "Negotiation Workflow",
    description: "Lightweight definition for negotiation work.",
    activeTitle: "Negotiating",
    activeIcon: "messages-square",
  }),
  createSimpleWorkflowDefinition({
    key: "sales-marketing",
    title: "Marketing Workflow",
    description: "Lightweight definition for marketing work.",
    activeTitle: "Marketing",
    activeIcon: "megaphone",
  }),
  REPAIR_WORKFLOW,
  createSimpleWorkflowDefinition({
    key: "technical-inspection",
    title: "Inspection Workflow",
    description: "Lightweight definition for technical inspection work.",
    activeTitle: "Inspecting",
    activeIcon: "search",
  }),
  createSimpleWorkflowDefinition({
    key: "technical-warranty",
    title: "Warranty Workflow",
    description: "Lightweight definition for warranty work.",
    activeTitle: "Handling Warranty",
    activeIcon: "shield-check",
  }),
  GENERAL_WORKFLOW,
];

export function listRegisteredWorkflowDefinitions() {
  return [...WORKFLOW_DEFINITIONS];
}
