"use client";
import Link from "next/link";
import { useState } from "react";

export default function CatalogManager({ items: initial }: { items: any[] }) {
  const [items,setItems]=useState<any[]>(initial||[]);
  const [form,setForm]=useState<any>({code:"",name:"",categoryKey:"OTHER",vendorPrice:"",customerPrice:"",internalCost:"0",note:"",isActive:true});
  async function save(item?: any){
    const body={...form, vendorPrice: form.vendorPrice===""?null:Number(form.vendorPrice), customerPrice: form.customerPrice===""?null:Number(form.customerPrice), internalCost: form.internalCost===""?0:Number(form.internalCost)};
    const res=await fetch('/api/admin/service-catalog',{method:item?'PATCH':'POST',headers:{'Content-Type':'application/json'},body: JSON.stringify(item?{id:item.id,...body}:body)});
    const data=await res.json(); if(!res.ok) throw new Error(data.error||'Save failed');
    location.reload();
  }
  return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold">Danh mục service</h1><Link href="/admin/services" className="rounded border px-3 py-2">← Service Requests</Link></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{['BATTERY','OVERHAUL','SPA','DIAL','PARTS','OTHER'].map(k=><button key={k} type="button" onClick={()=>setForm((p:any)=>({...p,categoryKey:k}))} className={`rounded border px-3 py-2 text-sm ${form.categoryKey===k?'bg-black text-white':''}`}>{k}</button>)}</div><div className="rounded border bg-white p-4 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4"><input className="rounded border px-3 py-2" placeholder="Code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input className="rounded border px-3 py-2" placeholder="Tên hạng mục" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="rounded border px-3 py-2" placeholder="Giá vendor ngoài" value={form.vendorPrice} onChange={e=>setForm({...form,vendorPrice:e.target.value})}/><input className="rounded border px-3 py-2" placeholder="Giá thu khách" value={form.customerPrice} onChange={e=>setForm({...form,customerPrice:e.target.value})}/><input className="rounded border px-3 py-2" placeholder="Giá kỹ thuật nội bộ" value={form.internalCost} onChange={e=>setForm({...form,internalCost:e.target.value})}/><input className="rounded border px-3 py-2 md:col-span-2" placeholder="Note" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><label className="flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Hoạt động</label><div><button className="rounded bg-black px-4 py-2 text-white" onClick={()=>save()}>Lưu hạng mục</button></div></div><div className="overflow-x-auto rounded border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="px-3 py-2 text-left">Code</th><th className="px-3 py-2 text-left">Tên</th><th className="px-3 py-2 text-left">Nhóm</th><th className="px-3 py-2 text-right">Vendor</th><th className="px-3 py-2 text-right">Khách</th><th className="px-3 py-2 text-right">Nội bộ</th><th className="px-3 py-2 text-left">Note</th></tr></thead><tbody>{items.map((it:any)=><tr key={it.id} className="border-t"><td className="px-3 py-2">{it.code}</td><td className="px-3 py-2">{it.name}</td><td className="px-3 py-2">{it.categoryKey||'OTHER'}</td><td className="px-3 py-2 text-right">{it.vendorPrice??'-'}</td><td className="px-3 py-2 text-right">{it.customerPrice??it.defaultPrice??'-'}</td><td className="px-3 py-2 text-right">{it.internalCost??0}</td><td className="px-3 py-2">{it.note??'-'}</td></tr>)}</tbody></table></div></div>
}
