import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../globals.css";
import BootstrapClient from "../BootstrapClient";
import CartDrawer from "@/features/cart/component/cart-drawer";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";

import { Playfair_Display } from 'next/font/google';
import ClientProviders from "@/app/providers";
const playfair = Playfair_Display({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
});
import { Merriweather } from 'next/font/google';

const merriweather = Merriweather({
    subsets: ['latin'],
    weight: ['400', '700'],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} bg-white`}>
                <ClientProviders>
                    <Header />
                    {children}
                    <Footer />
                    <CartDrawer />
                </ClientProviders>
                <BootstrapClient />   {/* load bootstrap JS chỉ ở client */}
            </body>
        </html>
    );
}
