import { defineBusinessEventContract } from "@/domains/event/contract/business-event-contract.helpers";
import type { BusinessEventContract } from "@/domains/event/contract/business-event-contract.types";

export const LEGACY_BUSINESS_EVENT_CONTRACTS: BusinessEventContract[] = [
  defineBusinessEventContract({
    key: "watch.service.eta.updated",
    label: "Watch service ETA updated",
    targetType: "WATCH",
    group: "Watch",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "technical_issue.updated",
    label: "Technical issue updated",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["timeline"],
  }),
  defineBusinessEventContract({
    key: "acquisition.created",
    label: "Acquisition created",
    targetType: "ACQUISITION",
    group: "Acquisition",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "acquisition.updated",
    label: "Acquisition updated",
    targetType: "ACQUISITION",
    group: "Acquisition",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "acquisition.items.updated",
    label: "Acquisition items updated",
    targetType: "ACQUISITION",
    group: "Acquisition",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "acquisition.posted",
    label: "Acquisition posted",
    targetType: "ACQUISITION",
    group: "Acquisition",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "acquisition.canceled",
    label: "Acquisition canceled",
    targetType: "ACQUISITION",
    group: "Acquisition",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "order.posted",
    label: "Order posted",
    targetType: "ORDER",
    group: "Order",
  }),
  defineBusinessEventContract({
    key: "order.paid",
    label: "Order paid",
    targetType: "ORDER",
    group: "Order",
  }),
  defineBusinessEventContract({
    key: "order.completed",
    label: "Order completed",
    targetType: "ORDER",
    group: "Order",
  }),
  defineBusinessEventContract({
    key: "shipment.delivered",
    label: "Shipment delivered",
    targetType: "SHIPMENT",
    group: "Shipment",
  }),
  defineBusinessEventContract({
    key: "shipment.returned",
    label: "Shipment returned",
    targetType: "SHIPMENT",
    group: "Shipment",
  }),
  defineBusinessEventContract({
    key: "payment.paid",
    label: "Payment paid",
    targetType: "PAYMENT",
    group: "Payment",
    knownConsumers: ["timeline", "coordination", "projection"],
  }),
  defineBusinessEventContract({
    key: "payment.created",
    label: "Payment created",
    targetType: "PAYMENT",
    group: "Payment",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "payment.status_updated",
    label: "Payment status updated",
    targetType: "PAYMENT",
    group: "Payment",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "payment.exception_marked",
    label: "Payment exception marked",
    targetType: "PAYMENT",
    group: "Payment",
    knownConsumers: ["timeline", "coordination", "projection"],
  }),
  defineBusinessEventContract({
    key: "service_request.created",
    label: "Service request created",
    targetType: "SERVICE_REQUEST",
    group: "Service",
    knownConsumers: ["timeline", "coordination", "projection"],
    autoBindingScope: "CURRENT_ACTIVE_WEEKLY_SPACE:TECHNICAL:service-operation",
  }),
  defineBusinessEventContract({
    key: "service_request.status_changed",
    label: "Service request status changed",
    targetType: "SERVICE_REQUEST",
    group: "Service",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "service_request.completed",
    label: "Service request completed",
    targetType: "SERVICE_REQUEST",
    group: "Service",
  }),
  defineBusinessEventContract({
    key: "technical_issue.created",
    label: "Technical issue created",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["notification", "timeline", "coordination", "projection"],
    autoBindingScope: "CURRENT_ACTIVE_WEEKLY_SPACE:TECHNICAL:service-operation",
  }),
  defineBusinessEventContract({
    key: "technical_issue.confirmed",
    label: "Technical issue confirmed",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["timeline", "coordination", "projection"],
  }),
  defineBusinessEventContract({
    key: "technical_issue.started",
    label: "Technical issue started",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["timeline", "coordination", "projection"],
  }),
  defineBusinessEventContract({
    key: "technical_issue.completed",
    label: "Technical issue completed",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["timeline", "coordination", "projection"],
  }),
  defineBusinessEventContract({
    key: "technical_issue.reopened",
    label: "Technical issue reopened",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
    knownConsumers: ["timeline", "projection"],
  }),
  defineBusinessEventContract({
    key: "technical_issue.done",
    label: "Technical issue done",
    targetType: "TECHNICAL_ISSUE",
    group: "Service",
  }),
  defineBusinessEventContract({
    key: "task.item.created",
    label: "Task item created",
    targetType: "TASK_ITEM",
    group: "Task",
  }),
  defineBusinessEventContract({
    key: "task.item.moved",
    label: "Task item moved",
    targetType: "TASK_ITEM",
    group: "Task",
  }),
  defineBusinessEventContract({
    key: "task.item.activity.commented",
    label: "Task activity commented",
    targetType: "TASK_ITEM",
    group: "Task",
    knownConsumers: ["notification", "timeline"],
  }),
];
