import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowConditionOrderByWithRelationInputObjectSchema as WorkflowConditionOrderByWithRelationInputObjectSchema } from './objects/WorkflowConditionOrderByWithRelationInput.schema';
import { WorkflowConditionWhereInputObjectSchema as WorkflowConditionWhereInputObjectSchema } from './objects/WorkflowConditionWhereInput.schema';
import { WorkflowConditionWhereUniqueInputObjectSchema as WorkflowConditionWhereUniqueInputObjectSchema } from './objects/WorkflowConditionWhereUniqueInput.schema';
import { WorkflowConditionCountAggregateInputObjectSchema as WorkflowConditionCountAggregateInputObjectSchema } from './objects/WorkflowConditionCountAggregateInput.schema';
import { WorkflowConditionMinAggregateInputObjectSchema as WorkflowConditionMinAggregateInputObjectSchema } from './objects/WorkflowConditionMinAggregateInput.schema';
import { WorkflowConditionMaxAggregateInputObjectSchema as WorkflowConditionMaxAggregateInputObjectSchema } from './objects/WorkflowConditionMaxAggregateInput.schema';
import { WorkflowConditionAvgAggregateInputObjectSchema as WorkflowConditionAvgAggregateInputObjectSchema } from './objects/WorkflowConditionAvgAggregateInput.schema';
import { WorkflowConditionSumAggregateInputObjectSchema as WorkflowConditionSumAggregateInputObjectSchema } from './objects/WorkflowConditionSumAggregateInput.schema';

export const WorkflowConditionAggregateSchema: z.ZodType<Prisma.WorkflowConditionAggregateArgs> = z.object({ orderBy: z.union([WorkflowConditionOrderByWithRelationInputObjectSchema, WorkflowConditionOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkflowConditionWhereInputObjectSchema.optional(), cursor: WorkflowConditionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkflowConditionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowConditionMinAggregateInputObjectSchema.optional(), _max: WorkflowConditionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowConditionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowConditionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowConditionAggregateArgs>;

export const WorkflowConditionAggregateZodSchema = z.object({ orderBy: z.union([WorkflowConditionOrderByWithRelationInputObjectSchema, WorkflowConditionOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkflowConditionWhereInputObjectSchema.optional(), cursor: WorkflowConditionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkflowConditionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowConditionMinAggregateInputObjectSchema.optional(), _max: WorkflowConditionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowConditionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowConditionSumAggregateInputObjectSchema.optional() }).strict();