import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TechnicalDetailCatalogOrderByWithRelationInputObjectSchema as TechnicalDetailCatalogOrderByWithRelationInputObjectSchema } from './objects/TechnicalDetailCatalogOrderByWithRelationInput.schema';
import { TechnicalDetailCatalogWhereInputObjectSchema as TechnicalDetailCatalogWhereInputObjectSchema } from './objects/TechnicalDetailCatalogWhereInput.schema';
import { TechnicalDetailCatalogWhereUniqueInputObjectSchema as TechnicalDetailCatalogWhereUniqueInputObjectSchema } from './objects/TechnicalDetailCatalogWhereUniqueInput.schema';
import { TechnicalDetailCatalogCountAggregateInputObjectSchema as TechnicalDetailCatalogCountAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogCountAggregateInput.schema';
import { TechnicalDetailCatalogMinAggregateInputObjectSchema as TechnicalDetailCatalogMinAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogMinAggregateInput.schema';
import { TechnicalDetailCatalogMaxAggregateInputObjectSchema as TechnicalDetailCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogMaxAggregateInput.schema';
import { TechnicalDetailCatalogAvgAggregateInputObjectSchema as TechnicalDetailCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogAvgAggregateInput.schema';
import { TechnicalDetailCatalogSumAggregateInputObjectSchema as TechnicalDetailCatalogSumAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogSumAggregateInput.schema';

export const TechnicalDetailCatalogAggregateSchema: z.ZodType<Prisma.TechnicalDetailCatalogAggregateArgs> = z.object({ orderBy: z.union([TechnicalDetailCatalogOrderByWithRelationInputObjectSchema, TechnicalDetailCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: TechnicalDetailCatalogWhereInputObjectSchema.optional(), cursor: TechnicalDetailCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalDetailCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalDetailCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalDetailCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalDetailCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalDetailCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TechnicalDetailCatalogAggregateArgs>;

export const TechnicalDetailCatalogAggregateZodSchema = z.object({ orderBy: z.union([TechnicalDetailCatalogOrderByWithRelationInputObjectSchema, TechnicalDetailCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: TechnicalDetailCatalogWhereInputObjectSchema.optional(), cursor: TechnicalDetailCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalDetailCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalDetailCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalDetailCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalDetailCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalDetailCatalogSumAggregateInputObjectSchema.optional() }).strict();