import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StrapCatalogOptionOrderByWithRelationInputObjectSchema as StrapCatalogOptionOrderByWithRelationInputObjectSchema } from './objects/StrapCatalogOptionOrderByWithRelationInput.schema';
import { StrapCatalogOptionWhereInputObjectSchema as StrapCatalogOptionWhereInputObjectSchema } from './objects/StrapCatalogOptionWhereInput.schema';
import { StrapCatalogOptionWhereUniqueInputObjectSchema as StrapCatalogOptionWhereUniqueInputObjectSchema } from './objects/StrapCatalogOptionWhereUniqueInput.schema';
import { StrapCatalogOptionCountAggregateInputObjectSchema as StrapCatalogOptionCountAggregateInputObjectSchema } from './objects/StrapCatalogOptionCountAggregateInput.schema';
import { StrapCatalogOptionMinAggregateInputObjectSchema as StrapCatalogOptionMinAggregateInputObjectSchema } from './objects/StrapCatalogOptionMinAggregateInput.schema';
import { StrapCatalogOptionMaxAggregateInputObjectSchema as StrapCatalogOptionMaxAggregateInputObjectSchema } from './objects/StrapCatalogOptionMaxAggregateInput.schema';
import { StrapCatalogOptionAvgAggregateInputObjectSchema as StrapCatalogOptionAvgAggregateInputObjectSchema } from './objects/StrapCatalogOptionAvgAggregateInput.schema';
import { StrapCatalogOptionSumAggregateInputObjectSchema as StrapCatalogOptionSumAggregateInputObjectSchema } from './objects/StrapCatalogOptionSumAggregateInput.schema';

export const StrapCatalogOptionAggregateSchema: z.ZodType<Prisma.StrapCatalogOptionAggregateArgs> = z.object({ orderBy: z.union([StrapCatalogOptionOrderByWithRelationInputObjectSchema, StrapCatalogOptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: StrapCatalogOptionWhereInputObjectSchema.optional(), cursor: StrapCatalogOptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StrapCatalogOptionCountAggregateInputObjectSchema ]).optional(), _min: StrapCatalogOptionMinAggregateInputObjectSchema.optional(), _max: StrapCatalogOptionMaxAggregateInputObjectSchema.optional(), _avg: StrapCatalogOptionAvgAggregateInputObjectSchema.optional(), _sum: StrapCatalogOptionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StrapCatalogOptionAggregateArgs>;

export const StrapCatalogOptionAggregateZodSchema = z.object({ orderBy: z.union([StrapCatalogOptionOrderByWithRelationInputObjectSchema, StrapCatalogOptionOrderByWithRelationInputObjectSchema.array()]).optional(), where: StrapCatalogOptionWhereInputObjectSchema.optional(), cursor: StrapCatalogOptionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StrapCatalogOptionCountAggregateInputObjectSchema ]).optional(), _min: StrapCatalogOptionMinAggregateInputObjectSchema.optional(), _max: StrapCatalogOptionMaxAggregateInputObjectSchema.optional(), _avg: StrapCatalogOptionAvgAggregateInputObjectSchema.optional(), _sum: StrapCatalogOptionSumAggregateInputObjectSchema.optional() }).strict();