import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { IntegrationIngressReceiptOrderByWithRelationInputObjectSchema as IntegrationIngressReceiptOrderByWithRelationInputObjectSchema } from './objects/IntegrationIngressReceiptOrderByWithRelationInput.schema';
import { IntegrationIngressReceiptWhereInputObjectSchema as IntegrationIngressReceiptWhereInputObjectSchema } from './objects/IntegrationIngressReceiptWhereInput.schema';
import { IntegrationIngressReceiptWhereUniqueInputObjectSchema as IntegrationIngressReceiptWhereUniqueInputObjectSchema } from './objects/IntegrationIngressReceiptWhereUniqueInput.schema';
import { IntegrationIngressReceiptCountAggregateInputObjectSchema as IntegrationIngressReceiptCountAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptCountAggregateInput.schema';
import { IntegrationIngressReceiptMinAggregateInputObjectSchema as IntegrationIngressReceiptMinAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptMinAggregateInput.schema';
import { IntegrationIngressReceiptMaxAggregateInputObjectSchema as IntegrationIngressReceiptMaxAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptMaxAggregateInput.schema';

export const IntegrationIngressReceiptAggregateSchema: z.ZodType<Prisma.IntegrationIngressReceiptAggregateArgs> = z.object({ orderBy: z.union([IntegrationIngressReceiptOrderByWithRelationInputObjectSchema, IntegrationIngressReceiptOrderByWithRelationInputObjectSchema.array()]).optional(), where: IntegrationIngressReceiptWhereInputObjectSchema.optional(), cursor: IntegrationIngressReceiptWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), IntegrationIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: IntegrationIngressReceiptMinAggregateInputObjectSchema.optional(), _max: IntegrationIngressReceiptMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.IntegrationIngressReceiptAggregateArgs>;

export const IntegrationIngressReceiptAggregateZodSchema = z.object({ orderBy: z.union([IntegrationIngressReceiptOrderByWithRelationInputObjectSchema, IntegrationIngressReceiptOrderByWithRelationInputObjectSchema.array()]).optional(), where: IntegrationIngressReceiptWhereInputObjectSchema.optional(), cursor: IntegrationIngressReceiptWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), IntegrationIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: IntegrationIngressReceiptMinAggregateInputObjectSchema.optional(), _max: IntegrationIngressReceiptMaxAggregateInputObjectSchema.optional() }).strict();