import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema as AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema } from './objects/AcquisitionSpecJobLogOrderByWithRelationInput.schema';
import { AcquisitionSpecJobLogWhereInputObjectSchema as AcquisitionSpecJobLogWhereInputObjectSchema } from './objects/AcquisitionSpecJobLogWhereInput.schema';
import { AcquisitionSpecJobLogWhereUniqueInputObjectSchema as AcquisitionSpecJobLogWhereUniqueInputObjectSchema } from './objects/AcquisitionSpecJobLogWhereUniqueInput.schema';
import { AcquisitionSpecJobLogCountAggregateInputObjectSchema as AcquisitionSpecJobLogCountAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogCountAggregateInput.schema';
import { AcquisitionSpecJobLogMinAggregateInputObjectSchema as AcquisitionSpecJobLogMinAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogMinAggregateInput.schema';
import { AcquisitionSpecJobLogMaxAggregateInputObjectSchema as AcquisitionSpecJobLogMaxAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogMaxAggregateInput.schema';

export const AcquisitionSpecJobLogAggregateSchema: z.ZodType<Prisma.AcquisitionSpecJobLogAggregateArgs> = z.object({ orderBy: z.union([AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema, AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobLogWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobLogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AcquisitionSpecJobLogCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobLogMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobLogMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AcquisitionSpecJobLogAggregateArgs>;

export const AcquisitionSpecJobLogAggregateZodSchema = z.object({ orderBy: z.union([AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema, AcquisitionSpecJobLogOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobLogWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobLogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AcquisitionSpecJobLogCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobLogMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobLogMaxAggregateInputObjectSchema.optional() }).strict();