import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowExecutionEventOrderByWithRelationInputObjectSchema as WorkflowExecutionEventOrderByWithRelationInputObjectSchema } from './objects/WorkflowExecutionEventOrderByWithRelationInput.schema';
import { WorkflowExecutionEventWhereInputObjectSchema as WorkflowExecutionEventWhereInputObjectSchema } from './objects/WorkflowExecutionEventWhereInput.schema';
import { WorkflowExecutionEventWhereUniqueInputObjectSchema as WorkflowExecutionEventWhereUniqueInputObjectSchema } from './objects/WorkflowExecutionEventWhereUniqueInput.schema';
import { WorkflowExecutionEventCountAggregateInputObjectSchema as WorkflowExecutionEventCountAggregateInputObjectSchema } from './objects/WorkflowExecutionEventCountAggregateInput.schema';
import { WorkflowExecutionEventMinAggregateInputObjectSchema as WorkflowExecutionEventMinAggregateInputObjectSchema } from './objects/WorkflowExecutionEventMinAggregateInput.schema';
import { WorkflowExecutionEventMaxAggregateInputObjectSchema as WorkflowExecutionEventMaxAggregateInputObjectSchema } from './objects/WorkflowExecutionEventMaxAggregateInput.schema';

export const WorkflowExecutionEventAggregateSchema: z.ZodType<Prisma.WorkflowExecutionEventAggregateArgs> = z.object({ orderBy: z.union([WorkflowExecutionEventOrderByWithRelationInputObjectSchema, WorkflowExecutionEventOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkflowExecutionEventWhereInputObjectSchema.optional(), cursor: WorkflowExecutionEventWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkflowExecutionEventCountAggregateInputObjectSchema ]).optional(), _min: WorkflowExecutionEventMinAggregateInputObjectSchema.optional(), _max: WorkflowExecutionEventMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowExecutionEventAggregateArgs>;

export const WorkflowExecutionEventAggregateZodSchema = z.object({ orderBy: z.union([WorkflowExecutionEventOrderByWithRelationInputObjectSchema, WorkflowExecutionEventOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkflowExecutionEventWhereInputObjectSchema.optional(), cursor: WorkflowExecutionEventWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkflowExecutionEventCountAggregateInputObjectSchema ]).optional(), _min: WorkflowExecutionEventMinAggregateInputObjectSchema.optional(), _max: WorkflowExecutionEventMaxAggregateInputObjectSchema.optional() }).strict();