import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema as CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema } from './objects/CarrierWebhookDeliveryOrderByWithRelationInput.schema';
import { CarrierWebhookDeliveryWhereInputObjectSchema as CarrierWebhookDeliveryWhereInputObjectSchema } from './objects/CarrierWebhookDeliveryWhereInput.schema';
import { CarrierWebhookDeliveryWhereUniqueInputObjectSchema as CarrierWebhookDeliveryWhereUniqueInputObjectSchema } from './objects/CarrierWebhookDeliveryWhereUniqueInput.schema';
import { CarrierWebhookDeliveryCountAggregateInputObjectSchema as CarrierWebhookDeliveryCountAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryCountAggregateInput.schema';
import { CarrierWebhookDeliveryMinAggregateInputObjectSchema as CarrierWebhookDeliveryMinAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryMinAggregateInput.schema';
import { CarrierWebhookDeliveryMaxAggregateInputObjectSchema as CarrierWebhookDeliveryMaxAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryMaxAggregateInput.schema';

export const CarrierWebhookDeliveryAggregateSchema: z.ZodType<Prisma.CarrierWebhookDeliveryAggregateArgs> = z.object({ orderBy: z.union([CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema, CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CarrierWebhookDeliveryWhereInputObjectSchema.optional(), cursor: CarrierWebhookDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CarrierWebhookDeliveryCountAggregateInputObjectSchema ]).optional(), _min: CarrierWebhookDeliveryMinAggregateInputObjectSchema.optional(), _max: CarrierWebhookDeliveryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CarrierWebhookDeliveryAggregateArgs>;

export const CarrierWebhookDeliveryAggregateZodSchema = z.object({ orderBy: z.union([CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema, CarrierWebhookDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CarrierWebhookDeliveryWhereInputObjectSchema.optional(), cursor: CarrierWebhookDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CarrierWebhookDeliveryCountAggregateInputObjectSchema ]).optional(), _min: CarrierWebhookDeliveryMinAggregateInputObjectSchema.optional(), _max: CarrierWebhookDeliveryMaxAggregateInputObjectSchema.optional() }).strict();