import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CarrierStatusHistoryOrderByWithRelationInputObjectSchema as CarrierStatusHistoryOrderByWithRelationInputObjectSchema } from './objects/CarrierStatusHistoryOrderByWithRelationInput.schema';
import { CarrierStatusHistoryWhereInputObjectSchema as CarrierStatusHistoryWhereInputObjectSchema } from './objects/CarrierStatusHistoryWhereInput.schema';
import { CarrierStatusHistoryWhereUniqueInputObjectSchema as CarrierStatusHistoryWhereUniqueInputObjectSchema } from './objects/CarrierStatusHistoryWhereUniqueInput.schema';
import { CarrierStatusHistoryCountAggregateInputObjectSchema as CarrierStatusHistoryCountAggregateInputObjectSchema } from './objects/CarrierStatusHistoryCountAggregateInput.schema';
import { CarrierStatusHistoryMinAggregateInputObjectSchema as CarrierStatusHistoryMinAggregateInputObjectSchema } from './objects/CarrierStatusHistoryMinAggregateInput.schema';
import { CarrierStatusHistoryMaxAggregateInputObjectSchema as CarrierStatusHistoryMaxAggregateInputObjectSchema } from './objects/CarrierStatusHistoryMaxAggregateInput.schema';

export const CarrierStatusHistoryAggregateSchema: z.ZodType<Prisma.CarrierStatusHistoryAggregateArgs> = z.object({ orderBy: z.union([CarrierStatusHistoryOrderByWithRelationInputObjectSchema, CarrierStatusHistoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CarrierStatusHistoryWhereInputObjectSchema.optional(), cursor: CarrierStatusHistoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CarrierStatusHistoryCountAggregateInputObjectSchema ]).optional(), _min: CarrierStatusHistoryMinAggregateInputObjectSchema.optional(), _max: CarrierStatusHistoryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CarrierStatusHistoryAggregateArgs>;

export const CarrierStatusHistoryAggregateZodSchema = z.object({ orderBy: z.union([CarrierStatusHistoryOrderByWithRelationInputObjectSchema, CarrierStatusHistoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CarrierStatusHistoryWhereInputObjectSchema.optional(), cursor: CarrierStatusHistoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CarrierStatusHistoryCountAggregateInputObjectSchema ]).optional(), _min: CarrierStatusHistoryMinAggregateInputObjectSchema.optional(), _max: CarrierStatusHistoryMaxAggregateInputObjectSchema.optional() }).strict();