import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { acquisition_spec_jobOrderByWithRelationInputObjectSchema as acquisition_spec_jobOrderByWithRelationInputObjectSchema } from './objects/acquisition_spec_jobOrderByWithRelationInput.schema';
import { acquisition_spec_jobWhereInputObjectSchema as acquisition_spec_jobWhereInputObjectSchema } from './objects/acquisition_spec_jobWhereInput.schema';
import { acquisition_spec_jobWhereUniqueInputObjectSchema as acquisition_spec_jobWhereUniqueInputObjectSchema } from './objects/acquisition_spec_jobWhereUniqueInput.schema';
import { Acquisition_spec_jobCountAggregateInputObjectSchema as Acquisition_spec_jobCountAggregateInputObjectSchema } from './objects/Acquisition_spec_jobCountAggregateInput.schema';
import { Acquisition_spec_jobMinAggregateInputObjectSchema as Acquisition_spec_jobMinAggregateInputObjectSchema } from './objects/Acquisition_spec_jobMinAggregateInput.schema';
import { Acquisition_spec_jobMaxAggregateInputObjectSchema as Acquisition_spec_jobMaxAggregateInputObjectSchema } from './objects/Acquisition_spec_jobMaxAggregateInput.schema';
import { Acquisition_spec_jobAvgAggregateInputObjectSchema as Acquisition_spec_jobAvgAggregateInputObjectSchema } from './objects/Acquisition_spec_jobAvgAggregateInput.schema';
import { Acquisition_spec_jobSumAggregateInputObjectSchema as Acquisition_spec_jobSumAggregateInputObjectSchema } from './objects/Acquisition_spec_jobSumAggregateInput.schema';

export const acquisition_spec_jobAggregateSchema: z.ZodType<Prisma.Acquisition_spec_jobAggregateArgs> = z.object({ orderBy: z.union([acquisition_spec_jobOrderByWithRelationInputObjectSchema, acquisition_spec_jobOrderByWithRelationInputObjectSchema.array()]).optional(), where: acquisition_spec_jobWhereInputObjectSchema.optional(), cursor: acquisition_spec_jobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional(), _min: Acquisition_spec_jobMinAggregateInputObjectSchema.optional(), _max: Acquisition_spec_jobMaxAggregateInputObjectSchema.optional(), _avg: Acquisition_spec_jobAvgAggregateInputObjectSchema.optional(), _sum: Acquisition_spec_jobSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.Acquisition_spec_jobAggregateArgs>;

export const acquisition_spec_jobAggregateZodSchema = z.object({ orderBy: z.union([acquisition_spec_jobOrderByWithRelationInputObjectSchema, acquisition_spec_jobOrderByWithRelationInputObjectSchema.array()]).optional(), where: acquisition_spec_jobWhereInputObjectSchema.optional(), cursor: acquisition_spec_jobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional(), _min: Acquisition_spec_jobMinAggregateInputObjectSchema.optional(), _max: Acquisition_spec_jobMaxAggregateInputObjectSchema.optional(), _avg: Acquisition_spec_jobAvgAggregateInputObjectSchema.optional(), _sum: Acquisition_spec_jobSumAggregateInputObjectSchema.optional() }).strict();