import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationChannelDeliveryOrderByWithRelationInputObjectSchema as NotificationChannelDeliveryOrderByWithRelationInputObjectSchema } from './objects/NotificationChannelDeliveryOrderByWithRelationInput.schema';
import { NotificationChannelDeliveryWhereInputObjectSchema as NotificationChannelDeliveryWhereInputObjectSchema } from './objects/NotificationChannelDeliveryWhereInput.schema';
import { NotificationChannelDeliveryWhereUniqueInputObjectSchema as NotificationChannelDeliveryWhereUniqueInputObjectSchema } from './objects/NotificationChannelDeliveryWhereUniqueInput.schema';
import { NotificationChannelDeliveryCountAggregateInputObjectSchema as NotificationChannelDeliveryCountAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryCountAggregateInput.schema';
import { NotificationChannelDeliveryMinAggregateInputObjectSchema as NotificationChannelDeliveryMinAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryMinAggregateInput.schema';
import { NotificationChannelDeliveryMaxAggregateInputObjectSchema as NotificationChannelDeliveryMaxAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryMaxAggregateInput.schema';

export const NotificationChannelDeliveryAggregateSchema: z.ZodType<Prisma.NotificationChannelDeliveryAggregateArgs> = z.object({ orderBy: z.union([NotificationChannelDeliveryOrderByWithRelationInputObjectSchema, NotificationChannelDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationChannelDeliveryWhereInputObjectSchema.optional(), cursor: NotificationChannelDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationChannelDeliveryCountAggregateInputObjectSchema ]).optional(), _min: NotificationChannelDeliveryMinAggregateInputObjectSchema.optional(), _max: NotificationChannelDeliveryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationChannelDeliveryAggregateArgs>;

export const NotificationChannelDeliveryAggregateZodSchema = z.object({ orderBy: z.union([NotificationChannelDeliveryOrderByWithRelationInputObjectSchema, NotificationChannelDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationChannelDeliveryWhereInputObjectSchema.optional(), cursor: NotificationChannelDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationChannelDeliveryCountAggregateInputObjectSchema ]).optional(), _min: NotificationChannelDeliveryMinAggregateInputObjectSchema.optional(), _max: NotificationChannelDeliveryMaxAggregateInputObjectSchema.optional() }).strict();