import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProjectionEventDeliveryOrderByWithRelationInputObjectSchema as ProjectionEventDeliveryOrderByWithRelationInputObjectSchema } from './objects/ProjectionEventDeliveryOrderByWithRelationInput.schema';
import { ProjectionEventDeliveryWhereInputObjectSchema as ProjectionEventDeliveryWhereInputObjectSchema } from './objects/ProjectionEventDeliveryWhereInput.schema';
import { ProjectionEventDeliveryWhereUniqueInputObjectSchema as ProjectionEventDeliveryWhereUniqueInputObjectSchema } from './objects/ProjectionEventDeliveryWhereUniqueInput.schema';
import { ProjectionEventDeliveryCountAggregateInputObjectSchema as ProjectionEventDeliveryCountAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryCountAggregateInput.schema';
import { ProjectionEventDeliveryMinAggregateInputObjectSchema as ProjectionEventDeliveryMinAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryMinAggregateInput.schema';
import { ProjectionEventDeliveryMaxAggregateInputObjectSchema as ProjectionEventDeliveryMaxAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryMaxAggregateInput.schema';
import { ProjectionEventDeliveryAvgAggregateInputObjectSchema as ProjectionEventDeliveryAvgAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryAvgAggregateInput.schema';
import { ProjectionEventDeliverySumAggregateInputObjectSchema as ProjectionEventDeliverySumAggregateInputObjectSchema } from './objects/ProjectionEventDeliverySumAggregateInput.schema';

export const ProjectionEventDeliveryAggregateSchema: z.ZodType<Prisma.ProjectionEventDeliveryAggregateArgs> = z.object({ orderBy: z.union([ProjectionEventDeliveryOrderByWithRelationInputObjectSchema, ProjectionEventDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProjectionEventDeliveryWhereInputObjectSchema.optional(), cursor: ProjectionEventDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProjectionEventDeliveryCountAggregateInputObjectSchema ]).optional(), _min: ProjectionEventDeliveryMinAggregateInputObjectSchema.optional(), _max: ProjectionEventDeliveryMaxAggregateInputObjectSchema.optional(), _avg: ProjectionEventDeliveryAvgAggregateInputObjectSchema.optional(), _sum: ProjectionEventDeliverySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProjectionEventDeliveryAggregateArgs>;

export const ProjectionEventDeliveryAggregateZodSchema = z.object({ orderBy: z.union([ProjectionEventDeliveryOrderByWithRelationInputObjectSchema, ProjectionEventDeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProjectionEventDeliveryWhereInputObjectSchema.optional(), cursor: ProjectionEventDeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProjectionEventDeliveryCountAggregateInputObjectSchema ]).optional(), _min: ProjectionEventDeliveryMinAggregateInputObjectSchema.optional(), _max: ProjectionEventDeliveryMaxAggregateInputObjectSchema.optional(), _avg: ProjectionEventDeliveryAvgAggregateInputObjectSchema.optional(), _sum: ProjectionEventDeliverySumAggregateInputObjectSchema.optional() }).strict();