import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SystemJobControlOrderByWithRelationInputObjectSchema as SystemJobControlOrderByWithRelationInputObjectSchema } from './objects/SystemJobControlOrderByWithRelationInput.schema';
import { SystemJobControlWhereInputObjectSchema as SystemJobControlWhereInputObjectSchema } from './objects/SystemJobControlWhereInput.schema';
import { SystemJobControlWhereUniqueInputObjectSchema as SystemJobControlWhereUniqueInputObjectSchema } from './objects/SystemJobControlWhereUniqueInput.schema';
import { SystemJobControlCountAggregateInputObjectSchema as SystemJobControlCountAggregateInputObjectSchema } from './objects/SystemJobControlCountAggregateInput.schema';
import { SystemJobControlMinAggregateInputObjectSchema as SystemJobControlMinAggregateInputObjectSchema } from './objects/SystemJobControlMinAggregateInput.schema';
import { SystemJobControlMaxAggregateInputObjectSchema as SystemJobControlMaxAggregateInputObjectSchema } from './objects/SystemJobControlMaxAggregateInput.schema';
import { SystemJobControlAvgAggregateInputObjectSchema as SystemJobControlAvgAggregateInputObjectSchema } from './objects/SystemJobControlAvgAggregateInput.schema';
import { SystemJobControlSumAggregateInputObjectSchema as SystemJobControlSumAggregateInputObjectSchema } from './objects/SystemJobControlSumAggregateInput.schema';

export const SystemJobControlAggregateSchema: z.ZodType<Prisma.SystemJobControlAggregateArgs> = z.object({ orderBy: z.union([SystemJobControlOrderByWithRelationInputObjectSchema, SystemJobControlOrderByWithRelationInputObjectSchema.array()]).optional(), where: SystemJobControlWhereInputObjectSchema.optional(), cursor: SystemJobControlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SystemJobControlCountAggregateInputObjectSchema ]).optional(), _min: SystemJobControlMinAggregateInputObjectSchema.optional(), _max: SystemJobControlMaxAggregateInputObjectSchema.optional(), _avg: SystemJobControlAvgAggregateInputObjectSchema.optional(), _sum: SystemJobControlSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SystemJobControlAggregateArgs>;

export const SystemJobControlAggregateZodSchema = z.object({ orderBy: z.union([SystemJobControlOrderByWithRelationInputObjectSchema, SystemJobControlOrderByWithRelationInputObjectSchema.array()]).optional(), where: SystemJobControlWhereInputObjectSchema.optional(), cursor: SystemJobControlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SystemJobControlCountAggregateInputObjectSchema ]).optional(), _min: SystemJobControlMinAggregateInputObjectSchema.optional(), _max: SystemJobControlMaxAggregateInputObjectSchema.optional(), _avg: SystemJobControlAvgAggregateInputObjectSchema.optional(), _sum: SystemJobControlSumAggregateInputObjectSchema.optional() }).strict();