import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskItemChecklistOrderByWithRelationInputObjectSchema as TaskItemChecklistOrderByWithRelationInputObjectSchema } from './objects/TaskItemChecklistOrderByWithRelationInput.schema';
import { TaskItemChecklistWhereInputObjectSchema as TaskItemChecklistWhereInputObjectSchema } from './objects/TaskItemChecklistWhereInput.schema';
import { TaskItemChecklistWhereUniqueInputObjectSchema as TaskItemChecklistWhereUniqueInputObjectSchema } from './objects/TaskItemChecklistWhereUniqueInput.schema';
import { TaskItemChecklistCountAggregateInputObjectSchema as TaskItemChecklistCountAggregateInputObjectSchema } from './objects/TaskItemChecklistCountAggregateInput.schema';
import { TaskItemChecklistMinAggregateInputObjectSchema as TaskItemChecklistMinAggregateInputObjectSchema } from './objects/TaskItemChecklistMinAggregateInput.schema';
import { TaskItemChecklistMaxAggregateInputObjectSchema as TaskItemChecklistMaxAggregateInputObjectSchema } from './objects/TaskItemChecklistMaxAggregateInput.schema';
import { TaskItemChecklistAvgAggregateInputObjectSchema as TaskItemChecklistAvgAggregateInputObjectSchema } from './objects/TaskItemChecklistAvgAggregateInput.schema';
import { TaskItemChecklistSumAggregateInputObjectSchema as TaskItemChecklistSumAggregateInputObjectSchema } from './objects/TaskItemChecklistSumAggregateInput.schema';

export const TaskItemChecklistAggregateSchema: z.ZodType<Prisma.TaskItemChecklistAggregateArgs> = z.object({ orderBy: z.union([TaskItemChecklistOrderByWithRelationInputObjectSchema, TaskItemChecklistOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskItemChecklistWhereInputObjectSchema.optional(), cursor: TaskItemChecklistWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskItemChecklistCountAggregateInputObjectSchema ]).optional(), _min: TaskItemChecklistMinAggregateInputObjectSchema.optional(), _max: TaskItemChecklistMaxAggregateInputObjectSchema.optional(), _avg: TaskItemChecklistAvgAggregateInputObjectSchema.optional(), _sum: TaskItemChecklistSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskItemChecklistAggregateArgs>;

export const TaskItemChecklistAggregateZodSchema = z.object({ orderBy: z.union([TaskItemChecklistOrderByWithRelationInputObjectSchema, TaskItemChecklistOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskItemChecklistWhereInputObjectSchema.optional(), cursor: TaskItemChecklistWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskItemChecklistCountAggregateInputObjectSchema ]).optional(), _min: TaskItemChecklistMinAggregateInputObjectSchema.optional(), _max: TaskItemChecklistMaxAggregateInputObjectSchema.optional(), _avg: TaskItemChecklistAvgAggregateInputObjectSchema.optional(), _sum: TaskItemChecklistSumAggregateInputObjectSchema.optional() }).strict();