import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestActivityOrderByWithRelationInputObjectSchema as PurchaseRequestActivityOrderByWithRelationInputObjectSchema } from './objects/PurchaseRequestActivityOrderByWithRelationInput.schema';
import { PurchaseRequestActivityWhereInputObjectSchema as PurchaseRequestActivityWhereInputObjectSchema } from './objects/PurchaseRequestActivityWhereInput.schema';
import { PurchaseRequestActivityWhereUniqueInputObjectSchema as PurchaseRequestActivityWhereUniqueInputObjectSchema } from './objects/PurchaseRequestActivityWhereUniqueInput.schema';
import { PurchaseRequestActivityCountAggregateInputObjectSchema as PurchaseRequestActivityCountAggregateInputObjectSchema } from './objects/PurchaseRequestActivityCountAggregateInput.schema';
import { PurchaseRequestActivityMinAggregateInputObjectSchema as PurchaseRequestActivityMinAggregateInputObjectSchema } from './objects/PurchaseRequestActivityMinAggregateInput.schema';
import { PurchaseRequestActivityMaxAggregateInputObjectSchema as PurchaseRequestActivityMaxAggregateInputObjectSchema } from './objects/PurchaseRequestActivityMaxAggregateInput.schema';

export const PurchaseRequestActivityAggregateSchema: z.ZodType<Prisma.PurchaseRequestActivityAggregateArgs> = z.object({ orderBy: z.union([PurchaseRequestActivityOrderByWithRelationInputObjectSchema, PurchaseRequestActivityOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestActivityWhereInputObjectSchema.optional(), cursor: PurchaseRequestActivityWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestActivityCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestActivityMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestActivityMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestActivityAggregateArgs>;

export const PurchaseRequestActivityAggregateZodSchema = z.object({ orderBy: z.union([PurchaseRequestActivityOrderByWithRelationInputObjectSchema, PurchaseRequestActivityOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestActivityWhereInputObjectSchema.optional(), cursor: PurchaseRequestActivityWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestActivityCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestActivityMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestActivityMaxAggregateInputObjectSchema.optional() }).strict();