import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkCaseCategoryOrderByWithRelationInputObjectSchema as WorkCaseCategoryOrderByWithRelationInputObjectSchema } from './objects/WorkCaseCategoryOrderByWithRelationInput.schema';
import { WorkCaseCategoryWhereInputObjectSchema as WorkCaseCategoryWhereInputObjectSchema } from './objects/WorkCaseCategoryWhereInput.schema';
import { WorkCaseCategoryWhereUniqueInputObjectSchema as WorkCaseCategoryWhereUniqueInputObjectSchema } from './objects/WorkCaseCategoryWhereUniqueInput.schema';
import { WorkCaseCategoryCountAggregateInputObjectSchema as WorkCaseCategoryCountAggregateInputObjectSchema } from './objects/WorkCaseCategoryCountAggregateInput.schema';
import { WorkCaseCategoryMinAggregateInputObjectSchema as WorkCaseCategoryMinAggregateInputObjectSchema } from './objects/WorkCaseCategoryMinAggregateInput.schema';
import { WorkCaseCategoryMaxAggregateInputObjectSchema as WorkCaseCategoryMaxAggregateInputObjectSchema } from './objects/WorkCaseCategoryMaxAggregateInput.schema';
import { WorkCaseCategoryAvgAggregateInputObjectSchema as WorkCaseCategoryAvgAggregateInputObjectSchema } from './objects/WorkCaseCategoryAvgAggregateInput.schema';
import { WorkCaseCategorySumAggregateInputObjectSchema as WorkCaseCategorySumAggregateInputObjectSchema } from './objects/WorkCaseCategorySumAggregateInput.schema';

export const WorkCaseCategoryAggregateSchema: z.ZodType<Prisma.WorkCaseCategoryAggregateArgs> = z.object({ orderBy: z.union([WorkCaseCategoryOrderByWithRelationInputObjectSchema, WorkCaseCategoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkCaseCategoryWhereInputObjectSchema.optional(), cursor: WorkCaseCategoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkCaseCategoryCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseCategoryMinAggregateInputObjectSchema.optional(), _max: WorkCaseCategoryMaxAggregateInputObjectSchema.optional(), _avg: WorkCaseCategoryAvgAggregateInputObjectSchema.optional(), _sum: WorkCaseCategorySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkCaseCategoryAggregateArgs>;

export const WorkCaseCategoryAggregateZodSchema = z.object({ orderBy: z.union([WorkCaseCategoryOrderByWithRelationInputObjectSchema, WorkCaseCategoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: WorkCaseCategoryWhereInputObjectSchema.optional(), cursor: WorkCaseCategoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WorkCaseCategoryCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseCategoryMinAggregateInputObjectSchema.optional(), _max: WorkCaseCategoryMaxAggregateInputObjectSchema.optional(), _avg: WorkCaseCategoryAvgAggregateInputObjectSchema.optional(), _sum: WorkCaseCategorySumAggregateInputObjectSchema.optional() }).strict();