import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationDispatchOrderByWithRelationInputObjectSchema as NotificationDispatchOrderByWithRelationInputObjectSchema } from './objects/NotificationDispatchOrderByWithRelationInput.schema';
import { NotificationDispatchWhereInputObjectSchema as NotificationDispatchWhereInputObjectSchema } from './objects/NotificationDispatchWhereInput.schema';
import { NotificationDispatchWhereUniqueInputObjectSchema as NotificationDispatchWhereUniqueInputObjectSchema } from './objects/NotificationDispatchWhereUniqueInput.schema';
import { NotificationDispatchCountAggregateInputObjectSchema as NotificationDispatchCountAggregateInputObjectSchema } from './objects/NotificationDispatchCountAggregateInput.schema';
import { NotificationDispatchMinAggregateInputObjectSchema as NotificationDispatchMinAggregateInputObjectSchema } from './objects/NotificationDispatchMinAggregateInput.schema';
import { NotificationDispatchMaxAggregateInputObjectSchema as NotificationDispatchMaxAggregateInputObjectSchema } from './objects/NotificationDispatchMaxAggregateInput.schema';

export const NotificationDispatchAggregateSchema: z.ZodType<Prisma.NotificationDispatchAggregateArgs> = z.object({ orderBy: z.union([NotificationDispatchOrderByWithRelationInputObjectSchema, NotificationDispatchOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationDispatchWhereInputObjectSchema.optional(), cursor: NotificationDispatchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationDispatchCountAggregateInputObjectSchema ]).optional(), _min: NotificationDispatchMinAggregateInputObjectSchema.optional(), _max: NotificationDispatchMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationDispatchAggregateArgs>;

export const NotificationDispatchAggregateZodSchema = z.object({ orderBy: z.union([NotificationDispatchOrderByWithRelationInputObjectSchema, NotificationDispatchOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationDispatchWhereInputObjectSchema.optional(), cursor: NotificationDispatchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationDispatchCountAggregateInputObjectSchema ]).optional(), _min: NotificationDispatchMinAggregateInputObjectSchema.optional(), _max: NotificationDispatchMaxAggregateInputObjectSchema.optional() }).strict();