import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WatchStrapInstallationOrderByWithRelationInputObjectSchema as WatchStrapInstallationOrderByWithRelationInputObjectSchema } from './objects/WatchStrapInstallationOrderByWithRelationInput.schema';
import { WatchStrapInstallationWhereInputObjectSchema as WatchStrapInstallationWhereInputObjectSchema } from './objects/WatchStrapInstallationWhereInput.schema';
import { WatchStrapInstallationWhereUniqueInputObjectSchema as WatchStrapInstallationWhereUniqueInputObjectSchema } from './objects/WatchStrapInstallationWhereUniqueInput.schema';
import { WatchStrapInstallationCountAggregateInputObjectSchema as WatchStrapInstallationCountAggregateInputObjectSchema } from './objects/WatchStrapInstallationCountAggregateInput.schema';
import { WatchStrapInstallationMinAggregateInputObjectSchema as WatchStrapInstallationMinAggregateInputObjectSchema } from './objects/WatchStrapInstallationMinAggregateInput.schema';
import { WatchStrapInstallationMaxAggregateInputObjectSchema as WatchStrapInstallationMaxAggregateInputObjectSchema } from './objects/WatchStrapInstallationMaxAggregateInput.schema';
import { WatchStrapInstallationAvgAggregateInputObjectSchema as WatchStrapInstallationAvgAggregateInputObjectSchema } from './objects/WatchStrapInstallationAvgAggregateInput.schema';
import { WatchStrapInstallationSumAggregateInputObjectSchema as WatchStrapInstallationSumAggregateInputObjectSchema } from './objects/WatchStrapInstallationSumAggregateInput.schema';

export const WatchStrapInstallationAggregateSchema: z.ZodType<Prisma.WatchStrapInstallationAggregateArgs> = z.object({ orderBy: z.union([WatchStrapInstallationOrderByWithRelationInputObjectSchema, WatchStrapInstallationOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchStrapInstallationWhereInputObjectSchema.optional(), cursor: WatchStrapInstallationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchStrapInstallationCountAggregateInputObjectSchema ]).optional(), _min: WatchStrapInstallationMinAggregateInputObjectSchema.optional(), _max: WatchStrapInstallationMaxAggregateInputObjectSchema.optional(), _avg: WatchStrapInstallationAvgAggregateInputObjectSchema.optional(), _sum: WatchStrapInstallationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WatchStrapInstallationAggregateArgs>;

export const WatchStrapInstallationAggregateZodSchema = z.object({ orderBy: z.union([WatchStrapInstallationOrderByWithRelationInputObjectSchema, WatchStrapInstallationOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchStrapInstallationWhereInputObjectSchema.optional(), cursor: WatchStrapInstallationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchStrapInstallationCountAggregateInputObjectSchema ]).optional(), _min: WatchStrapInstallationMinAggregateInputObjectSchema.optional(), _max: WatchStrapInstallationMaxAggregateInputObjectSchema.optional(), _avg: WatchStrapInstallationAvgAggregateInputObjectSchema.optional(), _sum: WatchStrapInstallationSumAggregateInputObjectSchema.optional() }).strict();