import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskItemActivityReplyOrderByWithRelationInputObjectSchema as TaskItemActivityReplyOrderByWithRelationInputObjectSchema } from './objects/TaskItemActivityReplyOrderByWithRelationInput.schema';
import { TaskItemActivityReplyWhereInputObjectSchema as TaskItemActivityReplyWhereInputObjectSchema } from './objects/TaskItemActivityReplyWhereInput.schema';
import { TaskItemActivityReplyWhereUniqueInputObjectSchema as TaskItemActivityReplyWhereUniqueInputObjectSchema } from './objects/TaskItemActivityReplyWhereUniqueInput.schema';
import { TaskItemActivityReplyCountAggregateInputObjectSchema as TaskItemActivityReplyCountAggregateInputObjectSchema } from './objects/TaskItemActivityReplyCountAggregateInput.schema';
import { TaskItemActivityReplyMinAggregateInputObjectSchema as TaskItemActivityReplyMinAggregateInputObjectSchema } from './objects/TaskItemActivityReplyMinAggregateInput.schema';
import { TaskItemActivityReplyMaxAggregateInputObjectSchema as TaskItemActivityReplyMaxAggregateInputObjectSchema } from './objects/TaskItemActivityReplyMaxAggregateInput.schema';

export const TaskItemActivityReplyAggregateSchema: z.ZodType<Prisma.TaskItemActivityReplyAggregateArgs> = z.object({ orderBy: z.union([TaskItemActivityReplyOrderByWithRelationInputObjectSchema, TaskItemActivityReplyOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskItemActivityReplyWhereInputObjectSchema.optional(), cursor: TaskItemActivityReplyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskItemActivityReplyCountAggregateInputObjectSchema ]).optional(), _min: TaskItemActivityReplyMinAggregateInputObjectSchema.optional(), _max: TaskItemActivityReplyMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskItemActivityReplyAggregateArgs>;

export const TaskItemActivityReplyAggregateZodSchema = z.object({ orderBy: z.union([TaskItemActivityReplyOrderByWithRelationInputObjectSchema, TaskItemActivityReplyOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskItemActivityReplyWhereInputObjectSchema.optional(), cursor: TaskItemActivityReplyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskItemActivityReplyCountAggregateInputObjectSchema ]).optional(), _min: TaskItemActivityReplyMinAggregateInputObjectSchema.optional(), _max: TaskItemActivityReplyMaxAggregateInputObjectSchema.optional() }).strict();