import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskTypeOrderByWithRelationInputObjectSchema as TaskTypeOrderByWithRelationInputObjectSchema } from './objects/TaskTypeOrderByWithRelationInput.schema';
import { TaskTypeWhereInputObjectSchema as TaskTypeWhereInputObjectSchema } from './objects/TaskTypeWhereInput.schema';
import { TaskTypeWhereUniqueInputObjectSchema as TaskTypeWhereUniqueInputObjectSchema } from './objects/TaskTypeWhereUniqueInput.schema';
import { TaskTypeCountAggregateInputObjectSchema as TaskTypeCountAggregateInputObjectSchema } from './objects/TaskTypeCountAggregateInput.schema';
import { TaskTypeMinAggregateInputObjectSchema as TaskTypeMinAggregateInputObjectSchema } from './objects/TaskTypeMinAggregateInput.schema';
import { TaskTypeMaxAggregateInputObjectSchema as TaskTypeMaxAggregateInputObjectSchema } from './objects/TaskTypeMaxAggregateInput.schema';
import { TaskTypeAvgAggregateInputObjectSchema as TaskTypeAvgAggregateInputObjectSchema } from './objects/TaskTypeAvgAggregateInput.schema';
import { TaskTypeSumAggregateInputObjectSchema as TaskTypeSumAggregateInputObjectSchema } from './objects/TaskTypeSumAggregateInput.schema';

export const TaskTypeAggregateSchema: z.ZodType<Prisma.TaskTypeAggregateArgs> = z.object({ orderBy: z.union([TaskTypeOrderByWithRelationInputObjectSchema, TaskTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskTypeWhereInputObjectSchema.optional(), cursor: TaskTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskTypeCountAggregateInputObjectSchema ]).optional(), _min: TaskTypeMinAggregateInputObjectSchema.optional(), _max: TaskTypeMaxAggregateInputObjectSchema.optional(), _avg: TaskTypeAvgAggregateInputObjectSchema.optional(), _sum: TaskTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskTypeAggregateArgs>;

export const TaskTypeAggregateZodSchema = z.object({ orderBy: z.union([TaskTypeOrderByWithRelationInputObjectSchema, TaskTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskTypeWhereInputObjectSchema.optional(), cursor: TaskTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskTypeCountAggregateInputObjectSchema ]).optional(), _min: TaskTypeMinAggregateInputObjectSchema.optional(), _max: TaskTypeMaxAggregateInputObjectSchema.optional(), _avg: TaskTypeAvgAggregateInputObjectSchema.optional(), _sum: TaskTypeSumAggregateInputObjectSchema.optional() }).strict();