import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestItemOrderByWithRelationInputObjectSchema as PurchaseRequestItemOrderByWithRelationInputObjectSchema } from './objects/PurchaseRequestItemOrderByWithRelationInput.schema';
import { PurchaseRequestItemWhereInputObjectSchema as PurchaseRequestItemWhereInputObjectSchema } from './objects/PurchaseRequestItemWhereInput.schema';
import { PurchaseRequestItemWhereUniqueInputObjectSchema as PurchaseRequestItemWhereUniqueInputObjectSchema } from './objects/PurchaseRequestItemWhereUniqueInput.schema';
import { PurchaseRequestItemCountAggregateInputObjectSchema as PurchaseRequestItemCountAggregateInputObjectSchema } from './objects/PurchaseRequestItemCountAggregateInput.schema';
import { PurchaseRequestItemMinAggregateInputObjectSchema as PurchaseRequestItemMinAggregateInputObjectSchema } from './objects/PurchaseRequestItemMinAggregateInput.schema';
import { PurchaseRequestItemMaxAggregateInputObjectSchema as PurchaseRequestItemMaxAggregateInputObjectSchema } from './objects/PurchaseRequestItemMaxAggregateInput.schema';
import { PurchaseRequestItemAvgAggregateInputObjectSchema as PurchaseRequestItemAvgAggregateInputObjectSchema } from './objects/PurchaseRequestItemAvgAggregateInput.schema';
import { PurchaseRequestItemSumAggregateInputObjectSchema as PurchaseRequestItemSumAggregateInputObjectSchema } from './objects/PurchaseRequestItemSumAggregateInput.schema';

export const PurchaseRequestItemAggregateSchema: z.ZodType<Prisma.PurchaseRequestItemAggregateArgs> = z.object({ orderBy: z.union([PurchaseRequestItemOrderByWithRelationInputObjectSchema, PurchaseRequestItemOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestItemWhereInputObjectSchema.optional(), cursor: PurchaseRequestItemWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestItemCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestItemMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestItemMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestItemAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestItemSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestItemAggregateArgs>;

export const PurchaseRequestItemAggregateZodSchema = z.object({ orderBy: z.union([PurchaseRequestItemOrderByWithRelationInputObjectSchema, PurchaseRequestItemOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestItemWhereInputObjectSchema.optional(), cursor: PurchaseRequestItemWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestItemCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestItemMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestItemMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestItemAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestItemSumAggregateInputObjectSchema.optional() }).strict();