import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationRecipientGroupOrderByWithRelationInputObjectSchema as NotificationRecipientGroupOrderByWithRelationInputObjectSchema } from './objects/NotificationRecipientGroupOrderByWithRelationInput.schema';
import { NotificationRecipientGroupWhereInputObjectSchema as NotificationRecipientGroupWhereInputObjectSchema } from './objects/NotificationRecipientGroupWhereInput.schema';
import { NotificationRecipientGroupWhereUniqueInputObjectSchema as NotificationRecipientGroupWhereUniqueInputObjectSchema } from './objects/NotificationRecipientGroupWhereUniqueInput.schema';
import { NotificationRecipientGroupCountAggregateInputObjectSchema as NotificationRecipientGroupCountAggregateInputObjectSchema } from './objects/NotificationRecipientGroupCountAggregateInput.schema';
import { NotificationRecipientGroupMinAggregateInputObjectSchema as NotificationRecipientGroupMinAggregateInputObjectSchema } from './objects/NotificationRecipientGroupMinAggregateInput.schema';
import { NotificationRecipientGroupMaxAggregateInputObjectSchema as NotificationRecipientGroupMaxAggregateInputObjectSchema } from './objects/NotificationRecipientGroupMaxAggregateInput.schema';

export const NotificationRecipientGroupAggregateSchema: z.ZodType<Prisma.NotificationRecipientGroupAggregateArgs> = z.object({ orderBy: z.union([NotificationRecipientGroupOrderByWithRelationInputObjectSchema, NotificationRecipientGroupOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationRecipientGroupWhereInputObjectSchema.optional(), cursor: NotificationRecipientGroupWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationRecipientGroupCountAggregateInputObjectSchema ]).optional(), _min: NotificationRecipientGroupMinAggregateInputObjectSchema.optional(), _max: NotificationRecipientGroupMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationRecipientGroupAggregateArgs>;

export const NotificationRecipientGroupAggregateZodSchema = z.object({ orderBy: z.union([NotificationRecipientGroupOrderByWithRelationInputObjectSchema, NotificationRecipientGroupOrderByWithRelationInputObjectSchema.array()]).optional(), where: NotificationRecipientGroupWhereInputObjectSchema.optional(), cursor: NotificationRecipientGroupWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), NotificationRecipientGroupCountAggregateInputObjectSchema ]).optional(), _min: NotificationRecipientGroupMinAggregateInputObjectSchema.optional(), _max: NotificationRecipientGroupMaxAggregateInputObjectSchema.optional() }).strict();