import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskChecklistItemOrderByWithRelationInputObjectSchema as TaskChecklistItemOrderByWithRelationInputObjectSchema } from './objects/TaskChecklistItemOrderByWithRelationInput.schema';
import { TaskChecklistItemWhereInputObjectSchema as TaskChecklistItemWhereInputObjectSchema } from './objects/TaskChecklistItemWhereInput.schema';
import { TaskChecklistItemWhereUniqueInputObjectSchema as TaskChecklistItemWhereUniqueInputObjectSchema } from './objects/TaskChecklistItemWhereUniqueInput.schema';
import { TaskChecklistItemCountAggregateInputObjectSchema as TaskChecklistItemCountAggregateInputObjectSchema } from './objects/TaskChecklistItemCountAggregateInput.schema';
import { TaskChecklistItemMinAggregateInputObjectSchema as TaskChecklistItemMinAggregateInputObjectSchema } from './objects/TaskChecklistItemMinAggregateInput.schema';
import { TaskChecklistItemMaxAggregateInputObjectSchema as TaskChecklistItemMaxAggregateInputObjectSchema } from './objects/TaskChecklistItemMaxAggregateInput.schema';
import { TaskChecklistItemAvgAggregateInputObjectSchema as TaskChecklistItemAvgAggregateInputObjectSchema } from './objects/TaskChecklistItemAvgAggregateInput.schema';
import { TaskChecklistItemSumAggregateInputObjectSchema as TaskChecklistItemSumAggregateInputObjectSchema } from './objects/TaskChecklistItemSumAggregateInput.schema';

export const TaskChecklistItemAggregateSchema: z.ZodType<Prisma.TaskChecklistItemAggregateArgs> = z.object({ orderBy: z.union([TaskChecklistItemOrderByWithRelationInputObjectSchema, TaskChecklistItemOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskChecklistItemWhereInputObjectSchema.optional(), cursor: TaskChecklistItemWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskChecklistItemCountAggregateInputObjectSchema ]).optional(), _min: TaskChecklistItemMinAggregateInputObjectSchema.optional(), _max: TaskChecklistItemMaxAggregateInputObjectSchema.optional(), _avg: TaskChecklistItemAvgAggregateInputObjectSchema.optional(), _sum: TaskChecklistItemSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskChecklistItemAggregateArgs>;

export const TaskChecklistItemAggregateZodSchema = z.object({ orderBy: z.union([TaskChecklistItemOrderByWithRelationInputObjectSchema, TaskChecklistItemOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaskChecklistItemWhereInputObjectSchema.optional(), cursor: TaskChecklistItemWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaskChecklistItemCountAggregateInputObjectSchema ]).optional(), _min: TaskChecklistItemMinAggregateInputObjectSchema.optional(), _max: TaskChecklistItemMaxAggregateInputObjectSchema.optional(), _avg: TaskChecklistItemAvgAggregateInputObjectSchema.optional(), _sum: TaskChecklistItemSumAggregateInputObjectSchema.optional() }).strict();