import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StorefrontHeroImageOrderByWithRelationInputObjectSchema as StorefrontHeroImageOrderByWithRelationInputObjectSchema } from './objects/StorefrontHeroImageOrderByWithRelationInput.schema';
import { StorefrontHeroImageWhereInputObjectSchema as StorefrontHeroImageWhereInputObjectSchema } from './objects/StorefrontHeroImageWhereInput.schema';
import { StorefrontHeroImageWhereUniqueInputObjectSchema as StorefrontHeroImageWhereUniqueInputObjectSchema } from './objects/StorefrontHeroImageWhereUniqueInput.schema';
import { StorefrontHeroImageCountAggregateInputObjectSchema as StorefrontHeroImageCountAggregateInputObjectSchema } from './objects/StorefrontHeroImageCountAggregateInput.schema';
import { StorefrontHeroImageMinAggregateInputObjectSchema as StorefrontHeroImageMinAggregateInputObjectSchema } from './objects/StorefrontHeroImageMinAggregateInput.schema';
import { StorefrontHeroImageMaxAggregateInputObjectSchema as StorefrontHeroImageMaxAggregateInputObjectSchema } from './objects/StorefrontHeroImageMaxAggregateInput.schema';
import { StorefrontHeroImageAvgAggregateInputObjectSchema as StorefrontHeroImageAvgAggregateInputObjectSchema } from './objects/StorefrontHeroImageAvgAggregateInput.schema';
import { StorefrontHeroImageSumAggregateInputObjectSchema as StorefrontHeroImageSumAggregateInputObjectSchema } from './objects/StorefrontHeroImageSumAggregateInput.schema';

export const StorefrontHeroImageAggregateSchema: z.ZodType<Prisma.StorefrontHeroImageAggregateArgs> = z.object({ orderBy: z.union([StorefrontHeroImageOrderByWithRelationInputObjectSchema, StorefrontHeroImageOrderByWithRelationInputObjectSchema.array()]).optional(), where: StorefrontHeroImageWhereInputObjectSchema.optional(), cursor: StorefrontHeroImageWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StorefrontHeroImageCountAggregateInputObjectSchema ]).optional(), _min: StorefrontHeroImageMinAggregateInputObjectSchema.optional(), _max: StorefrontHeroImageMaxAggregateInputObjectSchema.optional(), _avg: StorefrontHeroImageAvgAggregateInputObjectSchema.optional(), _sum: StorefrontHeroImageSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StorefrontHeroImageAggregateArgs>;

export const StorefrontHeroImageAggregateZodSchema = z.object({ orderBy: z.union([StorefrontHeroImageOrderByWithRelationInputObjectSchema, StorefrontHeroImageOrderByWithRelationInputObjectSchema.array()]).optional(), where: StorefrontHeroImageWhereInputObjectSchema.optional(), cursor: StorefrontHeroImageWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StorefrontHeroImageCountAggregateInputObjectSchema ]).optional(), _min: StorefrontHeroImageMinAggregateInputObjectSchema.optional(), _max: StorefrontHeroImageMaxAggregateInputObjectSchema.optional(), _avg: StorefrontHeroImageAvgAggregateInputObjectSchema.optional(), _sum: StorefrontHeroImageSumAggregateInputObjectSchema.optional() }).strict();