import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema as PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema } from './objects/PurchaseRequestIngressReceiptOrderByWithRelationInput.schema';
import { PurchaseRequestIngressReceiptWhereInputObjectSchema as PurchaseRequestIngressReceiptWhereInputObjectSchema } from './objects/PurchaseRequestIngressReceiptWhereInput.schema';
import { PurchaseRequestIngressReceiptWhereUniqueInputObjectSchema as PurchaseRequestIngressReceiptWhereUniqueInputObjectSchema } from './objects/PurchaseRequestIngressReceiptWhereUniqueInput.schema';
import { PurchaseRequestIngressReceiptCountAggregateInputObjectSchema as PurchaseRequestIngressReceiptCountAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptCountAggregateInput.schema';
import { PurchaseRequestIngressReceiptMinAggregateInputObjectSchema as PurchaseRequestIngressReceiptMinAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptMinAggregateInput.schema';
import { PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema as PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptMaxAggregateInput.schema';
import { PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema as PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptAvgAggregateInput.schema';
import { PurchaseRequestIngressReceiptSumAggregateInputObjectSchema as PurchaseRequestIngressReceiptSumAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptSumAggregateInput.schema';

export const PurchaseRequestIngressReceiptAggregateSchema: z.ZodType<Prisma.PurchaseRequestIngressReceiptAggregateArgs> = z.object({ orderBy: z.union([PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema, PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestIngressReceiptWhereInputObjectSchema.optional(), cursor: PurchaseRequestIngressReceiptWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestIngressReceiptMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestIngressReceiptSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestIngressReceiptAggregateArgs>;

export const PurchaseRequestIngressReceiptAggregateZodSchema = z.object({ orderBy: z.union([PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema, PurchaseRequestIngressReceiptOrderByWithRelationInputObjectSchema.array()]).optional(), where: PurchaseRequestIngressReceiptWhereInputObjectSchema.optional(), cursor: PurchaseRequestIngressReceiptWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PurchaseRequestIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestIngressReceiptMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestIngressReceiptSumAggregateInputObjectSchema.optional() }).strict();