import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StrapInventoryMovementOrderByWithRelationInputObjectSchema as StrapInventoryMovementOrderByWithRelationInputObjectSchema } from './objects/StrapInventoryMovementOrderByWithRelationInput.schema';
import { StrapInventoryMovementWhereInputObjectSchema as StrapInventoryMovementWhereInputObjectSchema } from './objects/StrapInventoryMovementWhereInput.schema';
import { StrapInventoryMovementWhereUniqueInputObjectSchema as StrapInventoryMovementWhereUniqueInputObjectSchema } from './objects/StrapInventoryMovementWhereUniqueInput.schema';
import { StrapInventoryMovementCountAggregateInputObjectSchema as StrapInventoryMovementCountAggregateInputObjectSchema } from './objects/StrapInventoryMovementCountAggregateInput.schema';
import { StrapInventoryMovementMinAggregateInputObjectSchema as StrapInventoryMovementMinAggregateInputObjectSchema } from './objects/StrapInventoryMovementMinAggregateInput.schema';
import { StrapInventoryMovementMaxAggregateInputObjectSchema as StrapInventoryMovementMaxAggregateInputObjectSchema } from './objects/StrapInventoryMovementMaxAggregateInput.schema';
import { StrapInventoryMovementAvgAggregateInputObjectSchema as StrapInventoryMovementAvgAggregateInputObjectSchema } from './objects/StrapInventoryMovementAvgAggregateInput.schema';
import { StrapInventoryMovementSumAggregateInputObjectSchema as StrapInventoryMovementSumAggregateInputObjectSchema } from './objects/StrapInventoryMovementSumAggregateInput.schema';

export const StrapInventoryMovementAggregateSchema: z.ZodType<Prisma.StrapInventoryMovementAggregateArgs> = z.object({ orderBy: z.union([StrapInventoryMovementOrderByWithRelationInputObjectSchema, StrapInventoryMovementOrderByWithRelationInputObjectSchema.array()]).optional(), where: StrapInventoryMovementWhereInputObjectSchema.optional(), cursor: StrapInventoryMovementWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StrapInventoryMovementCountAggregateInputObjectSchema ]).optional(), _min: StrapInventoryMovementMinAggregateInputObjectSchema.optional(), _max: StrapInventoryMovementMaxAggregateInputObjectSchema.optional(), _avg: StrapInventoryMovementAvgAggregateInputObjectSchema.optional(), _sum: StrapInventoryMovementSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StrapInventoryMovementAggregateArgs>;

export const StrapInventoryMovementAggregateZodSchema = z.object({ orderBy: z.union([StrapInventoryMovementOrderByWithRelationInputObjectSchema, StrapInventoryMovementOrderByWithRelationInputObjectSchema.array()]).optional(), where: StrapInventoryMovementWhereInputObjectSchema.optional(), cursor: StrapInventoryMovementWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), StrapInventoryMovementCountAggregateInputObjectSchema ]).optional(), _min: StrapInventoryMovementMinAggregateInputObjectSchema.optional(), _max: StrapInventoryMovementMaxAggregateInputObjectSchema.optional(), _avg: StrapInventoryMovementAvgAggregateInputObjectSchema.optional(), _sum: StrapInventoryMovementSumAggregateInputObjectSchema.optional() }).strict();