import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ClaspVariantSpecOrderByWithRelationInputObjectSchema as ClaspVariantSpecOrderByWithRelationInputObjectSchema } from './objects/ClaspVariantSpecOrderByWithRelationInput.schema';
import { ClaspVariantSpecWhereInputObjectSchema as ClaspVariantSpecWhereInputObjectSchema } from './objects/ClaspVariantSpecWhereInput.schema';
import { ClaspVariantSpecWhereUniqueInputObjectSchema as ClaspVariantSpecWhereUniqueInputObjectSchema } from './objects/ClaspVariantSpecWhereUniqueInput.schema';
import { ClaspVariantSpecCountAggregateInputObjectSchema as ClaspVariantSpecCountAggregateInputObjectSchema } from './objects/ClaspVariantSpecCountAggregateInput.schema';
import { ClaspVariantSpecMinAggregateInputObjectSchema as ClaspVariantSpecMinAggregateInputObjectSchema } from './objects/ClaspVariantSpecMinAggregateInput.schema';
import { ClaspVariantSpecMaxAggregateInputObjectSchema as ClaspVariantSpecMaxAggregateInputObjectSchema } from './objects/ClaspVariantSpecMaxAggregateInput.schema';
import { ClaspVariantSpecAvgAggregateInputObjectSchema as ClaspVariantSpecAvgAggregateInputObjectSchema } from './objects/ClaspVariantSpecAvgAggregateInput.schema';
import { ClaspVariantSpecSumAggregateInputObjectSchema as ClaspVariantSpecSumAggregateInputObjectSchema } from './objects/ClaspVariantSpecSumAggregateInput.schema';

export const ClaspVariantSpecAggregateSchema: z.ZodType<Prisma.ClaspVariantSpecAggregateArgs> = z.object({ orderBy: z.union([ClaspVariantSpecOrderByWithRelationInputObjectSchema, ClaspVariantSpecOrderByWithRelationInputObjectSchema.array()]).optional(), where: ClaspVariantSpecWhereInputObjectSchema.optional(), cursor: ClaspVariantSpecWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ClaspVariantSpecCountAggregateInputObjectSchema ]).optional(), _min: ClaspVariantSpecMinAggregateInputObjectSchema.optional(), _max: ClaspVariantSpecMaxAggregateInputObjectSchema.optional(), _avg: ClaspVariantSpecAvgAggregateInputObjectSchema.optional(), _sum: ClaspVariantSpecSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ClaspVariantSpecAggregateArgs>;

export const ClaspVariantSpecAggregateZodSchema = z.object({ orderBy: z.union([ClaspVariantSpecOrderByWithRelationInputObjectSchema, ClaspVariantSpecOrderByWithRelationInputObjectSchema.array()]).optional(), where: ClaspVariantSpecWhereInputObjectSchema.optional(), cursor: ClaspVariantSpecWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ClaspVariantSpecCountAggregateInputObjectSchema ]).optional(), _min: ClaspVariantSpecMinAggregateInputObjectSchema.optional(), _max: ClaspVariantSpecMaxAggregateInputObjectSchema.optional(), _avg: ClaspVariantSpecAvgAggregateInputObjectSchema.optional(), _sum: ClaspVariantSpecSumAggregateInputObjectSchema.optional() }).strict();