import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProjectionRecordOrderByWithRelationInputObjectSchema as ProjectionRecordOrderByWithRelationInputObjectSchema } from './objects/ProjectionRecordOrderByWithRelationInput.schema';
import { ProjectionRecordWhereInputObjectSchema as ProjectionRecordWhereInputObjectSchema } from './objects/ProjectionRecordWhereInput.schema';
import { ProjectionRecordWhereUniqueInputObjectSchema as ProjectionRecordWhereUniqueInputObjectSchema } from './objects/ProjectionRecordWhereUniqueInput.schema';
import { ProjectionRecordCountAggregateInputObjectSchema as ProjectionRecordCountAggregateInputObjectSchema } from './objects/ProjectionRecordCountAggregateInput.schema';
import { ProjectionRecordMinAggregateInputObjectSchema as ProjectionRecordMinAggregateInputObjectSchema } from './objects/ProjectionRecordMinAggregateInput.schema';
import { ProjectionRecordMaxAggregateInputObjectSchema as ProjectionRecordMaxAggregateInputObjectSchema } from './objects/ProjectionRecordMaxAggregateInput.schema';
import { ProjectionRecordAvgAggregateInputObjectSchema as ProjectionRecordAvgAggregateInputObjectSchema } from './objects/ProjectionRecordAvgAggregateInput.schema';
import { ProjectionRecordSumAggregateInputObjectSchema as ProjectionRecordSumAggregateInputObjectSchema } from './objects/ProjectionRecordSumAggregateInput.schema';

export const ProjectionRecordAggregateSchema: z.ZodType<Prisma.ProjectionRecordAggregateArgs> = z.object({ orderBy: z.union([ProjectionRecordOrderByWithRelationInputObjectSchema, ProjectionRecordOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProjectionRecordWhereInputObjectSchema.optional(), cursor: ProjectionRecordWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProjectionRecordCountAggregateInputObjectSchema ]).optional(), _min: ProjectionRecordMinAggregateInputObjectSchema.optional(), _max: ProjectionRecordMaxAggregateInputObjectSchema.optional(), _avg: ProjectionRecordAvgAggregateInputObjectSchema.optional(), _sum: ProjectionRecordSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProjectionRecordAggregateArgs>;

export const ProjectionRecordAggregateZodSchema = z.object({ orderBy: z.union([ProjectionRecordOrderByWithRelationInputObjectSchema, ProjectionRecordOrderByWithRelationInputObjectSchema.array()]).optional(), where: ProjectionRecordWhereInputObjectSchema.optional(), cursor: ProjectionRecordWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ProjectionRecordCountAggregateInputObjectSchema ]).optional(), _min: ProjectionRecordMinAggregateInputObjectSchema.optional(), _max: ProjectionRecordMaxAggregateInputObjectSchema.optional(), _avg: ProjectionRecordAvgAggregateInputObjectSchema.optional(), _sum: ProjectionRecordSumAggregateInputObjectSchema.optional() }).strict();