import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WatchContentOrderByWithRelationInputObjectSchema as WatchContentOrderByWithRelationInputObjectSchema } from './objects/WatchContentOrderByWithRelationInput.schema';
import { WatchContentWhereInputObjectSchema as WatchContentWhereInputObjectSchema } from './objects/WatchContentWhereInput.schema';
import { WatchContentWhereUniqueInputObjectSchema as WatchContentWhereUniqueInputObjectSchema } from './objects/WatchContentWhereUniqueInput.schema';
import { WatchContentCountAggregateInputObjectSchema as WatchContentCountAggregateInputObjectSchema } from './objects/WatchContentCountAggregateInput.schema';
import { WatchContentMinAggregateInputObjectSchema as WatchContentMinAggregateInputObjectSchema } from './objects/WatchContentMinAggregateInput.schema';
import { WatchContentMaxAggregateInputObjectSchema as WatchContentMaxAggregateInputObjectSchema } from './objects/WatchContentMaxAggregateInput.schema';

export const WatchContentAggregateSchema: z.ZodType<Prisma.WatchContentAggregateArgs> = z.object({ orderBy: z.union([WatchContentOrderByWithRelationInputObjectSchema, WatchContentOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchContentWhereInputObjectSchema.optional(), cursor: WatchContentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchContentCountAggregateInputObjectSchema ]).optional(), _min: WatchContentMinAggregateInputObjectSchema.optional(), _max: WatchContentMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WatchContentAggregateArgs>;

export const WatchContentAggregateZodSchema = z.object({ orderBy: z.union([WatchContentOrderByWithRelationInputObjectSchema, WatchContentOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchContentWhereInputObjectSchema.optional(), cursor: WatchContentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchContentCountAggregateInputObjectSchema ]).optional(), _min: WatchContentMinAggregateInputObjectSchema.optional(), _max: WatchContentMaxAggregateInputObjectSchema.optional() }).strict();