import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WatchMediaOrderByWithRelationInputObjectSchema as WatchMediaOrderByWithRelationInputObjectSchema } from './objects/WatchMediaOrderByWithRelationInput.schema';
import { WatchMediaWhereInputObjectSchema as WatchMediaWhereInputObjectSchema } from './objects/WatchMediaWhereInput.schema';
import { WatchMediaWhereUniqueInputObjectSchema as WatchMediaWhereUniqueInputObjectSchema } from './objects/WatchMediaWhereUniqueInput.schema';
import { WatchMediaCountAggregateInputObjectSchema as WatchMediaCountAggregateInputObjectSchema } from './objects/WatchMediaCountAggregateInput.schema';
import { WatchMediaMinAggregateInputObjectSchema as WatchMediaMinAggregateInputObjectSchema } from './objects/WatchMediaMinAggregateInput.schema';
import { WatchMediaMaxAggregateInputObjectSchema as WatchMediaMaxAggregateInputObjectSchema } from './objects/WatchMediaMaxAggregateInput.schema';
import { WatchMediaAvgAggregateInputObjectSchema as WatchMediaAvgAggregateInputObjectSchema } from './objects/WatchMediaAvgAggregateInput.schema';
import { WatchMediaSumAggregateInputObjectSchema as WatchMediaSumAggregateInputObjectSchema } from './objects/WatchMediaSumAggregateInput.schema';

export const WatchMediaAggregateSchema: z.ZodType<Prisma.WatchMediaAggregateArgs> = z.object({ orderBy: z.union([WatchMediaOrderByWithRelationInputObjectSchema, WatchMediaOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchMediaWhereInputObjectSchema.optional(), cursor: WatchMediaWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchMediaCountAggregateInputObjectSchema ]).optional(), _min: WatchMediaMinAggregateInputObjectSchema.optional(), _max: WatchMediaMaxAggregateInputObjectSchema.optional(), _avg: WatchMediaAvgAggregateInputObjectSchema.optional(), _sum: WatchMediaSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WatchMediaAggregateArgs>;

export const WatchMediaAggregateZodSchema = z.object({ orderBy: z.union([WatchMediaOrderByWithRelationInputObjectSchema, WatchMediaOrderByWithRelationInputObjectSchema.array()]).optional(), where: WatchMediaWhereInputObjectSchema.optional(), cursor: WatchMediaWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), WatchMediaCountAggregateInputObjectSchema ]).optional(), _min: WatchMediaMinAggregateInputObjectSchema.optional(), _max: WatchMediaMaxAggregateInputObjectSchema.optional(), _avg: WatchMediaAvgAggregateInputObjectSchema.optional(), _sum: WatchMediaSumAggregateInputObjectSchema.optional() }).strict();