import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { acquisition_spec_jobOrderByWithRelationInputObjectSchema as acquisition_spec_jobOrderByWithRelationInputObjectSchema } from './objects/acquisition_spec_jobOrderByWithRelationInput.schema';
import { acquisition_spec_jobWhereInputObjectSchema as acquisition_spec_jobWhereInputObjectSchema } from './objects/acquisition_spec_jobWhereInput.schema';
import { acquisition_spec_jobWhereUniqueInputObjectSchema as acquisition_spec_jobWhereUniqueInputObjectSchema } from './objects/acquisition_spec_jobWhereUniqueInput.schema';
import { Acquisition_spec_jobCountAggregateInputObjectSchema as Acquisition_spec_jobCountAggregateInputObjectSchema } from './objects/Acquisition_spec_jobCountAggregateInput.schema';

export const acquisition_spec_jobCountSchema: z.ZodType<Prisma.acquisition_spec_jobCountArgs> = z.object({ orderBy: z.union([acquisition_spec_jobOrderByWithRelationInputObjectSchema, acquisition_spec_jobOrderByWithRelationInputObjectSchema.array()]).optional(), where: acquisition_spec_jobWhereInputObjectSchema.optional(), cursor: acquisition_spec_jobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.acquisition_spec_jobCountArgs>;

export const acquisition_spec_jobCountZodSchema = z.object({ orderBy: z.union([acquisition_spec_jobOrderByWithRelationInputObjectSchema, acquisition_spec_jobOrderByWithRelationInputObjectSchema.array()]).optional(), where: acquisition_spec_jobWhereInputObjectSchema.optional(), cursor: acquisition_spec_jobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional() }).strict();