import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TechnicalDetailCatalogWhereInputObjectSchema as TechnicalDetailCatalogWhereInputObjectSchema } from './objects/TechnicalDetailCatalogWhereInput.schema';
import { TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema as TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema } from './objects/TechnicalDetailCatalogOrderByWithAggregationInput.schema';
import { TechnicalDetailCatalogScalarWhereWithAggregatesInputObjectSchema as TechnicalDetailCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/TechnicalDetailCatalogScalarWhereWithAggregatesInput.schema';
import { TechnicalDetailCatalogScalarFieldEnumSchema } from './enums/TechnicalDetailCatalogScalarFieldEnum.schema';
import { TechnicalDetailCatalogCountAggregateInputObjectSchema as TechnicalDetailCatalogCountAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogCountAggregateInput.schema';
import { TechnicalDetailCatalogMinAggregateInputObjectSchema as TechnicalDetailCatalogMinAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogMinAggregateInput.schema';
import { TechnicalDetailCatalogMaxAggregateInputObjectSchema as TechnicalDetailCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogMaxAggregateInput.schema';
import { TechnicalDetailCatalogAvgAggregateInputObjectSchema as TechnicalDetailCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogAvgAggregateInput.schema';
import { TechnicalDetailCatalogSumAggregateInputObjectSchema as TechnicalDetailCatalogSumAggregateInputObjectSchema } from './objects/TechnicalDetailCatalogSumAggregateInput.schema';

export const TechnicalDetailCatalogGroupBySchema: z.ZodType<Prisma.TechnicalDetailCatalogGroupByArgs> = z.object({ where: TechnicalDetailCatalogWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema, TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalDetailCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalDetailCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalDetailCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalDetailCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalDetailCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalDetailCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalDetailCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TechnicalDetailCatalogGroupByArgs>;

export const TechnicalDetailCatalogGroupByZodSchema = z.object({ where: TechnicalDetailCatalogWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema, TechnicalDetailCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalDetailCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalDetailCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalDetailCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalDetailCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalDetailCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalDetailCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalDetailCatalogSumAggregateInputObjectSchema.optional() }).strict();