import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SystemJobRunLogWhereInputObjectSchema as SystemJobRunLogWhereInputObjectSchema } from './objects/SystemJobRunLogWhereInput.schema';
import { SystemJobRunLogOrderByWithAggregationInputObjectSchema as SystemJobRunLogOrderByWithAggregationInputObjectSchema } from './objects/SystemJobRunLogOrderByWithAggregationInput.schema';
import { SystemJobRunLogScalarWhereWithAggregatesInputObjectSchema as SystemJobRunLogScalarWhereWithAggregatesInputObjectSchema } from './objects/SystemJobRunLogScalarWhereWithAggregatesInput.schema';
import { SystemJobRunLogScalarFieldEnumSchema } from './enums/SystemJobRunLogScalarFieldEnum.schema';
import { SystemJobRunLogCountAggregateInputObjectSchema as SystemJobRunLogCountAggregateInputObjectSchema } from './objects/SystemJobRunLogCountAggregateInput.schema';
import { SystemJobRunLogMinAggregateInputObjectSchema as SystemJobRunLogMinAggregateInputObjectSchema } from './objects/SystemJobRunLogMinAggregateInput.schema';
import { SystemJobRunLogMaxAggregateInputObjectSchema as SystemJobRunLogMaxAggregateInputObjectSchema } from './objects/SystemJobRunLogMaxAggregateInput.schema';
import { SystemJobRunLogAvgAggregateInputObjectSchema as SystemJobRunLogAvgAggregateInputObjectSchema } from './objects/SystemJobRunLogAvgAggregateInput.schema';
import { SystemJobRunLogSumAggregateInputObjectSchema as SystemJobRunLogSumAggregateInputObjectSchema } from './objects/SystemJobRunLogSumAggregateInput.schema';

export const SystemJobRunLogGroupBySchema: z.ZodType<Prisma.SystemJobRunLogGroupByArgs> = z.object({ where: SystemJobRunLogWhereInputObjectSchema.optional(), orderBy: z.union([SystemJobRunLogOrderByWithAggregationInputObjectSchema, SystemJobRunLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SystemJobRunLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobRunLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), SystemJobRunLogCountAggregateInputObjectSchema ]).optional(), _min: SystemJobRunLogMinAggregateInputObjectSchema.optional(), _max: SystemJobRunLogMaxAggregateInputObjectSchema.optional(), _avg: SystemJobRunLogAvgAggregateInputObjectSchema.optional(), _sum: SystemJobRunLogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SystemJobRunLogGroupByArgs>;

export const SystemJobRunLogGroupByZodSchema = z.object({ where: SystemJobRunLogWhereInputObjectSchema.optional(), orderBy: z.union([SystemJobRunLogOrderByWithAggregationInputObjectSchema, SystemJobRunLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SystemJobRunLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobRunLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), SystemJobRunLogCountAggregateInputObjectSchema ]).optional(), _min: SystemJobRunLogMinAggregateInputObjectSchema.optional(), _max: SystemJobRunLogMaxAggregateInputObjectSchema.optional(), _avg: SystemJobRunLogAvgAggregateInputObjectSchema.optional(), _sum: SystemJobRunLogSumAggregateInputObjectSchema.optional() }).strict();