import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { IntegrationIngressReceiptWhereInputObjectSchema as IntegrationIngressReceiptWhereInputObjectSchema } from './objects/IntegrationIngressReceiptWhereInput.schema';
import { IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema as IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema } from './objects/IntegrationIngressReceiptOrderByWithAggregationInput.schema';
import { IntegrationIngressReceiptScalarWhereWithAggregatesInputObjectSchema as IntegrationIngressReceiptScalarWhereWithAggregatesInputObjectSchema } from './objects/IntegrationIngressReceiptScalarWhereWithAggregatesInput.schema';
import { IntegrationIngressReceiptScalarFieldEnumSchema } from './enums/IntegrationIngressReceiptScalarFieldEnum.schema';
import { IntegrationIngressReceiptCountAggregateInputObjectSchema as IntegrationIngressReceiptCountAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptCountAggregateInput.schema';
import { IntegrationIngressReceiptMinAggregateInputObjectSchema as IntegrationIngressReceiptMinAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptMinAggregateInput.schema';
import { IntegrationIngressReceiptMaxAggregateInputObjectSchema as IntegrationIngressReceiptMaxAggregateInputObjectSchema } from './objects/IntegrationIngressReceiptMaxAggregateInput.schema';

export const IntegrationIngressReceiptGroupBySchema: z.ZodType<Prisma.IntegrationIngressReceiptGroupByArgs> = z.object({ where: IntegrationIngressReceiptWhereInputObjectSchema.optional(), orderBy: z.union([IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema, IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema.array()]).optional(), having: IntegrationIngressReceiptScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(IntegrationIngressReceiptScalarFieldEnumSchema), _count: z.union([ z.literal(true), IntegrationIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: IntegrationIngressReceiptMinAggregateInputObjectSchema.optional(), _max: IntegrationIngressReceiptMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.IntegrationIngressReceiptGroupByArgs>;

export const IntegrationIngressReceiptGroupByZodSchema = z.object({ where: IntegrationIngressReceiptWhereInputObjectSchema.optional(), orderBy: z.union([IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema, IntegrationIngressReceiptOrderByWithAggregationInputObjectSchema.array()]).optional(), having: IntegrationIngressReceiptScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(IntegrationIngressReceiptScalarFieldEnumSchema), _count: z.union([ z.literal(true), IntegrationIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: IntegrationIngressReceiptMinAggregateInputObjectSchema.optional(), _max: IntegrationIngressReceiptMaxAggregateInputObjectSchema.optional() }).strict();