import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProjectionEventDeliveryWhereInputObjectSchema as ProjectionEventDeliveryWhereInputObjectSchema } from './objects/ProjectionEventDeliveryWhereInput.schema';
import { ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema as ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema } from './objects/ProjectionEventDeliveryOrderByWithAggregationInput.schema';
import { ProjectionEventDeliveryScalarWhereWithAggregatesInputObjectSchema as ProjectionEventDeliveryScalarWhereWithAggregatesInputObjectSchema } from './objects/ProjectionEventDeliveryScalarWhereWithAggregatesInput.schema';
import { ProjectionEventDeliveryScalarFieldEnumSchema } from './enums/ProjectionEventDeliveryScalarFieldEnum.schema';
import { ProjectionEventDeliveryCountAggregateInputObjectSchema as ProjectionEventDeliveryCountAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryCountAggregateInput.schema';
import { ProjectionEventDeliveryMinAggregateInputObjectSchema as ProjectionEventDeliveryMinAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryMinAggregateInput.schema';
import { ProjectionEventDeliveryMaxAggregateInputObjectSchema as ProjectionEventDeliveryMaxAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryMaxAggregateInput.schema';
import { ProjectionEventDeliveryAvgAggregateInputObjectSchema as ProjectionEventDeliveryAvgAggregateInputObjectSchema } from './objects/ProjectionEventDeliveryAvgAggregateInput.schema';
import { ProjectionEventDeliverySumAggregateInputObjectSchema as ProjectionEventDeliverySumAggregateInputObjectSchema } from './objects/ProjectionEventDeliverySumAggregateInput.schema';

export const ProjectionEventDeliveryGroupBySchema: z.ZodType<Prisma.ProjectionEventDeliveryGroupByArgs> = z.object({ where: ProjectionEventDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema, ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProjectionEventDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProjectionEventDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProjectionEventDeliveryCountAggregateInputObjectSchema ]).optional(), _min: ProjectionEventDeliveryMinAggregateInputObjectSchema.optional(), _max: ProjectionEventDeliveryMaxAggregateInputObjectSchema.optional(), _avg: ProjectionEventDeliveryAvgAggregateInputObjectSchema.optional(), _sum: ProjectionEventDeliverySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProjectionEventDeliveryGroupByArgs>;

export const ProjectionEventDeliveryGroupByZodSchema = z.object({ where: ProjectionEventDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema, ProjectionEventDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProjectionEventDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProjectionEventDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProjectionEventDeliveryCountAggregateInputObjectSchema ]).optional(), _min: ProjectionEventDeliveryMinAggregateInputObjectSchema.optional(), _max: ProjectionEventDeliveryMaxAggregateInputObjectSchema.optional(), _avg: ProjectionEventDeliveryAvgAggregateInputObjectSchema.optional(), _sum: ProjectionEventDeliverySumAggregateInputObjectSchema.optional() }).strict();