import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskTypeWhereInputObjectSchema as TaskTypeWhereInputObjectSchema } from './objects/TaskTypeWhereInput.schema';
import { TaskTypeOrderByWithAggregationInputObjectSchema as TaskTypeOrderByWithAggregationInputObjectSchema } from './objects/TaskTypeOrderByWithAggregationInput.schema';
import { TaskTypeScalarWhereWithAggregatesInputObjectSchema as TaskTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/TaskTypeScalarWhereWithAggregatesInput.schema';
import { TaskTypeScalarFieldEnumSchema } from './enums/TaskTypeScalarFieldEnum.schema';
import { TaskTypeCountAggregateInputObjectSchema as TaskTypeCountAggregateInputObjectSchema } from './objects/TaskTypeCountAggregateInput.schema';
import { TaskTypeMinAggregateInputObjectSchema as TaskTypeMinAggregateInputObjectSchema } from './objects/TaskTypeMinAggregateInput.schema';
import { TaskTypeMaxAggregateInputObjectSchema as TaskTypeMaxAggregateInputObjectSchema } from './objects/TaskTypeMaxAggregateInput.schema';
import { TaskTypeAvgAggregateInputObjectSchema as TaskTypeAvgAggregateInputObjectSchema } from './objects/TaskTypeAvgAggregateInput.schema';
import { TaskTypeSumAggregateInputObjectSchema as TaskTypeSumAggregateInputObjectSchema } from './objects/TaskTypeSumAggregateInput.schema';

export const TaskTypeGroupBySchema: z.ZodType<Prisma.TaskTypeGroupByArgs> = z.object({ where: TaskTypeWhereInputObjectSchema.optional(), orderBy: z.union([TaskTypeOrderByWithAggregationInputObjectSchema, TaskTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskTypeCountAggregateInputObjectSchema ]).optional(), _min: TaskTypeMinAggregateInputObjectSchema.optional(), _max: TaskTypeMaxAggregateInputObjectSchema.optional(), _avg: TaskTypeAvgAggregateInputObjectSchema.optional(), _sum: TaskTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskTypeGroupByArgs>;

export const TaskTypeGroupByZodSchema = z.object({ where: TaskTypeWhereInputObjectSchema.optional(), orderBy: z.union([TaskTypeOrderByWithAggregationInputObjectSchema, TaskTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskTypeCountAggregateInputObjectSchema ]).optional(), _min: TaskTypeMinAggregateInputObjectSchema.optional(), _max: TaskTypeMaxAggregateInputObjectSchema.optional(), _avg: TaskTypeAvgAggregateInputObjectSchema.optional(), _sum: TaskTypeSumAggregateInputObjectSchema.optional() }).strict();