import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowConditionWhereInputObjectSchema as WorkflowConditionWhereInputObjectSchema } from './objects/WorkflowConditionWhereInput.schema';
import { WorkflowConditionOrderByWithAggregationInputObjectSchema as WorkflowConditionOrderByWithAggregationInputObjectSchema } from './objects/WorkflowConditionOrderByWithAggregationInput.schema';
import { WorkflowConditionScalarWhereWithAggregatesInputObjectSchema as WorkflowConditionScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkflowConditionScalarWhereWithAggregatesInput.schema';
import { WorkflowConditionScalarFieldEnumSchema } from './enums/WorkflowConditionScalarFieldEnum.schema';
import { WorkflowConditionCountAggregateInputObjectSchema as WorkflowConditionCountAggregateInputObjectSchema } from './objects/WorkflowConditionCountAggregateInput.schema';
import { WorkflowConditionMinAggregateInputObjectSchema as WorkflowConditionMinAggregateInputObjectSchema } from './objects/WorkflowConditionMinAggregateInput.schema';
import { WorkflowConditionMaxAggregateInputObjectSchema as WorkflowConditionMaxAggregateInputObjectSchema } from './objects/WorkflowConditionMaxAggregateInput.schema';
import { WorkflowConditionAvgAggregateInputObjectSchema as WorkflowConditionAvgAggregateInputObjectSchema } from './objects/WorkflowConditionAvgAggregateInput.schema';
import { WorkflowConditionSumAggregateInputObjectSchema as WorkflowConditionSumAggregateInputObjectSchema } from './objects/WorkflowConditionSumAggregateInput.schema';

export const WorkflowConditionGroupBySchema: z.ZodType<Prisma.WorkflowConditionGroupByArgs> = z.object({ where: WorkflowConditionWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowConditionOrderByWithAggregationInputObjectSchema, WorkflowConditionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowConditionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowConditionScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowConditionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowConditionMinAggregateInputObjectSchema.optional(), _max: WorkflowConditionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowConditionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowConditionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowConditionGroupByArgs>;

export const WorkflowConditionGroupByZodSchema = z.object({ where: WorkflowConditionWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowConditionOrderByWithAggregationInputObjectSchema, WorkflowConditionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowConditionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowConditionScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowConditionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowConditionMinAggregateInputObjectSchema.optional(), _max: WorkflowConditionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowConditionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowConditionSumAggregateInputObjectSchema.optional() }).strict();