import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestItemWhereInputObjectSchema as PurchaseRequestItemWhereInputObjectSchema } from './objects/PurchaseRequestItemWhereInput.schema';
import { PurchaseRequestItemOrderByWithAggregationInputObjectSchema as PurchaseRequestItemOrderByWithAggregationInputObjectSchema } from './objects/PurchaseRequestItemOrderByWithAggregationInput.schema';
import { PurchaseRequestItemScalarWhereWithAggregatesInputObjectSchema as PurchaseRequestItemScalarWhereWithAggregatesInputObjectSchema } from './objects/PurchaseRequestItemScalarWhereWithAggregatesInput.schema';
import { PurchaseRequestItemScalarFieldEnumSchema } from './enums/PurchaseRequestItemScalarFieldEnum.schema';
import { PurchaseRequestItemCountAggregateInputObjectSchema as PurchaseRequestItemCountAggregateInputObjectSchema } from './objects/PurchaseRequestItemCountAggregateInput.schema';
import { PurchaseRequestItemMinAggregateInputObjectSchema as PurchaseRequestItemMinAggregateInputObjectSchema } from './objects/PurchaseRequestItemMinAggregateInput.schema';
import { PurchaseRequestItemMaxAggregateInputObjectSchema as PurchaseRequestItemMaxAggregateInputObjectSchema } from './objects/PurchaseRequestItemMaxAggregateInput.schema';
import { PurchaseRequestItemAvgAggregateInputObjectSchema as PurchaseRequestItemAvgAggregateInputObjectSchema } from './objects/PurchaseRequestItemAvgAggregateInput.schema';
import { PurchaseRequestItemSumAggregateInputObjectSchema as PurchaseRequestItemSumAggregateInputObjectSchema } from './objects/PurchaseRequestItemSumAggregateInput.schema';

export const PurchaseRequestItemGroupBySchema: z.ZodType<Prisma.PurchaseRequestItemGroupByArgs> = z.object({ where: PurchaseRequestItemWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestItemOrderByWithAggregationInputObjectSchema, PurchaseRequestItemOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestItemScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestItemScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestItemCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestItemMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestItemMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestItemAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestItemSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestItemGroupByArgs>;

export const PurchaseRequestItemGroupByZodSchema = z.object({ where: PurchaseRequestItemWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestItemOrderByWithAggregationInputObjectSchema, PurchaseRequestItemOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestItemScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestItemScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestItemCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestItemMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestItemMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestItemAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestItemSumAggregateInputObjectSchema.optional() }).strict();