import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationChannelDeliveryWhereInputObjectSchema as NotificationChannelDeliveryWhereInputObjectSchema } from './objects/NotificationChannelDeliveryWhereInput.schema';
import { NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema as NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema } from './objects/NotificationChannelDeliveryOrderByWithAggregationInput.schema';
import { NotificationChannelDeliveryScalarWhereWithAggregatesInputObjectSchema as NotificationChannelDeliveryScalarWhereWithAggregatesInputObjectSchema } from './objects/NotificationChannelDeliveryScalarWhereWithAggregatesInput.schema';
import { NotificationChannelDeliveryScalarFieldEnumSchema } from './enums/NotificationChannelDeliveryScalarFieldEnum.schema';
import { NotificationChannelDeliveryCountAggregateInputObjectSchema as NotificationChannelDeliveryCountAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryCountAggregateInput.schema';
import { NotificationChannelDeliveryMinAggregateInputObjectSchema as NotificationChannelDeliveryMinAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryMinAggregateInput.schema';
import { NotificationChannelDeliveryMaxAggregateInputObjectSchema as NotificationChannelDeliveryMaxAggregateInputObjectSchema } from './objects/NotificationChannelDeliveryMaxAggregateInput.schema';

export const NotificationChannelDeliveryGroupBySchema: z.ZodType<Prisma.NotificationChannelDeliveryGroupByArgs> = z.object({ where: NotificationChannelDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema, NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationChannelDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationChannelDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationChannelDeliveryCountAggregateInputObjectSchema ]).optional(), _min: NotificationChannelDeliveryMinAggregateInputObjectSchema.optional(), _max: NotificationChannelDeliveryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationChannelDeliveryGroupByArgs>;

export const NotificationChannelDeliveryGroupByZodSchema = z.object({ where: NotificationChannelDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema, NotificationChannelDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationChannelDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationChannelDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationChannelDeliveryCountAggregateInputObjectSchema ]).optional(), _min: NotificationChannelDeliveryMinAggregateInputObjectSchema.optional(), _max: NotificationChannelDeliveryMaxAggregateInputObjectSchema.optional() }).strict();