import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProductPostTargetWhereInputObjectSchema as ProductPostTargetWhereInputObjectSchema } from './objects/ProductPostTargetWhereInput.schema';
import { ProductPostTargetOrderByWithAggregationInputObjectSchema as ProductPostTargetOrderByWithAggregationInputObjectSchema } from './objects/ProductPostTargetOrderByWithAggregationInput.schema';
import { ProductPostTargetScalarWhereWithAggregatesInputObjectSchema as ProductPostTargetScalarWhereWithAggregatesInputObjectSchema } from './objects/ProductPostTargetScalarWhereWithAggregatesInput.schema';
import { ProductPostTargetScalarFieldEnumSchema } from './enums/ProductPostTargetScalarFieldEnum.schema';
import { ProductPostTargetCountAggregateInputObjectSchema as ProductPostTargetCountAggregateInputObjectSchema } from './objects/ProductPostTargetCountAggregateInput.schema';
import { ProductPostTargetMinAggregateInputObjectSchema as ProductPostTargetMinAggregateInputObjectSchema } from './objects/ProductPostTargetMinAggregateInput.schema';
import { ProductPostTargetMaxAggregateInputObjectSchema as ProductPostTargetMaxAggregateInputObjectSchema } from './objects/ProductPostTargetMaxAggregateInput.schema';

export const ProductPostTargetGroupBySchema: z.ZodType<Prisma.ProductPostTargetGroupByArgs> = z.object({ where: ProductPostTargetWhereInputObjectSchema.optional(), orderBy: z.union([ProductPostTargetOrderByWithAggregationInputObjectSchema, ProductPostTargetOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProductPostTargetScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductPostTargetScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProductPostTargetCountAggregateInputObjectSchema ]).optional(), _min: ProductPostTargetMinAggregateInputObjectSchema.optional(), _max: ProductPostTargetMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProductPostTargetGroupByArgs>;

export const ProductPostTargetGroupByZodSchema = z.object({ where: ProductPostTargetWhereInputObjectSchema.optional(), orderBy: z.union([ProductPostTargetOrderByWithAggregationInputObjectSchema, ProductPostTargetOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProductPostTargetScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProductPostTargetScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProductPostTargetCountAggregateInputObjectSchema ]).optional(), _min: ProductPostTargetMinAggregateInputObjectSchema.optional(), _max: ProductPostTargetMaxAggregateInputObjectSchema.optional() }).strict();