import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ProjectionRecordWhereInputObjectSchema as ProjectionRecordWhereInputObjectSchema } from './objects/ProjectionRecordWhereInput.schema';
import { ProjectionRecordOrderByWithAggregationInputObjectSchema as ProjectionRecordOrderByWithAggregationInputObjectSchema } from './objects/ProjectionRecordOrderByWithAggregationInput.schema';
import { ProjectionRecordScalarWhereWithAggregatesInputObjectSchema as ProjectionRecordScalarWhereWithAggregatesInputObjectSchema } from './objects/ProjectionRecordScalarWhereWithAggregatesInput.schema';
import { ProjectionRecordScalarFieldEnumSchema } from './enums/ProjectionRecordScalarFieldEnum.schema';
import { ProjectionRecordCountAggregateInputObjectSchema as ProjectionRecordCountAggregateInputObjectSchema } from './objects/ProjectionRecordCountAggregateInput.schema';
import { ProjectionRecordMinAggregateInputObjectSchema as ProjectionRecordMinAggregateInputObjectSchema } from './objects/ProjectionRecordMinAggregateInput.schema';
import { ProjectionRecordMaxAggregateInputObjectSchema as ProjectionRecordMaxAggregateInputObjectSchema } from './objects/ProjectionRecordMaxAggregateInput.schema';
import { ProjectionRecordAvgAggregateInputObjectSchema as ProjectionRecordAvgAggregateInputObjectSchema } from './objects/ProjectionRecordAvgAggregateInput.schema';
import { ProjectionRecordSumAggregateInputObjectSchema as ProjectionRecordSumAggregateInputObjectSchema } from './objects/ProjectionRecordSumAggregateInput.schema';

export const ProjectionRecordGroupBySchema: z.ZodType<Prisma.ProjectionRecordGroupByArgs> = z.object({ where: ProjectionRecordWhereInputObjectSchema.optional(), orderBy: z.union([ProjectionRecordOrderByWithAggregationInputObjectSchema, ProjectionRecordOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProjectionRecordScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProjectionRecordScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProjectionRecordCountAggregateInputObjectSchema ]).optional(), _min: ProjectionRecordMinAggregateInputObjectSchema.optional(), _max: ProjectionRecordMaxAggregateInputObjectSchema.optional(), _avg: ProjectionRecordAvgAggregateInputObjectSchema.optional(), _sum: ProjectionRecordSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ProjectionRecordGroupByArgs>;

export const ProjectionRecordGroupByZodSchema = z.object({ where: ProjectionRecordWhereInputObjectSchema.optional(), orderBy: z.union([ProjectionRecordOrderByWithAggregationInputObjectSchema, ProjectionRecordOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ProjectionRecordScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ProjectionRecordScalarFieldEnumSchema), _count: z.union([ z.literal(true), ProjectionRecordCountAggregateInputObjectSchema ]).optional(), _min: ProjectionRecordMinAggregateInputObjectSchema.optional(), _max: ProjectionRecordMaxAggregateInputObjectSchema.optional(), _avg: ProjectionRecordAvgAggregateInputObjectSchema.optional(), _sum: ProjectionRecordSumAggregateInputObjectSchema.optional() }).strict();