import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StrapInventoryMovementWhereInputObjectSchema as StrapInventoryMovementWhereInputObjectSchema } from './objects/StrapInventoryMovementWhereInput.schema';
import { StrapInventoryMovementOrderByWithAggregationInputObjectSchema as StrapInventoryMovementOrderByWithAggregationInputObjectSchema } from './objects/StrapInventoryMovementOrderByWithAggregationInput.schema';
import { StrapInventoryMovementScalarWhereWithAggregatesInputObjectSchema as StrapInventoryMovementScalarWhereWithAggregatesInputObjectSchema } from './objects/StrapInventoryMovementScalarWhereWithAggregatesInput.schema';
import { StrapInventoryMovementScalarFieldEnumSchema } from './enums/StrapInventoryMovementScalarFieldEnum.schema';
import { StrapInventoryMovementCountAggregateInputObjectSchema as StrapInventoryMovementCountAggregateInputObjectSchema } from './objects/StrapInventoryMovementCountAggregateInput.schema';
import { StrapInventoryMovementMinAggregateInputObjectSchema as StrapInventoryMovementMinAggregateInputObjectSchema } from './objects/StrapInventoryMovementMinAggregateInput.schema';
import { StrapInventoryMovementMaxAggregateInputObjectSchema as StrapInventoryMovementMaxAggregateInputObjectSchema } from './objects/StrapInventoryMovementMaxAggregateInput.schema';
import { StrapInventoryMovementAvgAggregateInputObjectSchema as StrapInventoryMovementAvgAggregateInputObjectSchema } from './objects/StrapInventoryMovementAvgAggregateInput.schema';
import { StrapInventoryMovementSumAggregateInputObjectSchema as StrapInventoryMovementSumAggregateInputObjectSchema } from './objects/StrapInventoryMovementSumAggregateInput.schema';

export const StrapInventoryMovementGroupBySchema: z.ZodType<Prisma.StrapInventoryMovementGroupByArgs> = z.object({ where: StrapInventoryMovementWhereInputObjectSchema.optional(), orderBy: z.union([StrapInventoryMovementOrderByWithAggregationInputObjectSchema, StrapInventoryMovementOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StrapInventoryMovementScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StrapInventoryMovementScalarFieldEnumSchema), _count: z.union([ z.literal(true), StrapInventoryMovementCountAggregateInputObjectSchema ]).optional(), _min: StrapInventoryMovementMinAggregateInputObjectSchema.optional(), _max: StrapInventoryMovementMaxAggregateInputObjectSchema.optional(), _avg: StrapInventoryMovementAvgAggregateInputObjectSchema.optional(), _sum: StrapInventoryMovementSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StrapInventoryMovementGroupByArgs>;

export const StrapInventoryMovementGroupByZodSchema = z.object({ where: StrapInventoryMovementWhereInputObjectSchema.optional(), orderBy: z.union([StrapInventoryMovementOrderByWithAggregationInputObjectSchema, StrapInventoryMovementOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StrapInventoryMovementScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StrapInventoryMovementScalarFieldEnumSchema), _count: z.union([ z.literal(true), StrapInventoryMovementCountAggregateInputObjectSchema ]).optional(), _min: StrapInventoryMovementMinAggregateInputObjectSchema.optional(), _max: StrapInventoryMovementMaxAggregateInputObjectSchema.optional(), _avg: StrapInventoryMovementAvgAggregateInputObjectSchema.optional(), _sum: StrapInventoryMovementSumAggregateInputObjectSchema.optional() }).strict();