import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskItemChecklistWhereInputObjectSchema as TaskItemChecklistWhereInputObjectSchema } from './objects/TaskItemChecklistWhereInput.schema';
import { TaskItemChecklistOrderByWithAggregationInputObjectSchema as TaskItemChecklistOrderByWithAggregationInputObjectSchema } from './objects/TaskItemChecklistOrderByWithAggregationInput.schema';
import { TaskItemChecklistScalarWhereWithAggregatesInputObjectSchema as TaskItemChecklistScalarWhereWithAggregatesInputObjectSchema } from './objects/TaskItemChecklistScalarWhereWithAggregatesInput.schema';
import { TaskItemChecklistScalarFieldEnumSchema } from './enums/TaskItemChecklistScalarFieldEnum.schema';
import { TaskItemChecklistCountAggregateInputObjectSchema as TaskItemChecklistCountAggregateInputObjectSchema } from './objects/TaskItemChecklistCountAggregateInput.schema';
import { TaskItemChecklistMinAggregateInputObjectSchema as TaskItemChecklistMinAggregateInputObjectSchema } from './objects/TaskItemChecklistMinAggregateInput.schema';
import { TaskItemChecklistMaxAggregateInputObjectSchema as TaskItemChecklistMaxAggregateInputObjectSchema } from './objects/TaskItemChecklistMaxAggregateInput.schema';
import { TaskItemChecklistAvgAggregateInputObjectSchema as TaskItemChecklistAvgAggregateInputObjectSchema } from './objects/TaskItemChecklistAvgAggregateInput.schema';
import { TaskItemChecklistSumAggregateInputObjectSchema as TaskItemChecklistSumAggregateInputObjectSchema } from './objects/TaskItemChecklistSumAggregateInput.schema';

export const TaskItemChecklistGroupBySchema: z.ZodType<Prisma.TaskItemChecklistGroupByArgs> = z.object({ where: TaskItemChecklistWhereInputObjectSchema.optional(), orderBy: z.union([TaskItemChecklistOrderByWithAggregationInputObjectSchema, TaskItemChecklistOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskItemChecklistScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskItemChecklistScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskItemChecklistCountAggregateInputObjectSchema ]).optional(), _min: TaskItemChecklistMinAggregateInputObjectSchema.optional(), _max: TaskItemChecklistMaxAggregateInputObjectSchema.optional(), _avg: TaskItemChecklistAvgAggregateInputObjectSchema.optional(), _sum: TaskItemChecklistSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskItemChecklistGroupByArgs>;

export const TaskItemChecklistGroupByZodSchema = z.object({ where: TaskItemChecklistWhereInputObjectSchema.optional(), orderBy: z.union([TaskItemChecklistOrderByWithAggregationInputObjectSchema, TaskItemChecklistOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskItemChecklistScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskItemChecklistScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskItemChecklistCountAggregateInputObjectSchema ]).optional(), _min: TaskItemChecklistMinAggregateInputObjectSchema.optional(), _max: TaskItemChecklistMaxAggregateInputObjectSchema.optional(), _avg: TaskItemChecklistAvgAggregateInputObjectSchema.optional(), _sum: TaskItemChecklistSumAggregateInputObjectSchema.optional() }).strict();