import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowExecutionEventWhereInputObjectSchema as WorkflowExecutionEventWhereInputObjectSchema } from './objects/WorkflowExecutionEventWhereInput.schema';
import { WorkflowExecutionEventOrderByWithAggregationInputObjectSchema as WorkflowExecutionEventOrderByWithAggregationInputObjectSchema } from './objects/WorkflowExecutionEventOrderByWithAggregationInput.schema';
import { WorkflowExecutionEventScalarWhereWithAggregatesInputObjectSchema as WorkflowExecutionEventScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkflowExecutionEventScalarWhereWithAggregatesInput.schema';
import { WorkflowExecutionEventScalarFieldEnumSchema } from './enums/WorkflowExecutionEventScalarFieldEnum.schema';
import { WorkflowExecutionEventCountAggregateInputObjectSchema as WorkflowExecutionEventCountAggregateInputObjectSchema } from './objects/WorkflowExecutionEventCountAggregateInput.schema';
import { WorkflowExecutionEventMinAggregateInputObjectSchema as WorkflowExecutionEventMinAggregateInputObjectSchema } from './objects/WorkflowExecutionEventMinAggregateInput.schema';
import { WorkflowExecutionEventMaxAggregateInputObjectSchema as WorkflowExecutionEventMaxAggregateInputObjectSchema } from './objects/WorkflowExecutionEventMaxAggregateInput.schema';

export const WorkflowExecutionEventGroupBySchema: z.ZodType<Prisma.WorkflowExecutionEventGroupByArgs> = z.object({ where: WorkflowExecutionEventWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowExecutionEventOrderByWithAggregationInputObjectSchema, WorkflowExecutionEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowExecutionEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowExecutionEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowExecutionEventCountAggregateInputObjectSchema ]).optional(), _min: WorkflowExecutionEventMinAggregateInputObjectSchema.optional(), _max: WorkflowExecutionEventMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowExecutionEventGroupByArgs>;

export const WorkflowExecutionEventGroupByZodSchema = z.object({ where: WorkflowExecutionEventWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowExecutionEventOrderByWithAggregationInputObjectSchema, WorkflowExecutionEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowExecutionEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowExecutionEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowExecutionEventCountAggregateInputObjectSchema ]).optional(), _min: WorkflowExecutionEventMinAggregateInputObjectSchema.optional(), _max: WorkflowExecutionEventMaxAggregateInputObjectSchema.optional() }).strict();