import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationDispatchWhereInputObjectSchema as NotificationDispatchWhereInputObjectSchema } from './objects/NotificationDispatchWhereInput.schema';
import { NotificationDispatchOrderByWithAggregationInputObjectSchema as NotificationDispatchOrderByWithAggregationInputObjectSchema } from './objects/NotificationDispatchOrderByWithAggregationInput.schema';
import { NotificationDispatchScalarWhereWithAggregatesInputObjectSchema as NotificationDispatchScalarWhereWithAggregatesInputObjectSchema } from './objects/NotificationDispatchScalarWhereWithAggregatesInput.schema';
import { NotificationDispatchScalarFieldEnumSchema } from './enums/NotificationDispatchScalarFieldEnum.schema';
import { NotificationDispatchCountAggregateInputObjectSchema as NotificationDispatchCountAggregateInputObjectSchema } from './objects/NotificationDispatchCountAggregateInput.schema';
import { NotificationDispatchMinAggregateInputObjectSchema as NotificationDispatchMinAggregateInputObjectSchema } from './objects/NotificationDispatchMinAggregateInput.schema';
import { NotificationDispatchMaxAggregateInputObjectSchema as NotificationDispatchMaxAggregateInputObjectSchema } from './objects/NotificationDispatchMaxAggregateInput.schema';

export const NotificationDispatchGroupBySchema: z.ZodType<Prisma.NotificationDispatchGroupByArgs> = z.object({ where: NotificationDispatchWhereInputObjectSchema.optional(), orderBy: z.union([NotificationDispatchOrderByWithAggregationInputObjectSchema, NotificationDispatchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationDispatchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationDispatchScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationDispatchCountAggregateInputObjectSchema ]).optional(), _min: NotificationDispatchMinAggregateInputObjectSchema.optional(), _max: NotificationDispatchMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationDispatchGroupByArgs>;

export const NotificationDispatchGroupByZodSchema = z.object({ where: NotificationDispatchWhereInputObjectSchema.optional(), orderBy: z.union([NotificationDispatchOrderByWithAggregationInputObjectSchema, NotificationDispatchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationDispatchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationDispatchScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationDispatchCountAggregateInputObjectSchema ]).optional(), _min: NotificationDispatchMinAggregateInputObjectSchema.optional(), _max: NotificationDispatchMaxAggregateInputObjectSchema.optional() }).strict();