import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MaintenanceRecordWhereInputObjectSchema as MaintenanceRecordWhereInputObjectSchema } from './objects/MaintenanceRecordWhereInput.schema';
import { MaintenanceRecordOrderByWithAggregationInputObjectSchema as MaintenanceRecordOrderByWithAggregationInputObjectSchema } from './objects/MaintenanceRecordOrderByWithAggregationInput.schema';
import { MaintenanceRecordScalarWhereWithAggregatesInputObjectSchema as MaintenanceRecordScalarWhereWithAggregatesInputObjectSchema } from './objects/MaintenanceRecordScalarWhereWithAggregatesInput.schema';
import { MaintenanceRecordScalarFieldEnumSchema } from './enums/MaintenanceRecordScalarFieldEnum.schema';
import { MaintenanceRecordCountAggregateInputObjectSchema as MaintenanceRecordCountAggregateInputObjectSchema } from './objects/MaintenanceRecordCountAggregateInput.schema';
import { MaintenanceRecordMinAggregateInputObjectSchema as MaintenanceRecordMinAggregateInputObjectSchema } from './objects/MaintenanceRecordMinAggregateInput.schema';
import { MaintenanceRecordMaxAggregateInputObjectSchema as MaintenanceRecordMaxAggregateInputObjectSchema } from './objects/MaintenanceRecordMaxAggregateInput.schema';
import { MaintenanceRecordAvgAggregateInputObjectSchema as MaintenanceRecordAvgAggregateInputObjectSchema } from './objects/MaintenanceRecordAvgAggregateInput.schema';
import { MaintenanceRecordSumAggregateInputObjectSchema as MaintenanceRecordSumAggregateInputObjectSchema } from './objects/MaintenanceRecordSumAggregateInput.schema';

export const MaintenanceRecordGroupBySchema: z.ZodType<Prisma.MaintenanceRecordGroupByArgs> = z.object({ where: MaintenanceRecordWhereInputObjectSchema.optional(), orderBy: z.union([MaintenanceRecordOrderByWithAggregationInputObjectSchema, MaintenanceRecordOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MaintenanceRecordScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MaintenanceRecordScalarFieldEnumSchema), _count: z.union([ z.literal(true), MaintenanceRecordCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceRecordMinAggregateInputObjectSchema.optional(), _max: MaintenanceRecordMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceRecordAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceRecordSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MaintenanceRecordGroupByArgs>;

export const MaintenanceRecordGroupByZodSchema = z.object({ where: MaintenanceRecordWhereInputObjectSchema.optional(), orderBy: z.union([MaintenanceRecordOrderByWithAggregationInputObjectSchema, MaintenanceRecordOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MaintenanceRecordScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MaintenanceRecordScalarFieldEnumSchema), _count: z.union([ z.literal(true), MaintenanceRecordCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceRecordMinAggregateInputObjectSchema.optional(), _max: MaintenanceRecordMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceRecordAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceRecordSumAggregateInputObjectSchema.optional() }).strict();