import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskChecklistItemWhereInputObjectSchema as TaskChecklistItemWhereInputObjectSchema } from './objects/TaskChecklistItemWhereInput.schema';
import { TaskChecklistItemOrderByWithAggregationInputObjectSchema as TaskChecklistItemOrderByWithAggregationInputObjectSchema } from './objects/TaskChecklistItemOrderByWithAggregationInput.schema';
import { TaskChecklistItemScalarWhereWithAggregatesInputObjectSchema as TaskChecklistItemScalarWhereWithAggregatesInputObjectSchema } from './objects/TaskChecklistItemScalarWhereWithAggregatesInput.schema';
import { TaskChecklistItemScalarFieldEnumSchema } from './enums/TaskChecklistItemScalarFieldEnum.schema';
import { TaskChecklistItemCountAggregateInputObjectSchema as TaskChecklistItemCountAggregateInputObjectSchema } from './objects/TaskChecklistItemCountAggregateInput.schema';
import { TaskChecklistItemMinAggregateInputObjectSchema as TaskChecklistItemMinAggregateInputObjectSchema } from './objects/TaskChecklistItemMinAggregateInput.schema';
import { TaskChecklistItemMaxAggregateInputObjectSchema as TaskChecklistItemMaxAggregateInputObjectSchema } from './objects/TaskChecklistItemMaxAggregateInput.schema';
import { TaskChecklistItemAvgAggregateInputObjectSchema as TaskChecklistItemAvgAggregateInputObjectSchema } from './objects/TaskChecklistItemAvgAggregateInput.schema';
import { TaskChecklistItemSumAggregateInputObjectSchema as TaskChecklistItemSumAggregateInputObjectSchema } from './objects/TaskChecklistItemSumAggregateInput.schema';

export const TaskChecklistItemGroupBySchema: z.ZodType<Prisma.TaskChecklistItemGroupByArgs> = z.object({ where: TaskChecklistItemWhereInputObjectSchema.optional(), orderBy: z.union([TaskChecklistItemOrderByWithAggregationInputObjectSchema, TaskChecklistItemOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskChecklistItemScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskChecklistItemScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskChecklistItemCountAggregateInputObjectSchema ]).optional(), _min: TaskChecklistItemMinAggregateInputObjectSchema.optional(), _max: TaskChecklistItemMaxAggregateInputObjectSchema.optional(), _avg: TaskChecklistItemAvgAggregateInputObjectSchema.optional(), _sum: TaskChecklistItemSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskChecklistItemGroupByArgs>;

export const TaskChecklistItemGroupByZodSchema = z.object({ where: TaskChecklistItemWhereInputObjectSchema.optional(), orderBy: z.union([TaskChecklistItemOrderByWithAggregationInputObjectSchema, TaskChecklistItemOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskChecklistItemScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskChecklistItemScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskChecklistItemCountAggregateInputObjectSchema ]).optional(), _min: TaskChecklistItemMinAggregateInputObjectSchema.optional(), _max: TaskChecklistItemMaxAggregateInputObjectSchema.optional(), _avg: TaskChecklistItemAvgAggregateInputObjectSchema.optional(), _sum: TaskChecklistItemSumAggregateInputObjectSchema.optional() }).strict();