import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SystemJobControlWhereInputObjectSchema as SystemJobControlWhereInputObjectSchema } from './objects/SystemJobControlWhereInput.schema';
import { SystemJobControlOrderByWithAggregationInputObjectSchema as SystemJobControlOrderByWithAggregationInputObjectSchema } from './objects/SystemJobControlOrderByWithAggregationInput.schema';
import { SystemJobControlScalarWhereWithAggregatesInputObjectSchema as SystemJobControlScalarWhereWithAggregatesInputObjectSchema } from './objects/SystemJobControlScalarWhereWithAggregatesInput.schema';
import { SystemJobControlScalarFieldEnumSchema } from './enums/SystemJobControlScalarFieldEnum.schema';
import { SystemJobControlCountAggregateInputObjectSchema as SystemJobControlCountAggregateInputObjectSchema } from './objects/SystemJobControlCountAggregateInput.schema';
import { SystemJobControlMinAggregateInputObjectSchema as SystemJobControlMinAggregateInputObjectSchema } from './objects/SystemJobControlMinAggregateInput.schema';
import { SystemJobControlMaxAggregateInputObjectSchema as SystemJobControlMaxAggregateInputObjectSchema } from './objects/SystemJobControlMaxAggregateInput.schema';
import { SystemJobControlAvgAggregateInputObjectSchema as SystemJobControlAvgAggregateInputObjectSchema } from './objects/SystemJobControlAvgAggregateInput.schema';
import { SystemJobControlSumAggregateInputObjectSchema as SystemJobControlSumAggregateInputObjectSchema } from './objects/SystemJobControlSumAggregateInput.schema';

export const SystemJobControlGroupBySchema: z.ZodType<Prisma.SystemJobControlGroupByArgs> = z.object({ where: SystemJobControlWhereInputObjectSchema.optional(), orderBy: z.union([SystemJobControlOrderByWithAggregationInputObjectSchema, SystemJobControlOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SystemJobControlScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobControlScalarFieldEnumSchema), _count: z.union([ z.literal(true), SystemJobControlCountAggregateInputObjectSchema ]).optional(), _min: SystemJobControlMinAggregateInputObjectSchema.optional(), _max: SystemJobControlMaxAggregateInputObjectSchema.optional(), _avg: SystemJobControlAvgAggregateInputObjectSchema.optional(), _sum: SystemJobControlSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SystemJobControlGroupByArgs>;

export const SystemJobControlGroupByZodSchema = z.object({ where: SystemJobControlWhereInputObjectSchema.optional(), orderBy: z.union([SystemJobControlOrderByWithAggregationInputObjectSchema, SystemJobControlOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SystemJobControlScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobControlScalarFieldEnumSchema), _count: z.union([ z.literal(true), SystemJobControlCountAggregateInputObjectSchema ]).optional(), _min: SystemJobControlMinAggregateInputObjectSchema.optional(), _max: SystemJobControlMaxAggregateInputObjectSchema.optional(), _avg: SystemJobControlAvgAggregateInputObjectSchema.optional(), _sum: SystemJobControlSumAggregateInputObjectSchema.optional() }).strict();