import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StrapCatalogOptionWhereInputObjectSchema as StrapCatalogOptionWhereInputObjectSchema } from './objects/StrapCatalogOptionWhereInput.schema';
import { StrapCatalogOptionOrderByWithAggregationInputObjectSchema as StrapCatalogOptionOrderByWithAggregationInputObjectSchema } from './objects/StrapCatalogOptionOrderByWithAggregationInput.schema';
import { StrapCatalogOptionScalarWhereWithAggregatesInputObjectSchema as StrapCatalogOptionScalarWhereWithAggregatesInputObjectSchema } from './objects/StrapCatalogOptionScalarWhereWithAggregatesInput.schema';
import { StrapCatalogOptionScalarFieldEnumSchema } from './enums/StrapCatalogOptionScalarFieldEnum.schema';
import { StrapCatalogOptionCountAggregateInputObjectSchema as StrapCatalogOptionCountAggregateInputObjectSchema } from './objects/StrapCatalogOptionCountAggregateInput.schema';
import { StrapCatalogOptionMinAggregateInputObjectSchema as StrapCatalogOptionMinAggregateInputObjectSchema } from './objects/StrapCatalogOptionMinAggregateInput.schema';
import { StrapCatalogOptionMaxAggregateInputObjectSchema as StrapCatalogOptionMaxAggregateInputObjectSchema } from './objects/StrapCatalogOptionMaxAggregateInput.schema';
import { StrapCatalogOptionAvgAggregateInputObjectSchema as StrapCatalogOptionAvgAggregateInputObjectSchema } from './objects/StrapCatalogOptionAvgAggregateInput.schema';
import { StrapCatalogOptionSumAggregateInputObjectSchema as StrapCatalogOptionSumAggregateInputObjectSchema } from './objects/StrapCatalogOptionSumAggregateInput.schema';

export const StrapCatalogOptionGroupBySchema: z.ZodType<Prisma.StrapCatalogOptionGroupByArgs> = z.object({ where: StrapCatalogOptionWhereInputObjectSchema.optional(), orderBy: z.union([StrapCatalogOptionOrderByWithAggregationInputObjectSchema, StrapCatalogOptionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StrapCatalogOptionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StrapCatalogOptionScalarFieldEnumSchema), _count: z.union([ z.literal(true), StrapCatalogOptionCountAggregateInputObjectSchema ]).optional(), _min: StrapCatalogOptionMinAggregateInputObjectSchema.optional(), _max: StrapCatalogOptionMaxAggregateInputObjectSchema.optional(), _avg: StrapCatalogOptionAvgAggregateInputObjectSchema.optional(), _sum: StrapCatalogOptionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StrapCatalogOptionGroupByArgs>;

export const StrapCatalogOptionGroupByZodSchema = z.object({ where: StrapCatalogOptionWhereInputObjectSchema.optional(), orderBy: z.union([StrapCatalogOptionOrderByWithAggregationInputObjectSchema, StrapCatalogOptionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StrapCatalogOptionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StrapCatalogOptionScalarFieldEnumSchema), _count: z.union([ z.literal(true), StrapCatalogOptionCountAggregateInputObjectSchema ]).optional(), _min: StrapCatalogOptionMinAggregateInputObjectSchema.optional(), _max: StrapCatalogOptionMaxAggregateInputObjectSchema.optional(), _avg: StrapCatalogOptionAvgAggregateInputObjectSchema.optional(), _sum: StrapCatalogOptionSumAggregateInputObjectSchema.optional() }).strict();