import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MediaOperationWhereInputObjectSchema as MediaOperationWhereInputObjectSchema } from './objects/MediaOperationWhereInput.schema';
import { MediaOperationOrderByWithAggregationInputObjectSchema as MediaOperationOrderByWithAggregationInputObjectSchema } from './objects/MediaOperationOrderByWithAggregationInput.schema';
import { MediaOperationScalarWhereWithAggregatesInputObjectSchema as MediaOperationScalarWhereWithAggregatesInputObjectSchema } from './objects/MediaOperationScalarWhereWithAggregatesInput.schema';
import { MediaOperationScalarFieldEnumSchema } from './enums/MediaOperationScalarFieldEnum.schema';
import { MediaOperationCountAggregateInputObjectSchema as MediaOperationCountAggregateInputObjectSchema } from './objects/MediaOperationCountAggregateInput.schema';
import { MediaOperationMinAggregateInputObjectSchema as MediaOperationMinAggregateInputObjectSchema } from './objects/MediaOperationMinAggregateInput.schema';
import { MediaOperationMaxAggregateInputObjectSchema as MediaOperationMaxAggregateInputObjectSchema } from './objects/MediaOperationMaxAggregateInput.schema';
import { MediaOperationAvgAggregateInputObjectSchema as MediaOperationAvgAggregateInputObjectSchema } from './objects/MediaOperationAvgAggregateInput.schema';
import { MediaOperationSumAggregateInputObjectSchema as MediaOperationSumAggregateInputObjectSchema } from './objects/MediaOperationSumAggregateInput.schema';

export const MediaOperationGroupBySchema: z.ZodType<Prisma.MediaOperationGroupByArgs> = z.object({ where: MediaOperationWhereInputObjectSchema.optional(), orderBy: z.union([MediaOperationOrderByWithAggregationInputObjectSchema, MediaOperationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MediaOperationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MediaOperationScalarFieldEnumSchema), _count: z.union([ z.literal(true), MediaOperationCountAggregateInputObjectSchema ]).optional(), _min: MediaOperationMinAggregateInputObjectSchema.optional(), _max: MediaOperationMaxAggregateInputObjectSchema.optional(), _avg: MediaOperationAvgAggregateInputObjectSchema.optional(), _sum: MediaOperationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MediaOperationGroupByArgs>;

export const MediaOperationGroupByZodSchema = z.object({ where: MediaOperationWhereInputObjectSchema.optional(), orderBy: z.union([MediaOperationOrderByWithAggregationInputObjectSchema, MediaOperationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MediaOperationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MediaOperationScalarFieldEnumSchema), _count: z.union([ z.literal(true), MediaOperationCountAggregateInputObjectSchema ]).optional(), _min: MediaOperationMinAggregateInputObjectSchema.optional(), _max: MediaOperationMaxAggregateInputObjectSchema.optional(), _avg: MediaOperationAvgAggregateInputObjectSchema.optional(), _sum: MediaOperationSumAggregateInputObjectSchema.optional() }).strict();