import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CarrierWebhookDeliveryWhereInputObjectSchema as CarrierWebhookDeliveryWhereInputObjectSchema } from './objects/CarrierWebhookDeliveryWhereInput.schema';
import { CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema as CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema } from './objects/CarrierWebhookDeliveryOrderByWithAggregationInput.schema';
import { CarrierWebhookDeliveryScalarWhereWithAggregatesInputObjectSchema as CarrierWebhookDeliveryScalarWhereWithAggregatesInputObjectSchema } from './objects/CarrierWebhookDeliveryScalarWhereWithAggregatesInput.schema';
import { CarrierWebhookDeliveryScalarFieldEnumSchema } from './enums/CarrierWebhookDeliveryScalarFieldEnum.schema';
import { CarrierWebhookDeliveryCountAggregateInputObjectSchema as CarrierWebhookDeliveryCountAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryCountAggregateInput.schema';
import { CarrierWebhookDeliveryMinAggregateInputObjectSchema as CarrierWebhookDeliveryMinAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryMinAggregateInput.schema';
import { CarrierWebhookDeliveryMaxAggregateInputObjectSchema as CarrierWebhookDeliveryMaxAggregateInputObjectSchema } from './objects/CarrierWebhookDeliveryMaxAggregateInput.schema';

export const CarrierWebhookDeliveryGroupBySchema: z.ZodType<Prisma.CarrierWebhookDeliveryGroupByArgs> = z.object({ where: CarrierWebhookDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema, CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierWebhookDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierWebhookDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierWebhookDeliveryCountAggregateInputObjectSchema ]).optional(), _min: CarrierWebhookDeliveryMinAggregateInputObjectSchema.optional(), _max: CarrierWebhookDeliveryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CarrierWebhookDeliveryGroupByArgs>;

export const CarrierWebhookDeliveryGroupByZodSchema = z.object({ where: CarrierWebhookDeliveryWhereInputObjectSchema.optional(), orderBy: z.union([CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema, CarrierWebhookDeliveryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierWebhookDeliveryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierWebhookDeliveryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierWebhookDeliveryCountAggregateInputObjectSchema ]).optional(), _min: CarrierWebhookDeliveryMinAggregateInputObjectSchema.optional(), _max: CarrierWebhookDeliveryMaxAggregateInputObjectSchema.optional() }).strict();