import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CarrierStatusHistoryWhereInputObjectSchema as CarrierStatusHistoryWhereInputObjectSchema } from './objects/CarrierStatusHistoryWhereInput.schema';
import { CarrierStatusHistoryOrderByWithAggregationInputObjectSchema as CarrierStatusHistoryOrderByWithAggregationInputObjectSchema } from './objects/CarrierStatusHistoryOrderByWithAggregationInput.schema';
import { CarrierStatusHistoryScalarWhereWithAggregatesInputObjectSchema as CarrierStatusHistoryScalarWhereWithAggregatesInputObjectSchema } from './objects/CarrierStatusHistoryScalarWhereWithAggregatesInput.schema';
import { CarrierStatusHistoryScalarFieldEnumSchema } from './enums/CarrierStatusHistoryScalarFieldEnum.schema';
import { CarrierStatusHistoryCountAggregateInputObjectSchema as CarrierStatusHistoryCountAggregateInputObjectSchema } from './objects/CarrierStatusHistoryCountAggregateInput.schema';
import { CarrierStatusHistoryMinAggregateInputObjectSchema as CarrierStatusHistoryMinAggregateInputObjectSchema } from './objects/CarrierStatusHistoryMinAggregateInput.schema';
import { CarrierStatusHistoryMaxAggregateInputObjectSchema as CarrierStatusHistoryMaxAggregateInputObjectSchema } from './objects/CarrierStatusHistoryMaxAggregateInput.schema';

export const CarrierStatusHistoryGroupBySchema: z.ZodType<Prisma.CarrierStatusHistoryGroupByArgs> = z.object({ where: CarrierStatusHistoryWhereInputObjectSchema.optional(), orderBy: z.union([CarrierStatusHistoryOrderByWithAggregationInputObjectSchema, CarrierStatusHistoryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierStatusHistoryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierStatusHistoryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierStatusHistoryCountAggregateInputObjectSchema ]).optional(), _min: CarrierStatusHistoryMinAggregateInputObjectSchema.optional(), _max: CarrierStatusHistoryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CarrierStatusHistoryGroupByArgs>;

export const CarrierStatusHistoryGroupByZodSchema = z.object({ where: CarrierStatusHistoryWhereInputObjectSchema.optional(), orderBy: z.union([CarrierStatusHistoryOrderByWithAggregationInputObjectSchema, CarrierStatusHistoryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierStatusHistoryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierStatusHistoryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierStatusHistoryCountAggregateInputObjectSchema ]).optional(), _min: CarrierStatusHistoryMinAggregateInputObjectSchema.optional(), _max: CarrierStatusHistoryMaxAggregateInputObjectSchema.optional() }).strict();