import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MediaLegacyManifestWhereInputObjectSchema as MediaLegacyManifestWhereInputObjectSchema } from './objects/MediaLegacyManifestWhereInput.schema';
import { MediaLegacyManifestOrderByWithAggregationInputObjectSchema as MediaLegacyManifestOrderByWithAggregationInputObjectSchema } from './objects/MediaLegacyManifestOrderByWithAggregationInput.schema';
import { MediaLegacyManifestScalarWhereWithAggregatesInputObjectSchema as MediaLegacyManifestScalarWhereWithAggregatesInputObjectSchema } from './objects/MediaLegacyManifestScalarWhereWithAggregatesInput.schema';
import { MediaLegacyManifestScalarFieldEnumSchema } from './enums/MediaLegacyManifestScalarFieldEnum.schema';
import { MediaLegacyManifestCountAggregateInputObjectSchema as MediaLegacyManifestCountAggregateInputObjectSchema } from './objects/MediaLegacyManifestCountAggregateInput.schema';
import { MediaLegacyManifestMinAggregateInputObjectSchema as MediaLegacyManifestMinAggregateInputObjectSchema } from './objects/MediaLegacyManifestMinAggregateInput.schema';
import { MediaLegacyManifestMaxAggregateInputObjectSchema as MediaLegacyManifestMaxAggregateInputObjectSchema } from './objects/MediaLegacyManifestMaxAggregateInput.schema';

export const MediaLegacyManifestGroupBySchema: z.ZodType<Prisma.MediaLegacyManifestGroupByArgs> = z.object({ where: MediaLegacyManifestWhereInputObjectSchema.optional(), orderBy: z.union([MediaLegacyManifestOrderByWithAggregationInputObjectSchema, MediaLegacyManifestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MediaLegacyManifestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MediaLegacyManifestScalarFieldEnumSchema), _count: z.union([ z.literal(true), MediaLegacyManifestCountAggregateInputObjectSchema ]).optional(), _min: MediaLegacyManifestMinAggregateInputObjectSchema.optional(), _max: MediaLegacyManifestMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MediaLegacyManifestGroupByArgs>;

export const MediaLegacyManifestGroupByZodSchema = z.object({ where: MediaLegacyManifestWhereInputObjectSchema.optional(), orderBy: z.union([MediaLegacyManifestOrderByWithAggregationInputObjectSchema, MediaLegacyManifestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MediaLegacyManifestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MediaLegacyManifestScalarFieldEnumSchema), _count: z.union([ z.literal(true), MediaLegacyManifestCountAggregateInputObjectSchema ]).optional(), _min: MediaLegacyManifestMinAggregateInputObjectSchema.optional(), _max: MediaLegacyManifestMaxAggregateInputObjectSchema.optional() }).strict();