import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkCaseActivityWhereInputObjectSchema as WorkCaseActivityWhereInputObjectSchema } from './objects/WorkCaseActivityWhereInput.schema';
import { WorkCaseActivityOrderByWithAggregationInputObjectSchema as WorkCaseActivityOrderByWithAggregationInputObjectSchema } from './objects/WorkCaseActivityOrderByWithAggregationInput.schema';
import { WorkCaseActivityScalarWhereWithAggregatesInputObjectSchema as WorkCaseActivityScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkCaseActivityScalarWhereWithAggregatesInput.schema';
import { WorkCaseActivityScalarFieldEnumSchema } from './enums/WorkCaseActivityScalarFieldEnum.schema';
import { WorkCaseActivityCountAggregateInputObjectSchema as WorkCaseActivityCountAggregateInputObjectSchema } from './objects/WorkCaseActivityCountAggregateInput.schema';
import { WorkCaseActivityMinAggregateInputObjectSchema as WorkCaseActivityMinAggregateInputObjectSchema } from './objects/WorkCaseActivityMinAggregateInput.schema';
import { WorkCaseActivityMaxAggregateInputObjectSchema as WorkCaseActivityMaxAggregateInputObjectSchema } from './objects/WorkCaseActivityMaxAggregateInput.schema';

export const WorkCaseActivityGroupBySchema: z.ZodType<Prisma.WorkCaseActivityGroupByArgs> = z.object({ where: WorkCaseActivityWhereInputObjectSchema.optional(), orderBy: z.union([WorkCaseActivityOrderByWithAggregationInputObjectSchema, WorkCaseActivityOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkCaseActivityScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkCaseActivityScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkCaseActivityCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseActivityMinAggregateInputObjectSchema.optional(), _max: WorkCaseActivityMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkCaseActivityGroupByArgs>;

export const WorkCaseActivityGroupByZodSchema = z.object({ where: WorkCaseActivityWhereInputObjectSchema.optional(), orderBy: z.union([WorkCaseActivityOrderByWithAggregationInputObjectSchema, WorkCaseActivityOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkCaseActivityScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkCaseActivityScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkCaseActivityCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseActivityMinAggregateInputObjectSchema.optional(), _max: WorkCaseActivityMaxAggregateInputObjectSchema.optional() }).strict();