import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestActivityWhereInputObjectSchema as PurchaseRequestActivityWhereInputObjectSchema } from './objects/PurchaseRequestActivityWhereInput.schema';
import { PurchaseRequestActivityOrderByWithAggregationInputObjectSchema as PurchaseRequestActivityOrderByWithAggregationInputObjectSchema } from './objects/PurchaseRequestActivityOrderByWithAggregationInput.schema';
import { PurchaseRequestActivityScalarWhereWithAggregatesInputObjectSchema as PurchaseRequestActivityScalarWhereWithAggregatesInputObjectSchema } from './objects/PurchaseRequestActivityScalarWhereWithAggregatesInput.schema';
import { PurchaseRequestActivityScalarFieldEnumSchema } from './enums/PurchaseRequestActivityScalarFieldEnum.schema';
import { PurchaseRequestActivityCountAggregateInputObjectSchema as PurchaseRequestActivityCountAggregateInputObjectSchema } from './objects/PurchaseRequestActivityCountAggregateInput.schema';
import { PurchaseRequestActivityMinAggregateInputObjectSchema as PurchaseRequestActivityMinAggregateInputObjectSchema } from './objects/PurchaseRequestActivityMinAggregateInput.schema';
import { PurchaseRequestActivityMaxAggregateInputObjectSchema as PurchaseRequestActivityMaxAggregateInputObjectSchema } from './objects/PurchaseRequestActivityMaxAggregateInput.schema';

export const PurchaseRequestActivityGroupBySchema: z.ZodType<Prisma.PurchaseRequestActivityGroupByArgs> = z.object({ where: PurchaseRequestActivityWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestActivityOrderByWithAggregationInputObjectSchema, PurchaseRequestActivityOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestActivityScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestActivityScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestActivityCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestActivityMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestActivityMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestActivityGroupByArgs>;

export const PurchaseRequestActivityGroupByZodSchema = z.object({ where: PurchaseRequestActivityWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestActivityOrderByWithAggregationInputObjectSchema, PurchaseRequestActivityOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestActivityScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestActivityScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestActivityCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestActivityMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestActivityMaxAggregateInputObjectSchema.optional() }).strict();