import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ShipmentPackageWhereInputObjectSchema as ShipmentPackageWhereInputObjectSchema } from './objects/ShipmentPackageWhereInput.schema';
import { ShipmentPackageOrderByWithAggregationInputObjectSchema as ShipmentPackageOrderByWithAggregationInputObjectSchema } from './objects/ShipmentPackageOrderByWithAggregationInput.schema';
import { ShipmentPackageScalarWhereWithAggregatesInputObjectSchema as ShipmentPackageScalarWhereWithAggregatesInputObjectSchema } from './objects/ShipmentPackageScalarWhereWithAggregatesInput.schema';
import { ShipmentPackageScalarFieldEnumSchema } from './enums/ShipmentPackageScalarFieldEnum.schema';
import { ShipmentPackageCountAggregateInputObjectSchema as ShipmentPackageCountAggregateInputObjectSchema } from './objects/ShipmentPackageCountAggregateInput.schema';
import { ShipmentPackageMinAggregateInputObjectSchema as ShipmentPackageMinAggregateInputObjectSchema } from './objects/ShipmentPackageMinAggregateInput.schema';
import { ShipmentPackageMaxAggregateInputObjectSchema as ShipmentPackageMaxAggregateInputObjectSchema } from './objects/ShipmentPackageMaxAggregateInput.schema';
import { ShipmentPackageAvgAggregateInputObjectSchema as ShipmentPackageAvgAggregateInputObjectSchema } from './objects/ShipmentPackageAvgAggregateInput.schema';
import { ShipmentPackageSumAggregateInputObjectSchema as ShipmentPackageSumAggregateInputObjectSchema } from './objects/ShipmentPackageSumAggregateInput.schema';

export const ShipmentPackageGroupBySchema: z.ZodType<Prisma.ShipmentPackageGroupByArgs> = z.object({ where: ShipmentPackageWhereInputObjectSchema.optional(), orderBy: z.union([ShipmentPackageOrderByWithAggregationInputObjectSchema, ShipmentPackageOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ShipmentPackageScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ShipmentPackageScalarFieldEnumSchema), _count: z.union([ z.literal(true), ShipmentPackageCountAggregateInputObjectSchema ]).optional(), _min: ShipmentPackageMinAggregateInputObjectSchema.optional(), _max: ShipmentPackageMaxAggregateInputObjectSchema.optional(), _avg: ShipmentPackageAvgAggregateInputObjectSchema.optional(), _sum: ShipmentPackageSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ShipmentPackageGroupByArgs>;

export const ShipmentPackageGroupByZodSchema = z.object({ where: ShipmentPackageWhereInputObjectSchema.optional(), orderBy: z.union([ShipmentPackageOrderByWithAggregationInputObjectSchema, ShipmentPackageOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ShipmentPackageScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ShipmentPackageScalarFieldEnumSchema), _count: z.union([ z.literal(true), ShipmentPackageCountAggregateInputObjectSchema ]).optional(), _min: ShipmentPackageMinAggregateInputObjectSchema.optional(), _max: ShipmentPackageMaxAggregateInputObjectSchema.optional(), _avg: ShipmentPackageAvgAggregateInputObjectSchema.optional(), _sum: ShipmentPackageSumAggregateInputObjectSchema.optional() }).strict();