import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WatchStrapInstallationWhereInputObjectSchema as WatchStrapInstallationWhereInputObjectSchema } from './objects/WatchStrapInstallationWhereInput.schema';
import { WatchStrapInstallationOrderByWithAggregationInputObjectSchema as WatchStrapInstallationOrderByWithAggregationInputObjectSchema } from './objects/WatchStrapInstallationOrderByWithAggregationInput.schema';
import { WatchStrapInstallationScalarWhereWithAggregatesInputObjectSchema as WatchStrapInstallationScalarWhereWithAggregatesInputObjectSchema } from './objects/WatchStrapInstallationScalarWhereWithAggregatesInput.schema';
import { WatchStrapInstallationScalarFieldEnumSchema } from './enums/WatchStrapInstallationScalarFieldEnum.schema';
import { WatchStrapInstallationCountAggregateInputObjectSchema as WatchStrapInstallationCountAggregateInputObjectSchema } from './objects/WatchStrapInstallationCountAggregateInput.schema';
import { WatchStrapInstallationMinAggregateInputObjectSchema as WatchStrapInstallationMinAggregateInputObjectSchema } from './objects/WatchStrapInstallationMinAggregateInput.schema';
import { WatchStrapInstallationMaxAggregateInputObjectSchema as WatchStrapInstallationMaxAggregateInputObjectSchema } from './objects/WatchStrapInstallationMaxAggregateInput.schema';
import { WatchStrapInstallationAvgAggregateInputObjectSchema as WatchStrapInstallationAvgAggregateInputObjectSchema } from './objects/WatchStrapInstallationAvgAggregateInput.schema';
import { WatchStrapInstallationSumAggregateInputObjectSchema as WatchStrapInstallationSumAggregateInputObjectSchema } from './objects/WatchStrapInstallationSumAggregateInput.schema';

export const WatchStrapInstallationGroupBySchema: z.ZodType<Prisma.WatchStrapInstallationGroupByArgs> = z.object({ where: WatchStrapInstallationWhereInputObjectSchema.optional(), orderBy: z.union([WatchStrapInstallationOrderByWithAggregationInputObjectSchema, WatchStrapInstallationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WatchStrapInstallationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WatchStrapInstallationScalarFieldEnumSchema), _count: z.union([ z.literal(true), WatchStrapInstallationCountAggregateInputObjectSchema ]).optional(), _min: WatchStrapInstallationMinAggregateInputObjectSchema.optional(), _max: WatchStrapInstallationMaxAggregateInputObjectSchema.optional(), _avg: WatchStrapInstallationAvgAggregateInputObjectSchema.optional(), _sum: WatchStrapInstallationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WatchStrapInstallationGroupByArgs>;

export const WatchStrapInstallationGroupByZodSchema = z.object({ where: WatchStrapInstallationWhereInputObjectSchema.optional(), orderBy: z.union([WatchStrapInstallationOrderByWithAggregationInputObjectSchema, WatchStrapInstallationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WatchStrapInstallationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WatchStrapInstallationScalarFieldEnumSchema), _count: z.union([ z.literal(true), WatchStrapInstallationCountAggregateInputObjectSchema ]).optional(), _min: WatchStrapInstallationMinAggregateInputObjectSchema.optional(), _max: WatchStrapInstallationMaxAggregateInputObjectSchema.optional(), _avg: WatchStrapInstallationAvgAggregateInputObjectSchema.optional(), _sum: WatchStrapInstallationSumAggregateInputObjectSchema.optional() }).strict();