import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowActionWhereInputObjectSchema as WorkflowActionWhereInputObjectSchema } from './objects/WorkflowActionWhereInput.schema';
import { WorkflowActionOrderByWithAggregationInputObjectSchema as WorkflowActionOrderByWithAggregationInputObjectSchema } from './objects/WorkflowActionOrderByWithAggregationInput.schema';
import { WorkflowActionScalarWhereWithAggregatesInputObjectSchema as WorkflowActionScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkflowActionScalarWhereWithAggregatesInput.schema';
import { WorkflowActionScalarFieldEnumSchema } from './enums/WorkflowActionScalarFieldEnum.schema';
import { WorkflowActionCountAggregateInputObjectSchema as WorkflowActionCountAggregateInputObjectSchema } from './objects/WorkflowActionCountAggregateInput.schema';
import { WorkflowActionMinAggregateInputObjectSchema as WorkflowActionMinAggregateInputObjectSchema } from './objects/WorkflowActionMinAggregateInput.schema';
import { WorkflowActionMaxAggregateInputObjectSchema as WorkflowActionMaxAggregateInputObjectSchema } from './objects/WorkflowActionMaxAggregateInput.schema';
import { WorkflowActionAvgAggregateInputObjectSchema as WorkflowActionAvgAggregateInputObjectSchema } from './objects/WorkflowActionAvgAggregateInput.schema';
import { WorkflowActionSumAggregateInputObjectSchema as WorkflowActionSumAggregateInputObjectSchema } from './objects/WorkflowActionSumAggregateInput.schema';

export const WorkflowActionGroupBySchema: z.ZodType<Prisma.WorkflowActionGroupByArgs> = z.object({ where: WorkflowActionWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowActionOrderByWithAggregationInputObjectSchema, WorkflowActionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowActionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowActionScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowActionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowActionMinAggregateInputObjectSchema.optional(), _max: WorkflowActionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowActionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowActionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowActionGroupByArgs>;

export const WorkflowActionGroupByZodSchema = z.object({ where: WorkflowActionWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowActionOrderByWithAggregationInputObjectSchema, WorkflowActionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowActionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowActionScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowActionCountAggregateInputObjectSchema ]).optional(), _min: WorkflowActionMinAggregateInputObjectSchema.optional(), _max: WorkflowActionMaxAggregateInputObjectSchema.optional(), _avg: WorkflowActionAvgAggregateInputObjectSchema.optional(), _sum: WorkflowActionSumAggregateInputObjectSchema.optional() }).strict();