import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AcquisitionSpecJobLogWhereInputObjectSchema as AcquisitionSpecJobLogWhereInputObjectSchema } from './objects/AcquisitionSpecJobLogWhereInput.schema';
import { AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema as AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema } from './objects/AcquisitionSpecJobLogOrderByWithAggregationInput.schema';
import { AcquisitionSpecJobLogScalarWhereWithAggregatesInputObjectSchema as AcquisitionSpecJobLogScalarWhereWithAggregatesInputObjectSchema } from './objects/AcquisitionSpecJobLogScalarWhereWithAggregatesInput.schema';
import { AcquisitionSpecJobLogScalarFieldEnumSchema } from './enums/AcquisitionSpecJobLogScalarFieldEnum.schema';
import { AcquisitionSpecJobLogCountAggregateInputObjectSchema as AcquisitionSpecJobLogCountAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogCountAggregateInput.schema';
import { AcquisitionSpecJobLogMinAggregateInputObjectSchema as AcquisitionSpecJobLogMinAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogMinAggregateInput.schema';
import { AcquisitionSpecJobLogMaxAggregateInputObjectSchema as AcquisitionSpecJobLogMaxAggregateInputObjectSchema } from './objects/AcquisitionSpecJobLogMaxAggregateInput.schema';

export const AcquisitionSpecJobLogGroupBySchema: z.ZodType<Prisma.AcquisitionSpecJobLogGroupByArgs> = z.object({ where: AcquisitionSpecJobLogWhereInputObjectSchema.optional(), orderBy: z.union([AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema, AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AcquisitionSpecJobLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), AcquisitionSpecJobLogCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobLogMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobLogMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AcquisitionSpecJobLogGroupByArgs>;

export const AcquisitionSpecJobLogGroupByZodSchema = z.object({ where: AcquisitionSpecJobLogWhereInputObjectSchema.optional(), orderBy: z.union([AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema, AcquisitionSpecJobLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AcquisitionSpecJobLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), AcquisitionSpecJobLogCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobLogMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobLogMaxAggregateInputObjectSchema.optional() }).strict();