import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkCaseCategoryWhereInputObjectSchema as WorkCaseCategoryWhereInputObjectSchema } from './objects/WorkCaseCategoryWhereInput.schema';
import { WorkCaseCategoryOrderByWithAggregationInputObjectSchema as WorkCaseCategoryOrderByWithAggregationInputObjectSchema } from './objects/WorkCaseCategoryOrderByWithAggregationInput.schema';
import { WorkCaseCategoryScalarWhereWithAggregatesInputObjectSchema as WorkCaseCategoryScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkCaseCategoryScalarWhereWithAggregatesInput.schema';
import { WorkCaseCategoryScalarFieldEnumSchema } from './enums/WorkCaseCategoryScalarFieldEnum.schema';
import { WorkCaseCategoryCountAggregateInputObjectSchema as WorkCaseCategoryCountAggregateInputObjectSchema } from './objects/WorkCaseCategoryCountAggregateInput.schema';
import { WorkCaseCategoryMinAggregateInputObjectSchema as WorkCaseCategoryMinAggregateInputObjectSchema } from './objects/WorkCaseCategoryMinAggregateInput.schema';
import { WorkCaseCategoryMaxAggregateInputObjectSchema as WorkCaseCategoryMaxAggregateInputObjectSchema } from './objects/WorkCaseCategoryMaxAggregateInput.schema';
import { WorkCaseCategoryAvgAggregateInputObjectSchema as WorkCaseCategoryAvgAggregateInputObjectSchema } from './objects/WorkCaseCategoryAvgAggregateInput.schema';
import { WorkCaseCategorySumAggregateInputObjectSchema as WorkCaseCategorySumAggregateInputObjectSchema } from './objects/WorkCaseCategorySumAggregateInput.schema';

export const WorkCaseCategoryGroupBySchema: z.ZodType<Prisma.WorkCaseCategoryGroupByArgs> = z.object({ where: WorkCaseCategoryWhereInputObjectSchema.optional(), orderBy: z.union([WorkCaseCategoryOrderByWithAggregationInputObjectSchema, WorkCaseCategoryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkCaseCategoryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkCaseCategoryScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkCaseCategoryCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseCategoryMinAggregateInputObjectSchema.optional(), _max: WorkCaseCategoryMaxAggregateInputObjectSchema.optional(), _avg: WorkCaseCategoryAvgAggregateInputObjectSchema.optional(), _sum: WorkCaseCategorySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkCaseCategoryGroupByArgs>;

export const WorkCaseCategoryGroupByZodSchema = z.object({ where: WorkCaseCategoryWhereInputObjectSchema.optional(), orderBy: z.union([WorkCaseCategoryOrderByWithAggregationInputObjectSchema, WorkCaseCategoryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkCaseCategoryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkCaseCategoryScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkCaseCategoryCountAggregateInputObjectSchema ]).optional(), _min: WorkCaseCategoryMinAggregateInputObjectSchema.optional(), _max: WorkCaseCategoryMaxAggregateInputObjectSchema.optional(), _avg: WorkCaseCategoryAvgAggregateInputObjectSchema.optional(), _sum: WorkCaseCategorySumAggregateInputObjectSchema.optional() }).strict();