import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CarrierRequestWhereInputObjectSchema as CarrierRequestWhereInputObjectSchema } from './objects/CarrierRequestWhereInput.schema';
import { CarrierRequestOrderByWithAggregationInputObjectSchema as CarrierRequestOrderByWithAggregationInputObjectSchema } from './objects/CarrierRequestOrderByWithAggregationInput.schema';
import { CarrierRequestScalarWhereWithAggregatesInputObjectSchema as CarrierRequestScalarWhereWithAggregatesInputObjectSchema } from './objects/CarrierRequestScalarWhereWithAggregatesInput.schema';
import { CarrierRequestScalarFieldEnumSchema } from './enums/CarrierRequestScalarFieldEnum.schema';
import { CarrierRequestCountAggregateInputObjectSchema as CarrierRequestCountAggregateInputObjectSchema } from './objects/CarrierRequestCountAggregateInput.schema';
import { CarrierRequestMinAggregateInputObjectSchema as CarrierRequestMinAggregateInputObjectSchema } from './objects/CarrierRequestMinAggregateInput.schema';
import { CarrierRequestMaxAggregateInputObjectSchema as CarrierRequestMaxAggregateInputObjectSchema } from './objects/CarrierRequestMaxAggregateInput.schema';
import { CarrierRequestAvgAggregateInputObjectSchema as CarrierRequestAvgAggregateInputObjectSchema } from './objects/CarrierRequestAvgAggregateInput.schema';
import { CarrierRequestSumAggregateInputObjectSchema as CarrierRequestSumAggregateInputObjectSchema } from './objects/CarrierRequestSumAggregateInput.schema';

export const CarrierRequestGroupBySchema: z.ZodType<Prisma.CarrierRequestGroupByArgs> = z.object({ where: CarrierRequestWhereInputObjectSchema.optional(), orderBy: z.union([CarrierRequestOrderByWithAggregationInputObjectSchema, CarrierRequestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierRequestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierRequestScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierRequestCountAggregateInputObjectSchema ]).optional(), _min: CarrierRequestMinAggregateInputObjectSchema.optional(), _max: CarrierRequestMaxAggregateInputObjectSchema.optional(), _avg: CarrierRequestAvgAggregateInputObjectSchema.optional(), _sum: CarrierRequestSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CarrierRequestGroupByArgs>;

export const CarrierRequestGroupByZodSchema = z.object({ where: CarrierRequestWhereInputObjectSchema.optional(), orderBy: z.union([CarrierRequestOrderByWithAggregationInputObjectSchema, CarrierRequestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CarrierRequestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CarrierRequestScalarFieldEnumSchema), _count: z.union([ z.literal(true), CarrierRequestCountAggregateInputObjectSchema ]).optional(), _min: CarrierRequestMinAggregateInputObjectSchema.optional(), _max: CarrierRequestMaxAggregateInputObjectSchema.optional(), _avg: CarrierRequestAvgAggregateInputObjectSchema.optional(), _sum: CarrierRequestSumAggregateInputObjectSchema.optional() }).strict();