import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PurchaseRequestIngressReceiptWhereInputObjectSchema as PurchaseRequestIngressReceiptWhereInputObjectSchema } from './objects/PurchaseRequestIngressReceiptWhereInput.schema';
import { PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema as PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema } from './objects/PurchaseRequestIngressReceiptOrderByWithAggregationInput.schema';
import { PurchaseRequestIngressReceiptScalarWhereWithAggregatesInputObjectSchema as PurchaseRequestIngressReceiptScalarWhereWithAggregatesInputObjectSchema } from './objects/PurchaseRequestIngressReceiptScalarWhereWithAggregatesInput.schema';
import { PurchaseRequestIngressReceiptScalarFieldEnumSchema } from './enums/PurchaseRequestIngressReceiptScalarFieldEnum.schema';
import { PurchaseRequestIngressReceiptCountAggregateInputObjectSchema as PurchaseRequestIngressReceiptCountAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptCountAggregateInput.schema';
import { PurchaseRequestIngressReceiptMinAggregateInputObjectSchema as PurchaseRequestIngressReceiptMinAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptMinAggregateInput.schema';
import { PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema as PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptMaxAggregateInput.schema';
import { PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema as PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptAvgAggregateInput.schema';
import { PurchaseRequestIngressReceiptSumAggregateInputObjectSchema as PurchaseRequestIngressReceiptSumAggregateInputObjectSchema } from './objects/PurchaseRequestIngressReceiptSumAggregateInput.schema';

export const PurchaseRequestIngressReceiptGroupBySchema: z.ZodType<Prisma.PurchaseRequestIngressReceiptGroupByArgs> = z.object({ where: PurchaseRequestIngressReceiptWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema, PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestIngressReceiptScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestIngressReceiptScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestIngressReceiptMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestIngressReceiptSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseRequestIngressReceiptGroupByArgs>;

export const PurchaseRequestIngressReceiptGroupByZodSchema = z.object({ where: PurchaseRequestIngressReceiptWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema, PurchaseRequestIngressReceiptOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseRequestIngressReceiptScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseRequestIngressReceiptScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseRequestIngressReceiptCountAggregateInputObjectSchema ]).optional(), _min: PurchaseRequestIngressReceiptMinAggregateInputObjectSchema.optional(), _max: PurchaseRequestIngressReceiptMaxAggregateInputObjectSchema.optional(), _avg: PurchaseRequestIngressReceiptAvgAggregateInputObjectSchema.optional(), _sum: PurchaseRequestIngressReceiptSumAggregateInputObjectSchema.optional() }).strict();