import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { NotificationRecipientGroupWhereInputObjectSchema as NotificationRecipientGroupWhereInputObjectSchema } from './objects/NotificationRecipientGroupWhereInput.schema';
import { NotificationRecipientGroupOrderByWithAggregationInputObjectSchema as NotificationRecipientGroupOrderByWithAggregationInputObjectSchema } from './objects/NotificationRecipientGroupOrderByWithAggregationInput.schema';
import { NotificationRecipientGroupScalarWhereWithAggregatesInputObjectSchema as NotificationRecipientGroupScalarWhereWithAggregatesInputObjectSchema } from './objects/NotificationRecipientGroupScalarWhereWithAggregatesInput.schema';
import { NotificationRecipientGroupScalarFieldEnumSchema } from './enums/NotificationRecipientGroupScalarFieldEnum.schema';
import { NotificationRecipientGroupCountAggregateInputObjectSchema as NotificationRecipientGroupCountAggregateInputObjectSchema } from './objects/NotificationRecipientGroupCountAggregateInput.schema';
import { NotificationRecipientGroupMinAggregateInputObjectSchema as NotificationRecipientGroupMinAggregateInputObjectSchema } from './objects/NotificationRecipientGroupMinAggregateInput.schema';
import { NotificationRecipientGroupMaxAggregateInputObjectSchema as NotificationRecipientGroupMaxAggregateInputObjectSchema } from './objects/NotificationRecipientGroupMaxAggregateInput.schema';

export const NotificationRecipientGroupGroupBySchema: z.ZodType<Prisma.NotificationRecipientGroupGroupByArgs> = z.object({ where: NotificationRecipientGroupWhereInputObjectSchema.optional(), orderBy: z.union([NotificationRecipientGroupOrderByWithAggregationInputObjectSchema, NotificationRecipientGroupOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationRecipientGroupScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationRecipientGroupScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationRecipientGroupCountAggregateInputObjectSchema ]).optional(), _min: NotificationRecipientGroupMinAggregateInputObjectSchema.optional(), _max: NotificationRecipientGroupMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.NotificationRecipientGroupGroupByArgs>;

export const NotificationRecipientGroupGroupByZodSchema = z.object({ where: NotificationRecipientGroupWhereInputObjectSchema.optional(), orderBy: z.union([NotificationRecipientGroupOrderByWithAggregationInputObjectSchema, NotificationRecipientGroupOrderByWithAggregationInputObjectSchema.array()]).optional(), having: NotificationRecipientGroupScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(NotificationRecipientGroupScalarFieldEnumSchema), _count: z.union([ z.literal(true), NotificationRecipientGroupCountAggregateInputObjectSchema ]).optional(), _min: NotificationRecipientGroupMinAggregateInputObjectSchema.optional(), _max: NotificationRecipientGroupMaxAggregateInputObjectSchema.optional() }).strict();