import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { WorkflowEventLogWhereInputObjectSchema as WorkflowEventLogWhereInputObjectSchema } from './objects/WorkflowEventLogWhereInput.schema';
import { WorkflowEventLogOrderByWithAggregationInputObjectSchema as WorkflowEventLogOrderByWithAggregationInputObjectSchema } from './objects/WorkflowEventLogOrderByWithAggregationInput.schema';
import { WorkflowEventLogScalarWhereWithAggregatesInputObjectSchema as WorkflowEventLogScalarWhereWithAggregatesInputObjectSchema } from './objects/WorkflowEventLogScalarWhereWithAggregatesInput.schema';
import { WorkflowEventLogScalarFieldEnumSchema } from './enums/WorkflowEventLogScalarFieldEnum.schema';
import { WorkflowEventLogCountAggregateInputObjectSchema as WorkflowEventLogCountAggregateInputObjectSchema } from './objects/WorkflowEventLogCountAggregateInput.schema';
import { WorkflowEventLogMinAggregateInputObjectSchema as WorkflowEventLogMinAggregateInputObjectSchema } from './objects/WorkflowEventLogMinAggregateInput.schema';
import { WorkflowEventLogMaxAggregateInputObjectSchema as WorkflowEventLogMaxAggregateInputObjectSchema } from './objects/WorkflowEventLogMaxAggregateInput.schema';

export const WorkflowEventLogGroupBySchema: z.ZodType<Prisma.WorkflowEventLogGroupByArgs> = z.object({ where: WorkflowEventLogWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowEventLogOrderByWithAggregationInputObjectSchema, WorkflowEventLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowEventLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowEventLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowEventLogCountAggregateInputObjectSchema ]).optional(), _min: WorkflowEventLogMinAggregateInputObjectSchema.optional(), _max: WorkflowEventLogMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.WorkflowEventLogGroupByArgs>;

export const WorkflowEventLogGroupByZodSchema = z.object({ where: WorkflowEventLogWhereInputObjectSchema.optional(), orderBy: z.union([WorkflowEventLogOrderByWithAggregationInputObjectSchema, WorkflowEventLogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: WorkflowEventLogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(WorkflowEventLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), WorkflowEventLogCountAggregateInputObjectSchema ]).optional(), _min: WorkflowEventLogMinAggregateInputObjectSchema.optional(), _max: WorkflowEventLogMaxAggregateInputObjectSchema.optional() }).strict();