import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { StorefrontHeroImageWhereInputObjectSchema as StorefrontHeroImageWhereInputObjectSchema } from './objects/StorefrontHeroImageWhereInput.schema';
import { StorefrontHeroImageOrderByWithAggregationInputObjectSchema as StorefrontHeroImageOrderByWithAggregationInputObjectSchema } from './objects/StorefrontHeroImageOrderByWithAggregationInput.schema';
import { StorefrontHeroImageScalarWhereWithAggregatesInputObjectSchema as StorefrontHeroImageScalarWhereWithAggregatesInputObjectSchema } from './objects/StorefrontHeroImageScalarWhereWithAggregatesInput.schema';
import { StorefrontHeroImageScalarFieldEnumSchema } from './enums/StorefrontHeroImageScalarFieldEnum.schema';
import { StorefrontHeroImageCountAggregateInputObjectSchema as StorefrontHeroImageCountAggregateInputObjectSchema } from './objects/StorefrontHeroImageCountAggregateInput.schema';
import { StorefrontHeroImageMinAggregateInputObjectSchema as StorefrontHeroImageMinAggregateInputObjectSchema } from './objects/StorefrontHeroImageMinAggregateInput.schema';
import { StorefrontHeroImageMaxAggregateInputObjectSchema as StorefrontHeroImageMaxAggregateInputObjectSchema } from './objects/StorefrontHeroImageMaxAggregateInput.schema';
import { StorefrontHeroImageAvgAggregateInputObjectSchema as StorefrontHeroImageAvgAggregateInputObjectSchema } from './objects/StorefrontHeroImageAvgAggregateInput.schema';
import { StorefrontHeroImageSumAggregateInputObjectSchema as StorefrontHeroImageSumAggregateInputObjectSchema } from './objects/StorefrontHeroImageSumAggregateInput.schema';

export const StorefrontHeroImageGroupBySchema: z.ZodType<Prisma.StorefrontHeroImageGroupByArgs> = z.object({ where: StorefrontHeroImageWhereInputObjectSchema.optional(), orderBy: z.union([StorefrontHeroImageOrderByWithAggregationInputObjectSchema, StorefrontHeroImageOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StorefrontHeroImageScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StorefrontHeroImageScalarFieldEnumSchema), _count: z.union([ z.literal(true), StorefrontHeroImageCountAggregateInputObjectSchema ]).optional(), _min: StorefrontHeroImageMinAggregateInputObjectSchema.optional(), _max: StorefrontHeroImageMaxAggregateInputObjectSchema.optional(), _avg: StorefrontHeroImageAvgAggregateInputObjectSchema.optional(), _sum: StorefrontHeroImageSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.StorefrontHeroImageGroupByArgs>;

export const StorefrontHeroImageGroupByZodSchema = z.object({ where: StorefrontHeroImageWhereInputObjectSchema.optional(), orderBy: z.union([StorefrontHeroImageOrderByWithAggregationInputObjectSchema, StorefrontHeroImageOrderByWithAggregationInputObjectSchema.array()]).optional(), having: StorefrontHeroImageScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(StorefrontHeroImageScalarFieldEnumSchema), _count: z.union([ z.literal(true), StorefrontHeroImageCountAggregateInputObjectSchema ]).optional(), _min: StorefrontHeroImageMinAggregateInputObjectSchema.optional(), _max: StorefrontHeroImageMaxAggregateInputObjectSchema.optional(), _avg: StorefrontHeroImageAvgAggregateInputObjectSchema.optional(), _sum: StorefrontHeroImageSumAggregateInputObjectSchema.optional() }).strict();