import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { acquisition_spec_jobWhereInputObjectSchema as acquisition_spec_jobWhereInputObjectSchema } from './objects/acquisition_spec_jobWhereInput.schema';
import { acquisition_spec_jobOrderByWithAggregationInputObjectSchema as acquisition_spec_jobOrderByWithAggregationInputObjectSchema } from './objects/acquisition_spec_jobOrderByWithAggregationInput.schema';
import { acquisition_spec_jobScalarWhereWithAggregatesInputObjectSchema as acquisition_spec_jobScalarWhereWithAggregatesInputObjectSchema } from './objects/acquisition_spec_jobScalarWhereWithAggregatesInput.schema';
import { AcquisitionSpecJobScalarFieldEnumSchema } from './enums/AcquisitionSpecJobScalarFieldEnum.schema';
import { Acquisition_spec_jobCountAggregateInputObjectSchema as Acquisition_spec_jobCountAggregateInputObjectSchema } from './objects/Acquisition_spec_jobCountAggregateInput.schema';
import { Acquisition_spec_jobMinAggregateInputObjectSchema as Acquisition_spec_jobMinAggregateInputObjectSchema } from './objects/Acquisition_spec_jobMinAggregateInput.schema';
import { Acquisition_spec_jobMaxAggregateInputObjectSchema as Acquisition_spec_jobMaxAggregateInputObjectSchema } from './objects/Acquisition_spec_jobMaxAggregateInput.schema';
import { Acquisition_spec_jobAvgAggregateInputObjectSchema as Acquisition_spec_jobAvgAggregateInputObjectSchema } from './objects/Acquisition_spec_jobAvgAggregateInput.schema';
import { Acquisition_spec_jobSumAggregateInputObjectSchema as Acquisition_spec_jobSumAggregateInputObjectSchema } from './objects/Acquisition_spec_jobSumAggregateInput.schema';

export const acquisition_spec_jobGroupBySchema: z.ZodType<Prisma.acquisition_spec_jobGroupByArgs> = z.object({ where: acquisition_spec_jobWhereInputObjectSchema.optional(), orderBy: z.union([acquisition_spec_jobOrderByWithAggregationInputObjectSchema, acquisition_spec_jobOrderByWithAggregationInputObjectSchema.array()]).optional(), having: acquisition_spec_jobScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobScalarFieldEnumSchema), _count: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional(), _min: Acquisition_spec_jobMinAggregateInputObjectSchema.optional(), _max: Acquisition_spec_jobMaxAggregateInputObjectSchema.optional(), _avg: Acquisition_spec_jobAvgAggregateInputObjectSchema.optional(), _sum: Acquisition_spec_jobSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.acquisition_spec_jobGroupByArgs>;

export const acquisition_spec_jobGroupByZodSchema = z.object({ where: acquisition_spec_jobWhereInputObjectSchema.optional(), orderBy: z.union([acquisition_spec_jobOrderByWithAggregationInputObjectSchema, acquisition_spec_jobOrderByWithAggregationInputObjectSchema.array()]).optional(), having: acquisition_spec_jobScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobScalarFieldEnumSchema), _count: z.union([ z.literal(true), Acquisition_spec_jobCountAggregateInputObjectSchema ]).optional(), _min: Acquisition_spec_jobMinAggregateInputObjectSchema.optional(), _max: Acquisition_spec_jobMaxAggregateInputObjectSchema.optional(), _avg: Acquisition_spec_jobAvgAggregateInputObjectSchema.optional(), _sum: Acquisition_spec_jobSumAggregateInputObjectSchema.optional() }).strict();