import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ClaspVariantSpecWhereInputObjectSchema as ClaspVariantSpecWhereInputObjectSchema } from './objects/ClaspVariantSpecWhereInput.schema';
import { ClaspVariantSpecOrderByWithAggregationInputObjectSchema as ClaspVariantSpecOrderByWithAggregationInputObjectSchema } from './objects/ClaspVariantSpecOrderByWithAggregationInput.schema';
import { ClaspVariantSpecScalarWhereWithAggregatesInputObjectSchema as ClaspVariantSpecScalarWhereWithAggregatesInputObjectSchema } from './objects/ClaspVariantSpecScalarWhereWithAggregatesInput.schema';
import { ClaspVariantSpecScalarFieldEnumSchema } from './enums/ClaspVariantSpecScalarFieldEnum.schema';
import { ClaspVariantSpecCountAggregateInputObjectSchema as ClaspVariantSpecCountAggregateInputObjectSchema } from './objects/ClaspVariantSpecCountAggregateInput.schema';
import { ClaspVariantSpecMinAggregateInputObjectSchema as ClaspVariantSpecMinAggregateInputObjectSchema } from './objects/ClaspVariantSpecMinAggregateInput.schema';
import { ClaspVariantSpecMaxAggregateInputObjectSchema as ClaspVariantSpecMaxAggregateInputObjectSchema } from './objects/ClaspVariantSpecMaxAggregateInput.schema';
import { ClaspVariantSpecAvgAggregateInputObjectSchema as ClaspVariantSpecAvgAggregateInputObjectSchema } from './objects/ClaspVariantSpecAvgAggregateInput.schema';
import { ClaspVariantSpecSumAggregateInputObjectSchema as ClaspVariantSpecSumAggregateInputObjectSchema } from './objects/ClaspVariantSpecSumAggregateInput.schema';

export const ClaspVariantSpecGroupBySchema: z.ZodType<Prisma.ClaspVariantSpecGroupByArgs> = z.object({ where: ClaspVariantSpecWhereInputObjectSchema.optional(), orderBy: z.union([ClaspVariantSpecOrderByWithAggregationInputObjectSchema, ClaspVariantSpecOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClaspVariantSpecScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClaspVariantSpecScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClaspVariantSpecCountAggregateInputObjectSchema ]).optional(), _min: ClaspVariantSpecMinAggregateInputObjectSchema.optional(), _max: ClaspVariantSpecMaxAggregateInputObjectSchema.optional(), _avg: ClaspVariantSpecAvgAggregateInputObjectSchema.optional(), _sum: ClaspVariantSpecSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ClaspVariantSpecGroupByArgs>;

export const ClaspVariantSpecGroupByZodSchema = z.object({ where: ClaspVariantSpecWhereInputObjectSchema.optional(), orderBy: z.union([ClaspVariantSpecOrderByWithAggregationInputObjectSchema, ClaspVariantSpecOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClaspVariantSpecScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClaspVariantSpecScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClaspVariantSpecCountAggregateInputObjectSchema ]).optional(), _min: ClaspVariantSpecMinAggregateInputObjectSchema.optional(), _max: ClaspVariantSpecMaxAggregateInputObjectSchema.optional(), _avg: ClaspVariantSpecAvgAggregateInputObjectSchema.optional(), _sum: ClaspVariantSpecSumAggregateInputObjectSchema.optional() }).strict();