import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaskItemActivityReplyWhereInputObjectSchema as TaskItemActivityReplyWhereInputObjectSchema } from './objects/TaskItemActivityReplyWhereInput.schema';
import { TaskItemActivityReplyOrderByWithAggregationInputObjectSchema as TaskItemActivityReplyOrderByWithAggregationInputObjectSchema } from './objects/TaskItemActivityReplyOrderByWithAggregationInput.schema';
import { TaskItemActivityReplyScalarWhereWithAggregatesInputObjectSchema as TaskItemActivityReplyScalarWhereWithAggregatesInputObjectSchema } from './objects/TaskItemActivityReplyScalarWhereWithAggregatesInput.schema';
import { TaskItemActivityReplyScalarFieldEnumSchema } from './enums/TaskItemActivityReplyScalarFieldEnum.schema';
import { TaskItemActivityReplyCountAggregateInputObjectSchema as TaskItemActivityReplyCountAggregateInputObjectSchema } from './objects/TaskItemActivityReplyCountAggregateInput.schema';
import { TaskItemActivityReplyMinAggregateInputObjectSchema as TaskItemActivityReplyMinAggregateInputObjectSchema } from './objects/TaskItemActivityReplyMinAggregateInput.schema';
import { TaskItemActivityReplyMaxAggregateInputObjectSchema as TaskItemActivityReplyMaxAggregateInputObjectSchema } from './objects/TaskItemActivityReplyMaxAggregateInput.schema';

export const TaskItemActivityReplyGroupBySchema: z.ZodType<Prisma.TaskItemActivityReplyGroupByArgs> = z.object({ where: TaskItemActivityReplyWhereInputObjectSchema.optional(), orderBy: z.union([TaskItemActivityReplyOrderByWithAggregationInputObjectSchema, TaskItemActivityReplyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskItemActivityReplyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskItemActivityReplyScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskItemActivityReplyCountAggregateInputObjectSchema ]).optional(), _min: TaskItemActivityReplyMinAggregateInputObjectSchema.optional(), _max: TaskItemActivityReplyMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaskItemActivityReplyGroupByArgs>;

export const TaskItemActivityReplyGroupByZodSchema = z.object({ where: TaskItemActivityReplyWhereInputObjectSchema.optional(), orderBy: z.union([TaskItemActivityReplyOrderByWithAggregationInputObjectSchema, TaskItemActivityReplyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaskItemActivityReplyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaskItemActivityReplyScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaskItemActivityReplyCountAggregateInputObjectSchema ]).optional(), _min: TaskItemActivityReplyMinAggregateInputObjectSchema.optional(), _max: TaskItemActivityReplyMaxAggregateInputObjectSchema.optional() }).strict();